<?php
require "../class/include.php";

file::head("Filosofia Teoretica - Appunti");

toc::show_toc("Filosofia_Teoretica/appunti.php");
?>

<?php t("4", "23/02/2011"); ?>
<p>"L'immaginazione è necessariamente un tratto che dobbiamo per forza pensare come caratteristico di una vita animale?""Quali possono essere le ragioni per cui immaginiamo?" Il nostro cervello è fatto per immagazinare dati, e ogni meccanismo per immagazinare i dati, si passa tramite un linguaggio. Per certi tratti, il format che il nostro cervello usa sono le immagini. Il nostro cervello crea mappe per le disposizioni degli oggetti. L'immaginazione ha una ricca funzione biologica. L'immaginazione nella prospettiva del naturalista (uomo come tutti gli altri animali) non spiega perchè l'immaginazione è stata premiata così tanto nella nostra evoluzione. Tomasello sostiene che se paragoniamo la vita dell'uomo a quella degli altri primati, non troviamo le differenze che spereremmo di trovare. Infatti ci sono tantissime somiglianze, e molte caratteristiche umane sono anticipate da altri animali. L'uomo però è in grado di insegnare e di apprendere un linguaggio, la matematica, la civiltà. Parlare di apprendimento vuol dire spostarsi da un terreno biologico a uno culturale, però ci deve essere qualcosa che permetta all'uomo di socializzare in questo modo. Il bambino che viene posto davanti a un presentatore che espone male l'uso di uno strumento, userà lo strumento in modo goffo, perchè ripete i movimenti. Mentre la scimmia manipola l'oggetto e cerca un metodo per usarlo. Il bambino vede la volontà atta ad arrivare a un fine, mentre la scimmia no. L'uomo sa vedere le intenzioni dell'altro perchè ha uno strumento biologico in più, rispetto agli altri animali. L'umano è più capace di comprendere l'altro, in quanto altro. Questo permette l'accumulazione del sapere. Posso capire l'altro perchè posso immaginare me al suo posto (posso mettermi nei suoi panni).</p>
<p>Accanto a questa capacità sembra affiancarsi un'altra capacità. I bambini che giocano, così come gli animali sono molto seri. I bambini, però, possono sperimentare mentalmente molte esperienze. Il bambino impara giocando a saggiare le proprie emozioni <i>off-line</i>, rispetto alla realtà.</p>
<p>Un approccio di stampo naturalistico è senz'altro legittimo, ma noi cerchiamo il significato dell'immaginazione. La base biologica non esaurisce i significati della parola immaginazione.</p>
<p>Gli antenati, 2 milioni di anni fa, avevano un'arco plantare atto alla camminata. Questo, però, non spiega i significati della parola camminare, così come non ci da le differenze di sfumatura tra il camminare e il passeggiare.</p>
<p>L'atteggiamento naturalistico ha la caratteristica di permetterci di guardare all'insieme degli elementi che costituiscono la nostra esistenza "dall'alto", in <i>terza persona</i>. Non c'è ragione di pensare che la linea evolutiva umana sia migliore delle altre (esempio: formiche). Un'altro sguardo che possiamo usare, e che ci mostra che noi siamo quello che siamo, dall'interno. <i>Siamo seduti su una sedia che non si possa spostare</i>. I nostri giochi linguistici, come la nostra vita, stanno lì. Non possiamo scendere per guardarla da fuori. Dal fatto che la nostra vita sta qui, capiamo che la nostra vita potrebbe non esserci. Noi dobbiamo calarci in questa prospettiva, interrogandoci sull'immaginazione, come una possibilità che appartiene al nostro linguaggio concettuale.</p>
<p>* Sensatezza = possibilità di parlare di quello che non c'è, raccontare favole = possibilità di senso = il mondo è fatto così e così, basandosi su quello che vediamo. Non possiamo fare nessun discorso che prescinda dal nostro linguaggio. Neurath raccontava un'immagine tipo: noi siamo marinai di una nave gettata nel mare, in balia delle intemperie, e dobbiamo riparare la nostra nave senza poter scendere.</p>
<p>Se l'immaginazione qualcosa di cui abbiamo esperienza, se è parte dei nostri giochi linguistici, come possiamo fare a capire cos'è l'immaginazione senza saggiare i modi in cui la parola è parte del nostro linguaggio. Immaginazione nel senso capacità di visualizzare un oggetto. Immaginazione nel senso di un progetto. Immaginazione nel senso del passato come una possibile differenza dal passato. Immaginazione di compiere un'attività. Immaginare un oggetto concreto come un oggetto astratto. Basta elencare i modi dell'immaginazione per capire l'immaginazione? no. Perchè? Perchè non siamo sicuri se c'è un'unico senso dietro a tutti i significati della parola immaginazione. Le nostre parole sono come una corda, sono arrotolate su se stesse e sono diversi usi che si arrotolano l'una sulle altre, e tengono per attrito. Non c'è sotto la nozione di immaginazione un'unico momento concettuale. Dobbiamo districarle per vedere se dietro al nostro uso della parola, c'è una sola nozione o molte. La parola immaginazione è un termine equivoco, cioè significa molte cose diverse, simili a catena. Se A somiglia a B, B a C, C a D, ... A non è detto che somigli a Z. Perchè la parola "immaginazione" è una sola, nonostante abbia multipli significati?.</p>
<p>Se ci capiamo, quando parliamo di immaginazione, vuol dire che padroneggiamo bene i significati. (Husserl: "La filosofia è la scienza delle ovvietà). Prima smontiamo il concetto e poi lo ricostruiamo, sapendo come e dove si intersecano gli oggetti.</p>
<p>La forma più ovvia di immaginazione: qualcuno pronuncia il nome di una persona che conosciamo, e noi ci immaginiamo il volto. Un'analisi introspettiva ci offre: "è come se vedessi quel volto" allude una vicinanza con la dimensione visiva (o acustica, per la musica). Le immagini mentali sembrano essere sfuocate e fragili (una temporalità tutta loro), se non stiamo attenti, spariscono. Non sembra essere in nostro possesso la facoltà di tenerle. Le immagini mentali sono "trebule" e sono caratterizzate dal fatto che se ci poniamo un quesito sull'immagine stessa, non è detto che questa ci possa rispondere. Il quadro qualcosa rappresenta e qualcosa tace, ha una soglia di informatività. Le immagini mentali sono anche loro così, però possono tacere grossi particolari (esempio, i colori). Le immagini mentali non tollerano il passaggio alla fase di osservazione. Posso visualizzare qualcosa se e solo se l'ho notato, se e solo se la conosco, se e solo se la ricordo. Quando mi immagino una persona, sto avendo un ricordo o un'immaginazione. Lasciamo da parte sulla specificità dell'immagine, e consideriamo il contesto in cui questa viene usata. Se si risponde alla domanda "come era quel volto?" stiamo disponendo un'immagine mentale sul terreno della memoria. <b>Un ricordo è un'immagine con un "Quando?"</b> e risponde fissando il luogo in una mia esperienza passata.</p>
<p>Se si visualizza un'immagine, la parola "ricordo" è sostituibile con la parola "so". In questo caso risponde alla domanda "che cosa?". Quindi questa è un'immagine. In alcuni casi il sapere è svincolato dalla data di acquisizione (19>18) in altre è vincolate (in 1a elementare ho imparato la data di nascita della Repubblica Italiana). Una stessa immagine mentale può essere ora un ricordo ora un sapere, in ragione all'appartenere a un contesto linguistico o un'altro. Il ricordo risponde a "quando?", mentre il sapere a "che cosa?". Un'immagine acquista il senso, sulla base del contesto.</p>
<p>"Stiamo montando una mensola di una libreria, e qualcuno ci fa immaginare a cosa succederebbe se il tassello non tenesse". Immagina in questo caso vuol dire: formula un'ipotesi. La libreria terrà o cadrà? Questa forma è molto usata in geometria (sia immagini una retta...). In questo caso possiamo dire: "si pensi che". Le due forme sono esattamente uguali? No, perché in questi casi non sempre può essere gestita come un'ipotesi, ma come una "scenetta" (immagina che ti si chiuda la scala sotto). Qui ci troviamo davanti al problema che ci sono concetti diversi, non sostituibili da un'unica parola</p>
<p>* frasi molto dubbie</p>

<?php t("6", "25/02/2011"); ?>
<p>Wittgenstein: dopo che finiamo i numeri N, passiamo ad usare i numeri R. Questo fa cambiare la nostra definizione di numero? Siamo ancora sul paragone della corda. Usando la parola 'immaginazione', cosa intendiamo? Paragone di Fune, e di rete, che usiamo per catturare una certa molteplicità di fenomeni. La parola immaginazione non è l'unica, e a volte si sovrappone con altre. Cosa vuol dire quando avviamo una sovrapposizione? Cosa vuol dire quando possiamo sovrapporre le parole immaginazione e pensiero?</p>
<p>La sovrapposizione deve essere presa molto sul serio. Secondo Yum è il modo per capire i significati della parola. Ci sono immagini memorative (ricordo) e immaginative. Se seguiamo Yum, perdiamo molte parti del ricordo. Il ricordo ha una sua grammatica che ne definisce il senso. Dato un ricordo possiamo sempre collegarlo ad altre esperienze, al momento in cui è successo. Cappuccetto Rosso non ha un posto nella storia perché non ha un quando. È opportuno procedere con un procedimento più metodico.</p>
<p>Il ricordo ha una caratteristica peculiare rispetto alla percezione: non da gli oggetti in modo immediato. Il ricordo rende presente una percezione passata, mentre una percezione rende presente l'oggetto.</p>
<table width="100%" border="1">
<tr>
<td>Atti che danno l'oggetto in se stesso</td>
<td colspan="2">Atti presentificanti</td>
<td colspan="2">Atti del possibile</td>
<td colspan="2">Finzioni</td>
</tr>
<tr>
<td>Percezione</td>
<td>Raffigurazioni temporali</td>
<td>Raffigurazioni atemporali</td>
<td>Ipotesi controfattuali</td>
<td>Possibilità aperte</td>
<td>Narrazioni</td>
<td>Funzioni ludiche</td>
</tr>
<tr>
<td>Vere o falss</td>
<td colspan="2">Vero o false</td>
<td colspan="2">Possibilità radicate in un contesto di mondo</td>
<td colspan="2">Acontestuali</td>
</tr>
<tr>
<td>Verifiicazione Interna</td>
<td colspan="2">Verificazione Esterna</td>
<td colspan="2">-</td>
<td colspan="2">-</td>
</tr>
</table>
<p>Gli atti di presentificazione sono immagini di cose senza tempo.</p>
<p>Nel rimorso, qualcosa che (non) abbiamo fatto ci infastidisce, e pensiamo cosa sarebbe potuto succedere se avessimo fatto cose diverse. Sono ipotesi ne vere ne false, ma sono cose che sono 'astrattamente possibili'. Questa possibilità inerisce a variazioni possibili di questo nostro mondo. Possibilità aperta: un oggetto ha un colore, questo colore <i>potrebbe</i> essere il rosso.</p>
<p>Alcuni fatti devono essere immaginativi (giochi, narrazione). La narrazione non propone qualcosa che non c'è più o qualcosa che ci sarà. Propone però una cosa che non ha un rapporto con questo nostro mondo. Il bambino non pretende di modificare il mondo. Appena il gioco termina, tutti gli oggetti riprendono la loro funzione. Non ha senso chiedersi se Pinocchio esiste o meno. Il racconto, in linea di principio esclude ogni possibile verificazione.</p>
<p>Ci avviciniamo all'immaginazione tanto più ci allontaniamo dall'antitesi <i>Vero/Falso</i>.</p>
<p>Quando parliamo di immaginazione, la nostra rete si sovrappone con i nodi del pensiero. Sui libri di geometria: "Si immagini un triangolo...". "Immagina cosa accadesse se...". L'immaginazione sembra una versione poco più colorata del fare assunzioni. Fare assunzioni non vuol dire credere davvero qualcosa. Le assunzioni hanno una concreta vicinanza con le immaginazioni, grazie a questa distanza dal vero e falso. L'immaginazione e il pensiero sono la stessa cosa? No, ma il perché è complesso.</p>
<p>Cartesio: "come faccio a rendere conto della differenza tra immaginare e pensare?" Quando immagino  una figura, aggiungo qualcosa al pensiero. Accanto al pensiero dell'oggetto geometrico,   creo un'immagine di esso. <b>L'immaginazione è un pensiero illustrato</b>. Immaginare vuol dire pensare con uno sfondo ...</p>
<p>Quando leggiamo un racconto non ci si crea una scena immediatamente. Capiamo senza visualizzare, immaginiamo senza immagini. Non è necessario che ci siano immagini per immaginare. Forse non è neanche sufficiente. [Risoluzioni di Euclide e Schopenhauer del teorema di Pitagora].</p>
<p>[Ernest Mach, Innenperspektive], Mach raffigura lo spazio visivo come una visione 'oculare'. Le visualizzazioni hanno l'aspetto di quasi percezioni, cioè sono situate, ego-dirette. Ego-dirette: prendendo una qualunque visualizzazione, come il cortile, lo visualizziamo in modo orientata verso l'io visualizzante. Abbiamo una sorta di sdoppiamento dell'io, c'è una parte tutta interna all'atto di visualizzazione che orienta la visualizzazione sulla base dell'io 'normale'. Una mappa non contiene un luogo di visualizzazione, mentre un quadro si. Il puntino rosso "voi siete qui" da un indicazione per permetterti di far combaciare con il mondo per usarla per capire il mondo. Le mappe non sono ego-dirette. L'immaginazione è "calda", il pensiero è "freddo". La prima coinvolge, la seconda no. Non esiste un termometro intellettuale.</p>
<p>La prospettiva è stata inventata per far diventare il quadro la visualizzazione di chi guarda il quadro.</p>
<table width="100%" border="1">
<tr>
<td colspan="4">Forme dell'Immaginazione (forme calde, ego-dirette)</td>
</tr>
<tr>
<td>Visualizzazioni</td>
<td>Finzioni del possibile</td>
<td>Far come se ludico</td>
<td>Finzioni narrative</td>
</tr>
<tr>
<td>Descrizioni</td>
<td>Supposizioni</td>
<td>È vero nel gioco che ...</td>
<td>È vero nell'universo del racconto che...</td>
</tr>
<tr>
<td colspan="4">Forme Obbiettive (forme fredde)</td>
</tr>
<tr>
<td colspan="2">Percezione</td>
<td colspan="2">Percezione?</td>
</tr>
</table>
<p>Il coinvolgimento è quello stesso tipo di relazione che proviamo quando abbiamo delle esperienze. Siamo situati in quella situazione/contesto. Un bambino che gioca si trova dentro al gioco. È anche situato al di fuori, il suo giocare avviene dentro ad uno spazio ludico. "Ora" ha un senso se e solo se è fissato un contesto. Quello che dovremmo sostenere è che la caratteristica che ci consente di dividere il pensiero dall'immaginazione è che l'immaginazione è ego-diretta, il pensiero è obbiettivo. Nel senso che ci propone descrizioni che non sono caratterizzate come mie esperienze. Possiamo enunciare stati di cose in modo obbiettivo, senza avere quasi esperienze del loro contenuto.</p>
<p>La percezione è la forma ovvia di coinvolgimento. Non ci è dubbio sull'esistenza di questa relazione. Quali sono le strutture che l'immaginazione e la percezione condividono? Entrambe hanno un punto di visione. L'immaginazione è un 'eco' della percezione. La descrizione dipende dalla percezione, ma non dipende dalla sua struttura. La descrizione traduce con un linguaggio nuovo la percezione. Molti giochi hanno la funzione di vedere una situazione, senza pensarci.</p>
<p>Evidentemente come facciamo a vedere qual'è il rapporto con la percezione, in quelle situazioni in cui la percezione è messa da parte (gioco). In realtà la dipendenza dell'immaginazione dalla percezione esiste, anche se a livello più basso. Nel gioco plasmiamo la realtà in un modo nuovo.</p>
<p>Lo stesso discorso è anche attuabile sui testi. L'Odissea ne è un esempio. Essa è una riflessione generale sull'idea del tempo. Il tempo lineare (Ulisse che vuole tornare). L'acqua: il tempo della dimenticanza, L'isola è il tempo lineare, il tempo del ricordo. Eolo dovrebbe appartenere alla terra, ma dovrebbe anche appartenere all'acqua. Infatti Eolo sta su un'isola galleggiante perché è entrambe le cose.</p>
<p>"Sul ponte di cullava la rugiada dalla testa di gatta" (Breton). L'esperienza immaginativa è una quasi esperienza ed è un lavoro immaginativo con le cose</p>

<?php t("7", "02/03/2011"); ?>
<p>Determinare il luogo dell'immaginazione nel vocabolario complessivo della nostra esperienza. Non possiamo limitarci a soppesare le parole e limitarci ai significati primari. Atti che rendono presenti gli oggetti con o senza darci un diretto accesso a essi. Non sono in grado di darci l'oggetto ma sono tutti passibili di una verificazione o confutazione. Un ricordo può essere vero o falso.</p>
<p>Mi immagino il volto di una persona amica, accanto a queste forme in cui vale la verificabilità o confutazione. In alcuni casi questo non è possibile, ad esempio nei casi in cui immagino come possibilità (se della storia). In questi casi queste cose non sono ne vere ne false. Sembra legittimo parlare di immaginazione anche nel caso della finzione immaginativa (ludica, ad es), perchè si sa che terminato il gioco le cose ritornano alla loro realtà. Gli atti immaginativi possiamo anche chiamarli come atti posizionali.</p>
<p>In questo modo di organizzare gli atti, sembra essere possibile una prima delimitazione del concetto di immaginazione? Mettere nel caso degli atti presentativi tal volta usiamo la parola immaginazione, ma possiamo sostituire questa parola con molte altre. Nel caso di atti non posizionali fare a meno della parola immaginazione è molto difficile.</p>
<p>Talvolta usiamo la parola immaginazione in modo molto simile alla parola pensiero. Che differenza c'è tra immaginare e pensare? Il pensiero sembra essere una forma più fredda dell'immaginare. Swift propone di mangiare i bambini per risolvere il problema della fame e della sorappopolazione. Questo potrebbe essere difficile da immaginare, ma molto semplice da assumere.</p>
<p>Un gioco può essere partecipato, un'ipotesi no.</p>
<p>Che differenza c'è tra la visualizzazione del cortile e una mappa del cortile? Quando lo visualizzo io mi rappresento questo cortile e me lo rappresento rispetto a un luogo in cui mi colloco. Nel caso delle mappe, non abbiamo qualcosa del genere. Il 'voi siete qui' serve ad individueare qual'è il posto che sulla mappa che rappresenta il nostro attuale posto. Questo è necessario per riproiettare la mappa sul mondo reale e viceversa. Qui accade una scissione dell'io pechè nel tessuto dell'immaginazione vi è un punto di riferimento che rappresenta all'io che appartiene al contesto dell'immaginazione. Quando ricordo qualcosa, ricordo qualcosa del passato, ma esso ha la triade temporale che non è riferita rispetto al punto della presenza, ma rispetto al luogo stesso: l'io temporale del ricordo. Quella differenza che abbiamo provato ad individuare nel caso della distione tra presente e passato, è una distinzione che possiamo articolare come : "non è una questione di caldo o freddo, ma di esperienze calde (esperienze, quasi-esperienze) o fredde (pensieri). Nel caso delle forme dell'immaginazione esse appatengono ad una forma di scissione tra l'io osservante e un'io immaginato all'interno dell'immaginazione stessa. C'è un io immaginato nell'immaginazione."</p>
<p>Quando qualcuno dice immagina, devo costruire una quasi-esperienza che presuppone un mondo in cui ci sono credenze, desideri,  paure e pone l'operatore modificatore al di fuori del mondo a cui l'atto creativo. L'immaginazione sembra costruire un mondo, dispiegarlo, e porre un 'soltanto' poichè non ha pretesa reale</p>

<?php t("9", "04/03/2011"); ?>
<p>Frome calde, forme fredde. Forme mediate, immediate. Forme posizionali, non posizionali. L'immaginazione occupa un piano dell'esperienza. L'immaginazione è una forma calda, non posizionale, e immediata. Ricordo: mediata, calda.</p>
<p>La filosofia non significa solo mettere in ordine in cassetti. Quali sono i cassetti dell'immaginazione?</p>
<ul>
<li>Fantasticherie
<li>Immaginazione tecnologica
<p>Immagina quello che non c'è, per poi modificare il reale</p>
<li>Gioco
<li>Finzione letteraria
<li>Figuratività
</ul>
<p>Il primo modo di ordinarle: l'immaginazione da dove sorge? Dalla vita. Fa parte della nostra vita. È un momento della nostra esstenza, del nostro stare in questo mondo. Quale passo d'immaginazione compie rispetto a questo nostro mondo.</p>
<ul>
<li>Spinge l'immaginazione a proporre alternative rispetto alla realtà
<p>Molto utile per comprendere la realtà stessa. Immaginazionee è la capacità di porre il reale sullo sfondo di un possibile. Cosa c'è alla base di una scelta? Cosa vuol dire comprendere un divieto? Immaginare l'altro. Disporre la nostra esperienza da ciò che è asserito dalla regola, e l'opposto. Il rimorso è un'esempio. La realtà viene messa su uno sfondo mobile.</p>
<p>La finzione del possibile è fortemente intrisa del mondo. Pensiamo la possibilità come possibilità di questo mondo. È una possibile alternativa a questo mondo, in questo mondo. Immaginamo realtà contestualizzate nel mondo.</p>
<ul>
<li>Immaginazione centestuale
<ul>
<li>Immaginazione tecnologica
<li>Modificazioni del reale
</ul>
<p>Immaginazione con vincoli</p>
<li>Immaginazione assoluta
<p>Immaginazione senza vincoli</p>
<ul>
<li>Figuratività
<li>Finzione ludica
<p>Immaginazione fantastica non può avere la possibilità, o la può avere ma non posto come un possibile, ma come uno scenario che i sovrappone alla nostra realtà, senza negarla.</p>
</ul>
</ul>
<li>Immaginazione centestuale
<ul>
<li>
<ul>
<li>
<li>
</ul>
<li>Immaginazione assoluta
<ul>
<li>Fantasticheria
<p>È una fantasia ad occhi aperti. È qualcosa che non si confonde con la realtà. Anche se il sogno fosse davvero la risposta ai nostrivoleri. I sogni accadono. Il corso degli eventi del sogno è in terza persona. Le fantasticherie hanno un forte nesso con la dimensione della soggettività. Il contenuto della fantasticheria paarla in nome di qualche nesso con la soggettività come unità di bisogni, paure. Riconosciamo la nostra natura, nelle fantasticheria. Hugo suggerisce uno svegliarsi dell'io nella fantisticheria, non nell'addormentarsi. Le fantasticherie sono spesse connesse con il desiderio. Sicuramente le fantasticherie non soddisfano il desiderio. L'immaginazione è un mezzo, non un fine. Nella fantasticheria è una manifestazoni di desideri appagati. Nella fantasticheria creiamo un reale alternativo.</p>
<p>Il tempo è un 'termometro' dell'immaginazione. Il tempo è la struttura dell'ordinamento del mondo. L'immaginazione ha una sua temporalità. Il desiderio è riivolto al futuro (ora desidero per domani). La dimensione della fantasticheria è presente, ma un adesso che non è l'ora reale, ma ha un rapporto temporlae solo con il tempo dell'immaginazione. La fantasticheria propone un'orizzonte altro rispetto a qeullo del reale, ed è costituito per opposizione a quello reale. L'utopia è qualcosa che è non-luogo e buon-luogo. (vedi Charlie Chapline - Modern Time, ~50'). Anche se le fantasticherie occupano una quantità di tempo rilevante nella fantasia di tuttii giorni, resta vero per essenza che è la fantasticheria che spunta dalla realtà, non l'incontrario.</p>
<p>Il ritratto ha sempre un collegamento con il mondo. Il ritratto è un eco della persona. Il ritratto può diventare una mappa (ci, patente,...) per riconoscere quacuno. Se parla del mondo, il ritratto può essere vero o falso (buono o cattivo). È cattivo quando non ci permette di riconoscere una persona. I ritratti sono sempre, davvero, questo? Abbiamo rinunciato ad intendere l'immagine pittorica come copia della realtà, ma come oggetto <i>in sè</i>.</p>
<li>Finzioni narrative
<p>Ha na consistenza più ricca delle fantasticherie. Cos'è un racconto? Un racconto è una narrazione assoluta (libera). Le parole possono descrivere eventi 'vero simili'. Una narrazione così ci obbliga a usare le parole 'a vuoto', perchè possono sganciarsi da un riferimento immediato ma possono manterene nel loro significato una serie di sensi che permettono di ricollegarle con un'insieme di eventi e una teorica verificazione. Il racconto letterario ha sciolto la sensatezza di una verificazione possibile. Questo perchè ci poniamo in una complessa opera di decontestalizzazione. Raccontando un fatto possiamo dare una collocazione spazio/temporale, mentre per una finzione questo non vale. Questo è anche vero se ci sono racconti che sembrano ambientati in un posto e in un tempo determinate, perchè non è ne parte del <u>nostro</u> passato ne del <u>nostro</u> futuro. In questi casi il tempo o lo spazio sono 'aggettivi'. Questo è anche vero per i personaggi di un libro. Non sono oggetti, ma ruoli. Gli oggetti sono al di là della descrizione che diamo e dell'esperienza che abbiamo. I personaggi di un racconto si esauriscono nella narrazione che se ne fa. I racconti contengono completamente l'oggetto della loro narrazione che esiste solo all'interno della narrazione stessa. Le narrazioni letterare sono assolute, una narrazione 'senza fuori'.</p>
</ul>
</ul>
</ul>

<?php t("10","09/03/2011"); ?>
<p>Chiediamoci il luogo dell'immaginazione. Quando si dice immaginazione si intende sempre la stessa cosa? No, anche se accettiamo di porre sotto la categoria dell'immaginazione solo quelle definizioni assegnate dal precedente schema.</p>
<p>La fantasticheria ci mostra come il mondo non soddisfa interamente i nostri desiderri (ci manca molto). Nonvi è dubbio che le fantasticherie prendano le origini dal mondo. I racconti ci dicono molte cose che ci permettono di sapere sul mondo. Calvino dice: le città di cui MArco parla, non esistono, ma tutte le immaginazioni parlano del mondo, o meglio <b>dal</b> mondo. Tutte le fantasticherie rispondono ai problemi della nsotra vita, ma non ce le propongono come possibili contenuti reali, neanche come mere possibilità, ma come una recita di una finzione. Non un progetto, ma un utopia.</p>
<p>Immaginare un ippogriffo è semplice perchèè un'oggetto fantastico. Ci sono immaginazioni più complesse (come le fantasticherie). Le fantasticherie parlano di noi e appartengono alla trama delle nostre motivazioni. Rispondono a qualche istanza pronda. L'immaginazione ci pone una domanda: perchè immaginiamo? I racconti (le favole, le commedie) sono immaginazioni per cui ha senso chiedersi il motivo. Le immaginazioni narrative sono rivolte da qualcuno a qualcuno, mentre la fantasticheria no.</p>
<p>Le narrazioni, possiamo davvero porle nell'immaginazione caratterizzata da un'eco di questo mondo? Che differenza c'è tra il narrare finzionale e la narrazione di un evento accaduto (vero o falso che sia).</p>
<p>Noi sappiamo parlare dando alle parole un certo significato anche se il contesto delle parole è lontano (sappiamo parlare di quello che non c'è), mentre un animale no.</p>
<p>Il linguaggio può agire come freccia per riferirsi a qualcosa di presente. Quando qualcuno si ricorda, il mondo è costruito dalle sue parole, ma in realtà è presente prima delle parole stesse. Il parlante, contemporaneamente, crea il mondo tramite le parole, e ricordando il ricordo. Per chi ascolta, il mondo si costruisce tramite le parole del narratore, il quale ricostruisce il mondo tramite le sue parole.</p>
<p>La narrazione è correlata con una realtà che fa da modello. Anche se non sappiamo dire se un racconto è vero o falso, il racconto - in se - è vero o falso.</p>
<p>I racconti che leggiamo, i romanzi che leggiamo, i quadri che leggiamo diventano narrazioni assolute. Nel momento in cui ascoltiamo una favola, ascoltiamo un mondo che prende forma, passo dopo passo, tramite le parole. Quel mondo si da completamente in quella forma. (io sono alto 'così', il metro campione). Non si possono verificare, perchè stiamo usando il racconto per verificare se stesso (sistema auto-referenziale). Possiamo solo verificare la nostra memoria di quel racconto, verificando la fonte primaria, ma non possiaamo verificare la veridicità del racconto. Nessun racconto è vero e nessuno è falso. Ogni racconto è ciò che racconta.</p>
<p>Un racconto è verificabile controllando la situazione in quel dato momento, in quel dato posto. Una finzione non è ne vera ne falsa, perchè non è ancorabile a un tempo e a un luogo. Se il racconto è delimitato temporalmente, </p>
<p>Proviamo a dare un tempo obbiettivo ai nostri ricordi perchè la domanda "questo è successo prima o dopo di [...]" ha sempre senso, mentre per le narrazioni letterarie non ha senso. Lo stesso discorso è spostabile sullo spazio. La fantasia è acontestuale. È anche possibile che le narrazioni letterarie si intreccino con la Storia (o per date, o per luoghi, o per entrambi). Siamo davvero così sicuri se quando parliamo di una data o di un posto all'interno di un racconto le usiamo come se stessimo usando le parole di tutti i giorni?</p>

<?php t("11","16/03/2011"); ?>
<p>Che cosa accade quando raaccontiamo qualcosa? Ha senso parlare di una storia lacunosa? Dare una risposta alla domanda 'manca qualcosa?' sembra un'invito a una nuova fantasia coerente. Ma questo non vuol dire mostrare che il racconto in uqel punto sia lacunoso. I racconti non hanno lacune perchè non hanno un metro per misurare le eventuali lacune.</p>
<p>Quando leggiamo unracconto dobbiamo fare una serie di assunzioni. Un racconto è una narrazione con o senza lacune? Facciamo inferenze? Da dove li prendiamo?</p>
<p>Un racconto è privo di lacune, dice quello chee dice, tace quello che tace che semplicemente non c'è. All'interno di una narrazioni ci sono delle domande che non facciamo, ma ci sono anche delle incongruenze fattuali e logiche. (i vari lupi che inghiottiscono capretti/bambini).</p>
<p>I racconti sono davvero una costruzione che si muove esclusivamente sul piano noematico. Cioè all'interno del racconto le cose sono presenti solo come oggetti in quanto descritti dalla narrazione. Ci muoviamo su un piano intensionale non estensionale. Venere è la prima stella della sera e l'ultima stella della mattina. Sono la stessa cosa su un piano estensionale ma non in quella intensionale. Questo abbraccia anche gli atteggiamenti emotivi (nessuno fraternizza con i vari lupi).</p>
<p>Un racconto è un corpus di credenze. Come esso, tutti abbiamo immagini parziali sia del mondo sia del racconto. Un corpus di credenze non abbraccia tutte le conoscenze e non rende possibili tutte le possibili inferenze. Sono sistemi relativamente coerenti di credenze. Relativamente coerenti perchè a volte abbiamo delle incongruenze più o meno forti e determinanti. Leggere un racconto vuol dire cercare di indovinare il sistema di credenze del narratore. Tutti i racconti sono basati su un corpus di inferenze che fa da sfondo.</p>
<p>Un racconto non può essere integrato con tutte le proposizioni vere. I sistemi di credenze sono opachi e possono avere contradizioni perchè una contradizione intesionale potrebbe non essere palese nel sistema estensionale. Cerchiamo di comprendere le credenze e le integriamo su uno sfondo probabile/possibile. Nessuna testimonianza dice tutto quello che serve per essere compresa. Perchè un racconto non è un sistema di credenze? Cos'è un sistema di credenze? Può essere fatto proprio da qualcuno anche se queste si possono rivelare false (o nel passato o nel futuro), inoltre sono qualcosa che è connessa in vario modo al mondo. Sono impegnato ad impegnarmi in maniera tale da far meritare alla cedenza lo status di credenza. Le credenze sono sensibili rispetto al mondo. Non vincolarsi a credere solo cose vere, ma essere flessibili a cambiare le credenze che si mostrano false. Un sistema di credenze deve crescere su un sistema di certezze. Io posso dubitare di molte cose, ma non di tutto. Non si può dubitare l'esistenza di un tempo passato, perchè questo saarebbe come tagliare il ramo su cui siamo. Non posso dubitare di sognare, se non do un significato alla parola sogno. Il dbbio avviene all'interno di un sistema di certezze. Qualcosa è una credenza se si può dire una credenza, cioè possiamo dubitare ma non abbiamo ragione di dubitarla. La credenza è ragionevole. Il dubbio è formulabile all'interno di un sistema di certezze. Il sistema di certezze è tutto quello che è del mondo ma non è mai messo in discussione dal mondo stesso.</p>
<p>È vero anche in un racconto? Noi consideriamo vere tutte le proposizioni del racconto sommate a tutte quelle del mondo che sono verosimili per il racconto. Le credenze che vanno fatte valere sono basate sulle certezze che sono alla base di tutti i sistemi di credenze. Non abbiamo a che fare con una pretesa di ricostruire un sistema di credenze. Quando noi ci chiediamo qualcosa su un racconto, noi non facciamo altro a guardare nel racconto cosa dobbiamo pensare per attribuire al racconto la massima pienezza di senso. Fare tutte e solo le inferenze che sono richieste dal racconto stesso.</p>
<p>L'inferenza è motivata esclusivamente da un oggetto nel testo. Legittimiamo il progetto narrativo sulla base del racconto stesso.</p>
<p>Che differenza c'è tra fantasticheria e i racconti? Le fantasticcherie non sono in nessun caso parte di un progetto comunicativo. Le fantasticherie non si fanno, accadono. I sogni non si fanno, accadono. I racconti si fanno. Le fantasticherie e i sogni non sono quindi fatti per uno scopo, ma si possono usare come tali. Mentre il racconto ha uno scopo comunicativo. Una cosa può avere una morale anche senza avere uno scopo. Non si è responsabili dei sogni, ma si sogna dentro di noi.</p>
<p>Chi è il soggetto che narra? L'autore reale non è la persona di cui stiamo immaginando il progetto immaginativo, perchè lo posso attribuire soltanto muovendomi dalla storia. Il narratore è qualcosa che possiamo costruire dalla sotira stessa. Il narratore è la voce della storia. Il narratore implicito si costruisce dal testo ed è tutto quello che serve a far intendere il testo, come se il testo dovesser essere raccontato dal un narratore implicito a uno spettatore implicito. Costruiamo a partire dal testo lo scenario mentale di chi ci narra quella storia, che è legittimato dal fatto che chi narra vuole farci pensare qualcosa. L'autore implicito è qualcuno che esce dal testo e che ci racconta una storia per far pensare all'ascoltare determinate cose</p>

<?php t("12","18/03/2011"); ?>
<p>Capire un racconto = considerare vere le proposizioni del racconto. Ci sono delle proposizioni che dobbiamo considerare vere per dare un senso a quello che leggiamo. Principio di realt: se le proposizioni a,b,c,e sono vere allora anche d è vera se nel nostro mondo le proposizioni a,b,c,d,e si accompagnano. Il nostro mondo ci permette di collocare il racconto nella rete delle conoscienze.</p>
<p>Cercare di dare basi fisiche ai racconti è sbagliato. È sbagliato cercare Troia, Circe etc, così come dobbiamo astrarci dalla nostra realtà per leggere Harry Potter</p>
<p>Principio di credenza condivisa: Se a,b,c,e sono vere, allora anche d è vero se e solo se d si accompagna alle altre proposizioni nel mondo come se lo immagina l'autore (in carne ed ossa). Ad esempio la cosmologia che Dante afferma nella <i>Divina Commedia</i>. Ogni storia abbraccia la totalità delle credenze dell'autore? No, i racconti accettano solo ed unicamente quei fatti che sono rilevanti, mentre la realtà abbraccia sempre qualsiasi cosa. Le storie sono tali perchè possiamo domandarci il perchè qualcosa c'è. Non possiamo quindi pensare che a integrare la storia sia la totalità dei fatti.</p>
<p>La proposizione non cade com'è, ma è fatta per comunicare, quindi può e deve avere un senso. Posso interpretare i gesti delle persone perché si condivide lo stesso mondo. Se non convidessimo il mondo non potremmo capirci. Non sembra essere vero che per capire una storia ci debba essere una concordanza con le idee di fondo. Le proposizioni di una storia, non sono un sistema di certezze.</p>
<p>I presupposti sono deliminati "all'estero" da certezze che mai vengono messi in discussione. Posso dubitare un discoso se capisco quello che viene detto e se il discorso parla di qualcosa di verificabile o falsificabile. Non possiamo fare a meno di muoverci all'interno di un sistema di credenze.</p>
<p>Una narrazione può essere intesa ccome una storia o come la prassi del narrare. Narrare vuol dire comunicare, proporre qualche contenuto (Storia) a qualcun altro. In ogni storia c'è un atto del narrare. Ogni storia ha un processo comunicativo, a differenza di una fantasticheria. Le fantasticherie accadono, non le costruiamo per narrarle. Ha sempre senso chiedersi come debbo fare a capire ciò che mi si narra per capirne il senso. Il racconto necessita dello sforzo dell'ascoltatore. Creiamo assieme alla comprensione del racconto uno sfondo che renda questa comprensione possibile. Dobbiamo legare alle parole che ascoltiamo tutte le preposizioni che ci possono aiutare a capirlo. Il narratore implicito di un racconto è soltanto colui che possiamo immaginare raccontare quella storia, a partire dalla storia stessa. Le voci fuori campo sono dentro alla storia, non sono il narratore. La storia è un narratore implicito di se stessa.</p>
<p>Immaginare= mettere capoa a una modificazione coerente del nostro mondo. L'immaginazione muove da un modello. Un bambino che non ha mai visto una spada o una persona che tira di scherma, non può usare un bastone come se fosse spada. Ogni coerenza si basa su una regola. Il lettore implicito è un altro modo per intendere quel 'calore' della narrazione. Un racconto è una narrazione che un autore implicito fa ad ascoltatore immaginario. Tanto maggiore è lo scarto tra il lettore reale e quello immaginario tanto diverso è il genere letterario a cui ci si sta riferendo. "c'era una volta, in un posto lontano lontano" pone l'ascoltatore immaginario molto lontano da quello reale. Ogni evento che accade sembra legittimare la domanda 'perchè?' se si parla di una storia, mentre nella realtà no. Se ce lo chiediamo anche nel mondo, allora dobbiamo pretendere che il mondo sia un racconto, come vogliono molte religioni. Tutte le storie hanno una fine. Una storia è una cosa con un inizio e una fine perchè una storia ha un inizio e una fine assoluti.  Una storia nasce perchè deve finire, le persone non nascono per morire. Una storia deve poter essere ripensata a ritroso. Ogni evento narrato deve  condurre verso la fine della storia. Le storie si possono giustificare a ritroso. LE storie si possono ripetere perchè hanno un'inizio e una fine assoluti. Non sono eventi nel tempo ma sono forme. La storia è staccata dal decorso temporale, quindi può essere pensato partendo dalla sua fine. Questo non avviene nella realtà per il Principio di causa sufficiente, quindi la realtà è una 'concatenazione aperta' mentre unaa storia è una 'concatenazione chiusa' (tutto quello che ha luogo, deve aver senso in vista dell'evento finale. Questo è anche vero quando non sembra (v. Coscienza di Zeno).</p>

<?php t("15","25/03/2011"); ?>
<p>(Mercoledì 6 non c'è lezione)</p>
<p>Come passiamo da un prodotto immaginativo a un progetto immaginativo? Non è possibile integrare il contenuto immaginativo con un sottofondo di mondo semplicemente presupposto. Come facciamo a raccogliere dal testo quello che fa da sfondo al testo stesso?</p>
<p>Immaginiamo partendo dal mondo, costruendo aree di significato. Sarebbe sciocco pensare che il piano alto e basso dell'immaginazione sarebbero davvero separati. Costruire Mondo immaginiativo</p>
<p>Ogni nostra proiezione immaginativa sul mondo sembra trovarsi tra la forza dei materiali e il modo in cui noi soggetti reagiamo immaginativamente ad essi.</p>
<p>Il nostro modo di pecepire si avvale dei suoi risultati anche per le fantasie mentali. La nostra di percepire è anche causata dalla fomazione di immagini mentali che ci permette di avere più di quanto il nostro occhio vede. Vedere != Guardare. Vedere è un verbo di succsso. Ciò che vedo può essere in qualche minusra articolato nella procedura del guardare.</p>
<p>Possiamo vedere solo le cose di cui abbiamo almeno un'idea. Una storia possiamo immaginarla, le somiglianze si veodno.</p>
<p>Figuratività: noi vediamo un volto (per esempio) ma vediamo assieme anche che il volto è soltanto apparente. Fenomeno percettivo curioso: io vedo l'immagine come solo apparente.</p>
<p>È possibile fare un passo in direzione di un'assunzione seria della figuratività. Il passaggio dalla figuratività all'immaginazione figurativa è davvero breve.</p>
<p>Dobbiamo togliere completamente dalla pittura lo spazio del naturale e mettere.</p>
<p>Obliquo come approssimazione al verticale, approssimazione, come tra poco.</p>
<p>Ogni figuratività è un veicolo figurativo, è un passo che può essere compiuto verso l'immaginazione.</p>

<?php t("16","30/03/2011"); ?>
<p>(Mercoledì 6 non c'è lezione, ha messo il programma in rete, esame: dispensa + approfondimenti con i testi)</p>
<p>Come possiamo comprendere un testo immaginativo? (gioco, immaginazione a occhi aperti, una narrazione, una costruzion immaginativa, un quadro, una costruzione musicale) Quando l'immaginazione entra in gioco, il gioco si complica perchè dobbiamo sempre prendere in considerazione lo sfondo. Ci sono delle modificazioni coerenti che danno la possibilità di immaginare. La figuratività non presuppone l'immaginazione, perchè sono semplicemente cose esperite come rimandi ad altre. La rete della figuratività, l'infita serae di rimandi è la premessa dell'immaginosità. L'immaginazione prende posizione rispetto a essi. A differenza dei richhiami, nell'immaginazione non si parla di richiamare, ma di essere/diventare. Abbiamo delel attese predeterminate dagli. Prporre un valore immaginativo vuol dire aderire alla figuratività. Il gioco della figuratività orienta ma non determina l'immaginazione. L'ombra riccorda la presenza corporea. La figuratività solitamente è intramodale (stesso senso9 e non intermodale (differenti sensi). La figuratività viene presa sul serio e il soggetto aderisce al mondo dell'immagine. Ci capita di dare vita a figurazioni su figuraioni. Costruire l'immaginosità come atteggiamento nuovo. Si può anche essere portati da una serie di fatti.</p>
<?php file::footer(); ?>
