<?php
require "../class/include.php";

file::head("Storia della Filosofia Morale - Appunti");

toc::show_toc();
?>

<?php t("1", "14/02/2011"); ?>
<p>Appello 17/5  ore 9.30 + 2 a giungo + 1 a luglio + settembre + ottobre</p>
<p>Un argomento spiegato nel modo freudiano</p>
<p>Chi si dichiara frequentante anche le varie divagazioni e digressioni.</p>
<p>Il terzo libro (Il disagio della civiltà e altri saggi) per forza Bollati Boringhieri</p>
<p>"Al di la del principio del piacere", "Totem e Tabù", "l'uomo Mosè e la religione monoteistica"
Kultur = Civiltà nel senso ampio (usi, costumi, opere intellettuali, cultura, abitudini sessuali, abitudini matrimoniali)</p>
<p>Anche gli aborigeni australiani (la forma più elementare di civiltà che esiste attualmente) hanno una Kultur.
Le due particolarmenti importanti parti della Kulture sono la religione e la guerra.</p>
<p>Secondo Freud, l'unica forma di incivilimento del uomo sia quella religiosa. Non esistono e non sono mai esistite civiltà prive di religione.</p>
<p>Totem e Tabu prova a rispondere alla domanda: "Come è nata la religione?"</p>
<p>La  guerra sono state scritte dal '12 al '39. Freud vede una guerra e vede l'inizio di una seconda. Freud è ebreo e ha subito le persecuzioni antisemite.</p>
<p>La visione di Freud sulla civiltà è molto negativa, probabilmente anche perché Freud ha vissuto esperienze che lo provavano.</p>
<p>Questi scritti sono stati scritti dal '12, momento in cui lui aveva già creato la Psicanalisi e aveva 56 anni. Freud all'epoca aveva già scritto tutti i libri principali della Psicanalisi e aveva già fondato la società, i congressi, due riviste. Freud non ha ancora terminato la sua opera di teorico della psicanalisi infatti anche dopo il '12 continuerà a pubblicare altre opere prettamente di psicanalisi. Freud crede di avere gli strumenti per applicare la psicoanalisi alla società e alla morale. Freud pensa di avere in mano uno strumento simile alla Filosofia e alla Psicologia, ma alternativo. Totem e Tabù viene pubblicato in una rivista di Freud per l'applicazione della psicanalisi alle scienze psicosociali. C'è stato un rifiuto da parte di molti antropologi a considerare queste opere invalide. Freud non rispetta i metodi di indagine degli antropologi. Freud in "Psicologie delle masse e analisi dell'io" analizza la differenza tra la somma degli individui e la massa. Questa opera nonostante sia scritta molti anni fa, è ancora molto attuale. Una delle maggiori critiche contro Freud è il pansessualismo. Molti scritti di Freud risalgono a un'epoca in cui i costumi sessuali siano molto cambiati, ma nonostante questo, le intuizioni che Freud ha sono ancora molto importanti. Freud rimane al centro del movimento psicanalitico perché lui è il più estremista.</p>
<?php t2("1.1", "Totem e Tabù"); ?>
<p>Opera divisa in quattro saggi.</p>
<p>Totem e Tabù sono entrambe parole che derivano dal gergo dell'antropologia. Entrambe sono state prese da posti lontani. Totem: progenitore animale di un clan (stirpe). Questo concetto non esiste nella cultura occidentale (4). Il concetto di Tabù è il divieto assoluto. È l'imperativo morale o delle proibizioni assolute, il concetto negativo del sacro (innominabile). La nascita di questi due concetti possa essere spiegata dall'analisi della vita dei nevrotici. Freud si imbattuto in fenomeni psicologici molto simili in casi di nevrosi. "Forse che quello che nella vita di un nevrotico, appare come malattia, è un residuo di stati che un tempo siano stati propri dell'intera umanità?" "Che i selvaggi siano simili ai nostri avi?" Il nevrotico soffre di regressione allo stato infantile, che è lo stesso stato in cui si sono fermati i popoli selvaggi. Tutti siamo nevrotici, chi più chi meno. Sottotitolo: "Alcune concordanze tra la vita dei selvaggi e dei nevrotici". L'idea che ci siano dei popoli meno sviluppati di altri, è una nozione senza senso, oggi. Freud parla di civiltà selvagge e semi selvagge presentando un punto di vista molto euro-centrico, anche perchè in quel periodo questo  era normale, infatti assistiamo al colonialismo. Però Freud arriverà a superare, almeno teoricamente, questo preconcetto. Le sue conclusioni per la vita dei selvaggi, valgono anche per i popoli europei. Il disagio della civiltà afferma che la nostra civiltà occidentale è nevrotica. Non si può tracciare una linea evolutiva per dimostrare che noi siamo più evoluti di loro. Freud aveva il gusto della dissacrazione.</p>
<?php t3("1.1.1", "L'orrore dell'incesto"); ?>
<p>Freud ritiene di aver sviluppato una teoria incentrata sul Complesso di Edipo. La prima scelta dell'analisi sessuale del bambino è incestuosa. L'incesto, all'epoca non era spiegabile con altre teorie. Perchè un uomo dovrebbe proibire a se stesso il soddisfacimento sessuale con l'oggetto più a portata di mano (madre, figlia, sorella) e  che gli animali fanno senza scrupolo. Tutti ritengono che la morale che proibisce l'incesto si sia sviluppata nel tempo, pian piano. Eppure se si prende il popolo più arretrato (aborigeni australiani) è vietatissimo l'incesto. Viaggiando si era capito che gli usi riguardanti l'incesto erano i più vari: aborigeni completamente proibito, in altri obbligatorio. Nella famiglia reale egiziana era obbligatorio sposare la sorella. Alcune hanno una contraddizione interna (vietato, ma obbligatorio in una festa). Pensare che l'orrore dell'incesto sia naturale, è fuori luogo. Freizer: "La legge vieta agli uomini solo ciò che sarebbero ...".</p>

<?php t("2", "15/02/2011"); ?>
<?php t2("2.1", "Totem e Tabù"); ?>
<?php t3("2.1.1", "L'orrore dell'incesto"); ?>
<p>La risposta di Freud arriva nel quarto saggio. Dove c'è un divieto c'è un desiderio. La nostra psiche nonè la nostra coscienza (iceberg). La parte cosciente della psiche prova un orrore per l'incesto, mentre la parte incosciente la desidera. Alla fine dell'1800 ci si era posto il problema dell'obbligo dell'esogamia (aka incesto) (endogamia). La definizione di 'gamia', ovviamente non è unica, ma varia al variare della civiltà considerata. Esistono molteplici situazioni sociali, nelle quali viene prescritta l'endogamia. La miscegenzaione aka miscuglio di geni. Tre situazioni recenti per le quali era obbligatoria l'endogamia: Germania Hitleriana (ariani vs others), USA fino al 1967 (neri vs bianchi nel sud), Sud Africa (neri vs bianchi). Nonostante questo si obbligavano delle leggi esogamiche guardando la famiglia.</p>
<p>Un famoso filosofo finlandese (<b>Westermarck</b>) propone la teoria "Effetto Westermarck" e che propone che individui che nascono e vivono sotto lo stesso tetto, perdono l'interesse sessuale l'uno per l'altro. Questa teoria deduce un divieto da una situazione di disinteresse psicologico. Però questo non spiega l'esistenza di una legge che lo proibisca.</p>
<p><b>Emil Durkheim</b>, Francese di origine ebraica, contemporaneo di Freud e nel 12-13 scrive un'opera sull'analisi della religione anche lui basandosi sugli Aborigeni Australiani. Secondo lui c'è un orrore per il mescolarsi del sangue che colpisce maggiormente la donna (sangue mestruale). Con una donna con la quale si vive, ci sono situazioni in cui c'è una conoscenza del sangue, era situazione di non accettabilità. Questa teoria ha problemi su tutti i fronti, ma evidenzia per la prima volta inserisce la religione come causa.</p>
<p><b>Spencer</b> propone una teoria che si fonda su: "in un epoca in cui la virtù cavalleresca è il tratto distintivo di un uomo, la capacità di riuscire a prendere una donna di un'altra tribù, questo è un motivo di prestigio".</p>
<p><b>Lévi-Strauss</b> vede in modo capovolto il problema. Pensa che la regola che struttura il sistema sociale non i divieti. Secondo Lévi-Strauss una buona regola per una società sia quella di entrare in contatto quanto più pacifico con altri clan/famiglie. Una regola di "buon vicinato".</p>
<p><b>René Girard</b> rimane in una prospettiva Freudiana, considerando che il divieto preceda l'obbligo. Ma è un divieto (non Freudiano) che non verte sulla sorella// in quanto cosanguinee, ma il divieto verte sugli oggetti sessuali che essendo troppo vicini, possono creare una rivalità all'interno della famiglia stessa. L'idea è sostanzialmente Freudiana, ma Freud mantiene il tema della parentela, mentre René Girard vede come tema qualsiasi oggetto troppo vicino.</p>
<p>Il sistema Totemico australiano è basato su due principi:</p>
<ul>
<li>Divieto di uccidere l'animale/piante a cui si appartiene
<li>Discendenza matrilineari e patrilineare
</ul>
<p>Il Totem si può trasmettere per via di madre (matrilineare) o padre (patrilineare), in base alla tribù. Se consideriamo che il sistema originario è matrilineare l'incesto vietato è madre-figlio, mentre in caso patrilineare vieta l'incesto padre-figlia. Non si è sicuri, ma si è abbastanza convinti che fosse il matrilineare quello originale. Gli aborigeni, in realtà hanno creato una serie di classi matrimoniali, per fare in modo che all'individuo siano vietati i rapporti con ~75% delle donne vicine a lui.</p>
<p>Qualcuno sosteneva che l'incesto era vietato per evitare malattie genetiche, ma all'epoca non si conosceva il DNA e le malattie genetiche.</p>
<p>Non è chiaro se per gli Aborigeni Australiani ci sia un collegamento tra il rapporto sessuale e il figlio. La spiegazione che spesso veniva riportata era che la donna rimanesse in cinta il giorno stesso in cui se ne accorgesse. La donna rimaneva in cinta a causa di quel particolare totem che era particolarmente dominante nel posto in cui la donna si trovasse nel momento in cui se ne accorgesse. Quindi è impossibile che l'incesto fosse vietato per motivi di discendenza.</p>
<p>Freud si avvicina al problema affrontato l'argomento dell'<i>avoidances</i>. Quell'insieme di usanze che evitano il contatto tra persone vicine. Secondo Freud sono forme attenuanti del divieto dell'incesto. Dietro il divieto dell'incesto, c'è un divieto di un rapporto affettivo tra le due persone. I fenomeni psichici (antipatie..) on ha mai una causa sola, ma solitamente ne ha molte, anche se ogni una sarebbe abbastanza per spiegare il fenomeno. Secondo Freud i rapporti tra generi e suoceri sono difficili poiché quando l'investimento libidico è rivolta verso un oggetto esterno, uscendo dalla sessualità infantile, non lo fa direttamente investendo un oggetto esterno, ma su un oggetto vicino, come può essere la madre. Questo è la base del complesso di Edipo. La presenza materna (della moglie) risveglia il sentimento di affetto per la propria madre che è stato difficilmente sorpassato. Questo comporta un rischio di regressione e quindi deve essere tenuto a distanza. Parlando del Freud Antropologo, il maschilismo che Freud ha, non è così assurdo. Secondo Freud, possiamo affermare che l'orrore dell'incesto è un tratto "squisitamente infantile", in cui l'individuo non vuole che gli sia ricordato un elemento della vita infantile e che aveva rimosso in una fase precedente della sua vita psichica. Così questa regola è stata fatta per evitare che l'uomo regredisca all'età infantile. Secondo Freud, la società non si basa su un "contratto formale". Quando parliamo di una costituzione di leggi, per Freud, hanno una spinta affettiva non razionale, quindi sotto effetto di paure/angosce. Per Freud gli uomini non calcolano quando creano regole, ma sono mossi - come marionette - dalle loro pulsioni, in questo caso, erotiche. Uno dei presupposti del discorso umano è che gli umani sono tutti uguali, quindi non ci sono razze/etc. Freud non ha bisogno delle tesi diffusioniste perché le pulsioni della natura umana sono le stesse dappertutto. Il diffusionismo è quell'idea che considera che quando una cultura comincia a fare una cosa, gli altri li copiano. Gli uomini posso non aver sviluppato molti modi diversi, ma solo le usanze "positive" o "neutre" vengono eliminate. Questo spiega il motivo per cui molte usanze sono molto simili.</p>
<?php t4("2.1.1.1", "Riepilogo"); ?>
<p>L'orrore per l'incesto è l'orrore per la riemersione di uno stadio provato in una fase precedente e che bisogna superare. Sotto la potentissima spinta della realtà che rende inpossibile/inaccettabile la soddisfazione di questi impulsi, si costruisce una psiche come quella che conosciamo.</p>
<?php t3("2.1.2", "Il tabù e l'emotiva"); ?>
<p>Il tabù si può tradurre con l'espressione di <i>"orrore sacro"</i>, cioè un sentimento di repulsione assoluta per qualcosa che è motivi che non sappiamo e di cui no riusciamo a trovare una giustificazione concreta. L'effetto del Tabù è reale, perché le persone lo rendono reale. Si può infrangere un Tabù senza saperlo, ma questo non fa cambiare la colpevolezza della persona.</p>

<?php t("3", "17/02/2011"); ?>
<?php t2("3.1", "Totem e Tabù"); ?>
<?php t3("3.1.1", "Il tabù e l'emotiva"); ?>
<p>La tematica psicoanalitica che è in gioco è il parallelo che c'è tra il tabù e le nevrosi ossessive. Le nevrosi ossessive sono una classe di nevrosi. I nevrosi ossessivi hanno una ossessività nel fare qualcosa o una negazione di qualche azioni.</p>
<p>Freud elenca 4 punti di comunanza tra i nevrotici ossessivi e i Tabù</p>
<ul>
<li>Immotivazione delle prescrizioni
<li>Consolidamento attraverso una necessità interiore
<li>Dislocabilità e principio di contagio dell'oggetto identificato dal divieto
<p>Alcuni oggetti e persone hanno un carattere tabù che passano agli oggetti con cui vengono in <b>contatto</b>. Coloro che seppelliscono il morto, diventano tabù. Il contatto anche per l'ossesso è molto pericoloso, infatti non entra in contatto con ceti oggetti.</p>
<li>Se si entra in contatto con qualcosa che è tabù ci sono delle forme di rituale che devono essere eseguiti
</ul>
<p>I tabù sono di molte specie, alcuni temporanei (persone che entrano a contatto col cadavere), altri eterni (cadaveri), altri geografici e infine chi ha infranto il tabù. La dislocabilità del tabù, secondo Freud, è riconducibile alla capacità di associazione della nostra psiche. Il motivo del tabù e della nevrosi, è il concetto di contatto (fisico, o nominarlo). Il nevrotico si proibisce il contatto con un'oggetto che aveva dato un grandissimo piacere nella primissima infanzia, ma a questo piacere si contrappone un divieto esterno a toccare queste cose e trova all'interno della psiche trova un rafforzamento. Secondo Freud le proibizioni vengono interiorizzate se arrivano da una figura temuta/amata/odiata, quindi c'è un'ambivalenza affettiva, come il padre. Così facendo si crea un'istanza interna - il Super-Io - cioè l'interiorizzazione del padre. Il conflitto tra desiderio e divieto può spiegare le dinamiche compulsive del nevrotico ossessivo e i tabù. La libido può essere trasformata o spostata, ma non si crea e non si distrugge. L'azione proibita è un'azione che l'inconscio vuole compiere.</p>
<p>Freud analizza</p>
<ul>
<li>Tabù del sangue dei nemici
<p>Freud vuole dimostrare che le forme di prescrizione che sono imposte ai guerrieri che hanno ucciso dei nemici, sono il risultato di un'ambivalenza emotiva. Poiché è evidente il motivo per cui si giustifica questa azione, bisogna dimostrare che esista la pulsione che ci imponga di trattare i nemici con rispetto. Freud prova a eliminare l'ipotesi più ovvia e comune, che prevedeva la paura degli spiriti dei nemici. Freud sostiene che c'è un'apparente legge di non uccidere. Secondo Freud c'è un'identificazione nel nemico ucciso. Quindi nel provare quel minimo di rispetto e umanità che si prova nelle cerimonie di purificazione. Il carattere comune di queste purificazioni era la privazione di piaceri ed entrare in contatto con gli altri. L'idea che c'è ma che Freud non espone, è che colui che ha ucciso, ha provato un piacere che potrebbe averlo inebriato e quindi deve liberarsi da questo stato prima di ritornare nella società.</p>
<li>Tabù che riguarda la figura del sovrano
<li>Tabù che riguarda i morti
</ul>
<p><b>Colui che infrange un tabù, diventa a sua volta oggetto di tabù</b>. Freud cerca sempre risposte più ampie. Si chiede, perciò, perché ci sia un collegamento tra il tabù e chi lo trasgredisce. La risposta è che la persona risveglia negli altri la tentazione di fare quel qualcosa. Se la violazione del tabù non ha provveduto a punire la persona stessa, le altre persone lo puniranno, per paura dell'esempio negativo. Non di rado, le persone colgono la situazione per fare la stessa azione ma in modo "giustificato". Questo è uno dei fondamenti del sistema giudiziario moderno.</p>
<p>Il contatto da un punto di vista sociale è anche un contatto aggressivo. Freud, successivamente, si chiede se ci sono solo pulsioni per il piacere (sessuali) o altre pulsioni, come le pulsioni distruttive (di morte). Una persona terrorizzata, continua a sognare cose che lo terrorizzano, ma questo è contro la classe di pulsioni per il piacere, quindi - probabilmente - c'è un'altra classe di pulsioni. Questo, però, Freud lo pensa solo successivamente. Freud al momento sostiene che il mettere le mani addosso a qualcuno, sia una forma di trasformazione delle pulsioni sessuali.</p>

<?php t("4", "21/02/2011"); ?>
<?php t2("4.1", "Totem e Tabù"); ?>
<?php t3("4.1.1", "Il tabù e l'emotiva"); ?>
<p>Parallelo tra le azioni degli ossessi e dei tabù. Questo è manifesto nel fatto che entrambi i casi hanno un'ambivalenza conscio/inconscio. Così come il tabù si sposta perché si sposta il desiderio così i rituali dell'ossesso provengono da un'ambivalenza nei confronti di determinate azioni.</p>
<ul>
<li>Tabù del sangue dei nemici
<p>Da un lato la soddisfazione per averli uccisi, e dall'altro il necessario blocco di questi impulsi per tornare alla vita di tutti i giorni. Freud non lo dice in modo esplicito, ma è necessario che quell'atteggiamento aggressivo non contamini i momenti di vita normale. Per far questo ci vuole un momento di "quarantena". Freud non lo spiega in questi termini, ma spiega l'operazione opposta (quando un guerriero si appresta andare in guerra si deve lasciar cadere tutti i freni inibitori che solitamente ha, quindi deve fare dei riti per favorire l'emersione dello spirito aggressivo.</p>
<li>Tabù che riguarda la figura del sovrano
<p>Nel caso dei sovrani, tutto è ambivalente. Freud mette in rilievo una serie di contraddizioni. Dai Re ci si deve guardare (i re fanno diventare pericoloso qualsiasi cosa toccano), ma il contatto con il Re è in grado, a volte, di guarire (es scrofola) toccando. attribuire a qualcuno un potere immenso (far guarire, e far ammalare) è la conseguenza di un delirio paranoico. Questo non è altro che la proiezione su un'altra persona di quei poteri terribili che il bambino attribuisce al padre. Per il bambino, il padre è onnipotente (sia nel bene sia nel male). La stessa persona può essere odiata e amata allo stesso momento. Questa ambivalenza è facilmente capibile se avvicinata a quella paterna, il quale sembra onnipotente e però sbarra la strada verso uno dei voleri del bambino (incesto).</p>
<p>Esistono una serie di obblighi per difendere il re, ma questi obblighi possono diventare 'apprensivi'. Questo è paragonabile al rapporto madre-figlio. Questo è un rapporto ambivalente, perché per 'amore' gli si impone di non fare una vita 'normale'. Frazer scopre che molti re sono uccisi ritualmente. Quindi c'è una connessione statisticamente difficile da spiegare, connesse tra il potere del re, e il sacrificio rituale. Anche nei posti dove manca, ci sono dei 'doppi del re' (giullari, carnevale, ...) che fa da sacrificio rituale. Il re è un sostituto della figura paterna, quindi ci si spiega il motivo di questi scoppi d'ira verso il re. La divisione tra un re 'sacro' e uno che si occupa di affari. Nella originale forma, il Re diventa garante che tutte le cose naturali succedano come devono, 'regna'. In molte società, il 're sacro', non essendo in grado di comandare, ha un sdoppiato che non ha l'aura religiosa, e che quindi può governare liberamente. <b>Spesso venerazione e persecuzione sono cose che vanno assieme, quando si parla di umani.</b> Quando le azioni ossessive si trasformano in un complesso rituale, finiscono per costituire dei deliri organizzati. Freud non pensa che la nostra cultura sia basata su deliri organizzati, perché pensa che un delirio organizzato si scontra prima o poi con la realtà e crolla. Freud, dopo il 1933, comincia a pensare seriamente che ci possa essere qualcosa come una paranoia totale, vedendo il Nazismo.</p>
<p><i>Secondo interpretazioni di Frazer i primi re erano stranieri che dopo un breve periodo di regno sarebbero stati sacrificati in una cerimonia sacra.</i> Freud sostiene che il Cristianesimo ancora abbia delle rimanenze di questo. Freud potrebbe alludere al fatto che Gesù è stato proclamato Re (INRI) e fornito di corona. Secondo Frazer questa è una grottesca presa in giro, come quella che avviene nelle Saturnali. Questo potrebbe essere visto come nuovi esempi di re-sacrificale.</p>
<li>Tabù che riguarda i morti
<p>Perché ci sono così tanti tabù intorno alla morte? Cadaveri, omicida, arma del delitto.... Il tabù dei morti è più forte quando le persone morte sono care (parenti, persone vicine). Questo perché si pensa che la persona appena muore diventa uno spirito che vuole fare del male. Freud è colpito dal fatto che più la persona è vicina, più vuole fare male. Il vedovo e la vedova sono pericolosi da un punto di vista sessuale. Un parente può essere scosso e quindi pericoloso. I morti uccidono perché hanno un rapporto particolare con la morte. Una specie di commistione tra i morti e la morte. Westermark sostiene che gli uomini associano ai propri morti. Secondo i primitivi non esiste la morte naturale, c'è sempre la volontà di qualcuno. Ecco allora perché i morti diventano sempre cattivi, perché sono sempre persone colpite da un torto. Dopo che si vendicano, gli antenati diventano buoni. Freud accetta la spiegazione di Westermark, però non pensa che questa sia l'intera spiegazione. Freud sostiene che gli antichi sappiano che ogni morte è un'uccisione. Quando una persona muore, è naturale che tutti coloro che hanno trattato male il morto o si è stati trattati male da essi. Se una persona muore non ha voluto morire, ma stiamo male perché ci ha lasciati, e quindi si crea una corrente di ostilità verso il morto. Il sopravvissuto nega questo, ma non lo fa in modo ipocrita, non potendolo riconoscere come proprio, quindi lo si proietta sul morto verso di se. Il demone è composto dal nostro odio verso il morto.</p>
<p>Freud basa la religione, la cultura e la società sulla proiezione. Freud da una definizione di <b>proiezione</b>:<i>Freud suppone che il cervello umano abbia, originariamente, la funzione - soltanto - di percepire i processi esterni (esopsichici) e percepisce i processi endopsichici soltanto come forma di piacere o dispiacere.</i> L'individuo non pensa a ciò che pensa, ma percepisce soltanto i sintomi esterni e il piacere e il dolore. I processi endopsichici più potenti vengono attribuite a un fenomeno esopsichico. Il cervello umano una macchina che trasforma in stimoli esterni, ciò che è uno stimolo interno. Proiettare costituisce la risposta più adattiva, e anche se il suo risultato è falso, può essere utile alla sopravvivenza. Il mondo dei popoli antichi, sono popolati da spiriti, demoni, anime, etc e sono da trattare come proiezioni di fenomeni. Si proietta per liberare la mente da contraddizioni.</p>
</ul>

<?php t("5", "22/02/2011"); ?>
<?php t2("5.1", "Totem e Tabù"); ?>
<?php t3("5.1.1", "Il tabù e l'emotiva"); ?>
<p>Se l'attenzione del cervello umano è essenzialmente rivolta verso l'esterno è prevedibile che i fenomeni interni alla psiche vengono vissuti come se fossero esterni. Quando un uomo si trova in condizioni estreme, l'attenzione per la vita interiore si affievolisce, e si acutizza l'attenzione per la vita esteriore. La proiezione sgombera la mente da contraddizioni affettive, proiettando all'esterno una delle due parti della contraddizione. Proiettando qualcosa al di fuori, si sgrava la mente, e credo di poter padroneggiare quella cosa.</p>
<p>Il sogno serve per garantire il prolungamento del sonno. Per questo non possono essere troppo espliciti, però non vengono censurate. Le pulsioni assumono una veste presentabile. L'operazione onirica primaria serve per evitare che la persona si svegli a causa di quello che ha sognato. L'operazione onirica secondaria. L'esigenza che il sogno non disturbi il sonno, il sogno necessita una certa logica (anche non completa). </p>
<p>Quando una persona proietta all'esterno propri sentimenti, gli deve fornire una veste di accettabilità. Il delirio paranoico ha la funzione di mettere in un sistema razionale pulsioni primitive che non ha nulla di razionalità. Lo psicotico può essere una persona in cui nulla più di coerente trapela, mentre nel paranoico, tutto è logico. La magia, l'animismo, la proiezione verso l'esterno, i demoni sono tipici dei sistemi paranoici. Per diventare collettive, devono per forza essere fenomeni logici, almeno in apparenza.</p>
<p>Freud pensa che nella civiltà moderna, il tabù della morte ha perso potere, rispetto al passato. La vita emotiva è diventata più tenera e ci sono più collegamenti positivi che negativi all'interno della famiglia. Quindi c'è meno motivo per odiare la persona che è morta, e di conseguenza proiettargli addosso il proprio odio.</p>
<p>Il tabù è anche alla base della nostra morale. Infatti moralità vuol dire la preclusione di compiere atti che seguono un desiderio. L'istanza morale che c'è dentro di me, è una istanza repressiva esterna, interiorizzata. Il tabù, come la morale, è frutto di una cultura che noi facciamo nostra (interiorizziamo) ma che è contro le nostre pulsioni. <i>Più la cultura è moralmente e sessualmente repressiva, più individui nevrotici e quindi infelici saranno presenti.</i> Non è pensabile una società nella quale nessuna morale/tabù è presente. <i>Il soddisfacimento sessuale è innanzi tutto un fatto privato dell'individuo.</i> È impossibile stringere relazioni pubbliche, senza distogliersi dal proprio partner. Le forze sessuali non cimentano le relazioni tra le persone. Il nevrotico grave ha delle pulsioni sessuali molto potenti, e fugge dalla realtà, perché esso è in contrasto con la società.</p>
<p>Nella prima teoria di Freud evidenzia due pulsioni: quelle erotiche e quelle di conservazione. Le prime devono essere tenute a freno per poter avere anche le seconde. Questa non è una teoria bipolare, perché entrambe le pulsioni sono pulsioni di piacere. Le seconde garantiscono nel tempo una maggiore continuità delle prime. Questa è una dottrina ottimistica, perché nel complesso è una struttura pulsionale che è tutta rivolta al piacere.</p>
<?php t3("5.1.2", "Animismo, magia e onnipotenza dei pensieri"); ?>
<p>Freud riconduce una serie di pratiche, come la credenza nella magia, negli spiriti, etc, alla fase del narcisismo.</p>
<p>Freud pensa che ci sia uno sviluppo ordinato nello sviluppo umano.</p>
<p>Tutti i popoli hanno forme di magia, tranne quelli che ne sono terrorizzati. Il divieto biblico di fare immagini di esseri viventi (e di Dio) non nasce dall'idea che la magia non esiste, ma dal fatto che c'è il timore che un'immagine possa essere usata per scopi magici. Secondo gli egizi, quando il Dio del sole (Ra) calava (tramonto), esso stesse combattendo una lotta contro degli spiriti che provavano a prolungare il più possibile la notte. Il compito dei sacerdoti, era quello di creare immagini di questi demoni, e poi la figura veniva 'maltratta' per aiutare Ra a riemergere il mattino dall'orizzonte. L'azione sugli spiriti si chiama incantesimo. Le pratiche magiche sono antecedenti delle pratiche di incantesimo. Freud sottolinea che la magia è caratterizzata da una sopravvalutazione del pensiero. L'uomo attribuisce alla capacità di collegare due fenomeni psicologici anche a due fenomeni reali. Quando ci si offende, si pensa che questo possa essere una forma di reazione utile. Questa è una forma di sopravvalutazione del pensiero. I bambini molto piccoli non hanno quasi mai la capacità di agire, e quindi usano moltissimo questa capacità. Il piangere è la scoperta della propria debolezza nei confronti del mondo esterno. Il bambino cerca e trova soddisfazioni illusorie.</p>
<p>L'auto-erotismo che il bambino ha, spesso si manifesta come dito in bocca. La prima fase auto-erotica è caratterizzata da attenzioni verso una parte dell'oggetto e non la sua totalità. Nella seconda, invece è caratterizzata da attenzioni verso un'intero oggetto. Un caso del primo momento è la bocca. Il primo oggetto intero investito di una libidine è lui stesso. Questa è la fase narcisistica, e il bambino si comporta come se fosse innamorata di se stessa. È ancora incapace di investire un'esterno di libidine, ma è già in grado di vedere se stesso completamente come oggetto libidico. Come noi sopravvalutiamo la persona amata, così l'individuo nella fase narcisistica pensa di essere capace di quasi qualunque cosa. Se una persona rimane in questa fase, si diventa megalomani. Il narcisismo intellettuale e l'onnipotenza dei pensieri vanno di pari passo. Nel narcisismo l'individuo non fa i conti con la realtà esterna. Una persona può pensare di essere immortale solamente se è in una fase di esaltazione narcisistica. Il narcisista può raggiungere uno stato di ebrezza senza paragoni, poiché solo lui può vantare l'intera attenzione del suo oggetto di amore. Il narcisismo può acquisire una certa accettabilità se diffuso socialmente. In questi casi il narcisismo deve essere metodizzato e quindi può sopravvivere in modo collettivo senza che questo carattere faccia crollare la società.</p>

<?php t("6", "24/02/2011"); ?>
<?php t2("6.1", "Totem e Tabù"); ?>
<?php t3("6.1.1", "Animismo, magia e onnipotenza dei pensieri"); ?>
<p>Il narcisista è onnipotente all'interno del suo recinto (se stesso). L'impatto con la realtà può risvegliarlo da questa fase. La magia è molto reale dal punto di vista psichico, poiché la credenza nella magia produce l'effetto che credee di produrre, in certe situazioni. "Nella vita, si può dire, che conta soltando la moneta nevrotica". Cioè, non le cose per quel che valgono, ma quello che noi gli diamo. Una persona che sia profondamete inconsapevole delle pulsioni, pensa che la realtà è plasmata da lui. "conoscere che un'idea è adeguata non è sufficiente a scacciare un'idea inadeguata" (Spinoza). La cura non consiste nello spiegare la causa al malato. "Per scacciaare una passione, serve unaa passione più potente" (Spinoza).</p>
<p>Freud e Jung hanno una grande differenza. Supponiamo che qualcosa cancelli per una generazione intera fiabe, miti, leggende, religioni. Cosa succederebbe secondo Jung? Questa generazione ritroverebbe, ricostruirebbe da dentro di se tutti i miti identici o molto simili a quelli originali. Freud non accetta questa teoria perchè Jung non da spiegazioni che non meta-fisica. Freud, invece, l'uomo che si trovasse in una situazione di azzeramento del patrimonio culturale, lo ricostruirebbe a partire dalla presetazione da quei fenomeni che avevano creato i miti in primis.</p>
<p>Una volta mostrata l'inesistenza concettuale delle magie, e della utilità per chi ci crede, non si è dissolta la magia. Quelle che noi chiamiamo "malattie nervose", nonostante la gravità dei sintomi e il dolore che il malato prova, la malattia può essere il male minore. Il sintomo, per quanto doloroso, è meglio dell'alternativa. La pulsione si scarica sempre là dove la resistenza è minore. Questi sintomi tendono ad organizzarsi nella forma mia coerente possibile.</p>
<p>L'isteria è una caricatura del gesto dell'artista. La mania dell'artista è la musa, mentre all'isterico consiglia cose senza alcuna bellezza. La nevrosi ossessiva è la caricatura di una religione. I religiosi compiono dei gesti rituali, così fa anche l'ossessivo. Il delirio paranoico è la caricatura di un sistema filosofico. Entrambi hanno la ricerca assoluta di una coerenza a partire da presupposti che possono non avere delle evidenze sulla base empirica.</p>
<p>Caso del <b>presidente Schreber</b>: un delirio organizzato che trova un compromesso con la realtà. Parte da alcune premesse e costruisce un sistema di incredibile precisione. I sistemi filosofici riescono a conquistare più seguaci rispetto al sistema del Presidente Schreber. Il Presidente Schreber era un eminente giurista della Sassonia, molto rigido dal punto di vista morale e religioso. Cristiano inmodo "molto convinto", e ad un'età avanzata ha avuto un esaurimento nervoso di circa un'anno. In questo periodo viene curato da Flechsig. Quando la sua carriera sta per fare un salto, ha un altro crollo psicologico. Cade in un delirio paranoico ricchissimo di dettagli. Riusciva a tenere una facciata di normalità, mentre nei momenti dove non era obbligato, delira. Scrive un'opera per ricordare le sue memorie per cercare di dimostrare che i suoi deliri sono reali. Freud si getta su questo caso perché i malati di paranoia non possono andare nel suo studio, perchèerano rinchiusi. La terapia del nevrotico a distanza non ha senso perché ci deve essere interazione tra le due parti. Il paranoico, invece, dice sempre e soltanto quel che gli pare. Quindi l'interazione con il medico non è una variabile. Schreber afferma che il tutto è nato dall'idea che essere donna e sottoporsi alla copula possa essere buona. Freud ritiene che Schreber ha creato un'enorme struttura per rifiutare la cosa. Ilsistema del pensiero si costituisce di due punti. Schreber ritiene di essere destinato al ruolo più importante che l'universo abbia mai avuto. Il suo essere donna è necessario perchè deve creare una nuova specie. Secondo lui gli attuali uomini sono cadaveri o finzioni di uomini, perchè Dio ha sterminato l'umanità. Pensa che Dio sia cattivo e che agisce con dei raggi che escono dal sole che portano malattia. Dio capisce e ama soltanto i morti, e che avendo visto in lui un'individuo in cui i nervi sono più potenti di quelli di Dio. Il dottor Flechsig è il boia di Dio che prova ad assassinare la sua anima. L'ordine delle cose è favorevole a Schreber, Dio (che è cattivo) non può giungere ad assassinare la sua anima perché l'ordine delle cose glielo impedisce. Tutte le cose che non quadrano trova una spiegazione ad-hoc. Arriva a dire che un dottore ha fino a 40 diverse realtà. Le parole che usa in certi momenti (volgari) sono esatte perché espongono lo stato delle cose. Quando viene dichiarato guarito dalla seconda malattia, mantiene quasi tutte le sue idee. Tra cui quella che l'umanità non esista più.</p>
<p>Freud pone il problema sul rapporto col padre. Il sogno di essere donna è il sogno di essere evirato. È un timore che il bambino maschio sperimenta di fronte alla figura paterna. Secondo la spiegazione di Freud, la figura del sole (cattivo), del medico (cattivo), ..., sono proiezioni del padre o di un fratello maggiore. Freud afferma che Schreber è un malato di proiezioni, nel senso che ha proiettato sulle varie figure immagini del padre. Padre che deve eessere stato una vera ira di Dio. Il padre di Schreber è un medico che inculcò il culto per la ginnastica dei bambini nella società. Questa educazione era ferocemente avversa verso l'auto-erotismo, minacciata in qualsiasi modo. C'erano dei limiti al limite del sadismo per imporre la postura. Questa è stata chiamata la "pedagogia nera". Sotto il nazzismo, queste intuizioni, vennero spinte all'estremo. Sottoposto a un padre così, Schreber, cerca di compensare l'umiliazione estrema di queste pratiche educative, inventando per se stesso un ruolo cosmico, e spiegando le sue paure aggiungendogli un fine gratificante. Quando il padre è così amato e così temuto, ha eretto se stesso ad individuo di importanza universale, per fare delle sue paure un motivo di vanto. Una delle cose che Schreber mantenne, uscito dalla casa di cura, è il sostenere di poter guardare il sole senza farsi male agli occhi. L'emblema di famiglia aveva l'aquila, e l'aquila può guardare il sole senza problemi. Al che dimostrava che lui discendeva dal sole, e quindi il Sole cattivo era suo padre.</p>

<?php t("7", "28/02/2011"); ?>
<?php t2("7.1", "Totem e Tabù"); ?>
<?php t3("7.1.1", "Il ritorno del totemismo nei bambini"); ?>
<p>In questo capitolo, Freud ci parla dell'origine delle religioni. Freud pone l'origine delle religioni nell'infanzia dei bambini. Nell'inconscio di ogni adulto ci sono segni delle manifestazioni di fenomeni avvenuti quando lui era piccolo. Il bambino, di fronte ad un affetto potente, è privo (o meno dotato) di deviare l'affetto verso altre cose. Gli adulti hanno a disposizione tanti oggetti sostitutivi per la loro vita psichica. Per i bambini, invece, ci sono quasi solo le figure parentali. Il bambino non è in grado di distrarsi in altro modo, perchè non si è ancora aperto a quella varietà di esperienze. Il bambin può superare il trauma, ma questo andrà a toccare tutta la sua vita psicologica. Se i genitori gli provocano qualcosa, esso non imparerà a rivolgere altrove la sua attenzione. Freud insiste tato sulla costituzione psichica del bambino perchè la religione ha una potente forza affettiva, essa non può essersi imposta nella fase adulta. La religione non può essere nella psiche umana nell'età adulta. Le paure, i terrori etc colpiscono molto meno gli adulti che i bambini. Come il nevrotico è essenzialmente legato ad una condizione infantile che non riesce a superare, così l'uomo religioso è caratterizzato da una condizione infantile. La religione è da legarsi con un particolare trauma che ha colpito l'umanità in un'epoca lontanissima. Secondo Freud le religioni non sono causate da un'accumulo di eventi, ma da un evento unico che è punto di origine delle religioni. A partire da quel momento, le religioni hanno dominato l'umanità. L'uomo religioso, soffre per la reminescenza di quel trauma.</p>
<p>I traumi di guerra non lasciano gli stessi effetti nell'uomo adulto se non vengono collegati ad un trauma infantile. Quando si parla di trauma, dobbiaamo ricordare che per Freud il nervrotico non conta tanto che il trauma sia riconducibile ad un fatto reale. Freud, all'inizio, si rende conto di quanto frequentemente il ripo di ricordo che veniva rimosso e che provocava malattia da adulto è caratterizzato da un trauma sessuale oviolenta da bambino, nella maggior parte da parte del padre. Si rende conto che il trauma può non essere avvenuto realmente, ma basta che il bambino abbia freinteso l'azione del padre. Da un punto di vista legale, le due cose sono molto diverse, ma da un punto di vista psicanalitico è quasi identico. Alcuni ricordi sono falsi, anche se sono molto realistici. Secondo Freud ci sono dei rapporti platoici che sono costitutive per l'essere umano, e se vengono intaccate i danni sono enormi.</p>
<p>Il punto di contatto del rapporto totemismo-bambini è: come il totem una religione che afferma che gli individui di un clan sono discenenti dal totem stesso, così l'animale è nella vita psichica del bambino, sta a sostituireil padre. Questo è quello che si evince anche solo ascoltando gli aborigeni. Il bambino attraversa una fase totemica, in cui la figura paterna viene esteriorizzata su un animale. La fobia da animale costituisce la fase totemica del bambino.</p>
<p>Il totemismo è l'oggetto del discorso Freudiano perhè sembra essere la forma religiosa più antiche. Cogliendo la vera natura del totemismo, si possono cogliere tutte le nature di tutte le religioni. Essere totemici significa:</p>
<ul>
<li>considerare che un animale l'antenato della tribù
<lI>il totem si eredita per linea materna
<li>non si può uccidere ne mangiare il totem
<li>non si  possono avere rapporti sessuali con un'altro appartenente allo stesso totem
</ul>
<p>Questo è il codice della più vecchia religione al mondo. Freud cerca di dare una spiegazione cominciando con l'analisi delle dottrine presentate dai suoi contemporanei.</p>
<p>Un'insiseme di teorie chiamate <b>nominalistiche</b>. Il totem è stato attribuito a un certo clan perchè originariamente qualche individuo fu individuato un tratto comune con un animale. Successivamente c'è stata una confusione tra il nome vero e il nome totemico. L'idea che un nome attribuito da altri, fosse rimasto appiccicato a un clan era molto improbabile. Queste teorie sono statedemolite</p>
<p>Spiegazione <b>sociologica</b>. (Durkain) pensa che il totemismo nasca da una forma di aggregazione sociale molto particolare: es: coloro che avevano a disposizione un gran numero di animali di un certo tipo, hanno cominciato a vendere la pelle/carne dell'animale. Una specie di cooperativa di consumo. Secondo lui nel totemismo uello che conta è semplicemente la società stessa. Quello che ogni clan venera come totem, in realtà, è il clan stesso. L'unica cosa che trascende il singolo uomo è la società stessa. Il 'Dio' dell'individuo è la società stessa. L'unica cosa che merita il titolo di divinità è l'unioe di tutti gli individui. L'intuizione è che Dio è la folla, la massa. Dio nasce quando in una società c'è un'insieme di individui che agiscono collettivamente. Quando gli individui hanno 'provato' la massa, pensavano di aver davanti  un evento sovra-umano. Il totem è il vessillo agitata quando la società agisce tutta assieme. Quello che conta del Totem sono proprio i colori. Tutti i fenomeni collettivi sono un'esperienza religiosa originaria. L'elemento decisivo della religione è stare tutti assieme a fare la stessa cosa. Non sono importanti i contenuti, ma gli aspetti sociali. La religione è cagulazione. Tutto quello che è rito, serve a tenere assieme. Solo lo stare tutti assieme a fare la stessa cosa può dare all'uomo quel brivido di un qualcosa di superiore. Chi compie un gesto all'interno di una comunità coesa prova un sentimento che lui chiama <i>effervescenza</i>. Le nostre sensazioni vengono potenziate. Quando una massa agisce tutta assieme, si ha un'effetto paragonabile a quello degli allucinogeni. Il sacro è quel brivido che passa all'interno di una persona che sta agendo all'interno di una massa. Non esiste una religione privata ne morale. Freud liquida questa teoria in modo troppo veloce. Freud non l'accetta perchè non spiega il divieto dell'incesto da un punto di vista sociologico.</p>
<p>Ne Freud ne Durkain uniscono il narcisismo ad una forza di massa è uno dei temi del libro sulle masse.</p>
<p>Altri parlano di una natura psicologica del totemisco, i quali pensano che il totemimo nasca dalla considerazione che il totem è la forza che produce la gravidanza della donna. Il totem sarebbe la forza che feconda le donne. Frazer afferma che il totemismo è il risultato delle donne in cinta.</p>
<p>Freud propone di immaginare come sono vissuti gli essere umani nei tempi più remoti. La risposta nasce da un'osservazione fatta da Darwinin <i>l'origine dell'uomo"</i> sulla gelosia e sull'improbabilità della promisquita dei sessi. Possiamo supporre che l'uomo premitivo come tanti animali che conosciamo vivesse in origine in piccole comunità con un uomo e tante donne quante lui possa mantenere e ottenere. In ogni "orda" si ha soltanto un maschio adulto. Il giovane maschio quando diventa sessualmente attivo, il più forte - dopo aver ucciso o cacciato l'altro - si impone come capo della comunità. Allora, come osservò Hatchinson, se il maschio che nasceva all'interno di un certo gruppo, queste orde erano già esogamiche. Nei bambini abbiamo una singolare predisposizione di cadere in una nevrosi fobica nei confronti degli animali. Questo perchè l'animale viene visto come eviratore. Arrivando ad identificarsi nell'animale temuto. La duplice carica affettiva verso l'animale è paragonata da Freud al rapporto col padre. Quindi l'animale totemico è il padre (A=B, B=C => A=C). Il padre geloso dell'orda primitiva, abbiamo motivo di supporre sia il totem. La figura del totem con tutti i divieti che impone sia il padre. Se il totem è il padre, ci spieghiamo il divieto dell'incesto.</p>

<?php t("8", "01/03/2011"); ?>
<?php t2("8.1", "Totem e Tabù"); ?>
<?php t3("8.1.1", "Il ritorno del totemismo nei bambini"); ?>
<p>Se lanimale totemico è il padre, i due comandamenti fondamentali del totemismo, coincidono quanto a contenuto con i due delitti di Edipo e con i due desisderi primordiali del bambino.</p>
<p>Dopo Freud, non solo la visione dell'infanza viene modificata dalla visione dei popoli primiitivi e viceversa, quest'opera collega elementi che nessuno avrebbe mai pensato di collegare. La tragedia e il mito non sono opere, ma sono rappresentazioni di pulsioni che abbiamo. Anzichè tirar fuori la Grecità, come se fosse un'essenza, Freud afferma che queste pulsioni foondamentali trovano la loro espressione nella tragedia e anche in altre forme di arte.</p>
<p>Freud si occupa del sacrificio. Non tutte le religioni sono totemiche, anche se si pensa che sia alla base di tutte le culture. Il sacrificio, però, è presente in tutte le culture e se la si riesce a provare che c'è una connessione con il rapporto padre-figlio. Come dice Freud, la parola sacrifico (come rinuncia) è un'accezzione sicuramente posteriore. All'inizio non era così. Un altro concetto sbagliato, è uello del sacrificio come offerta alla divinità. Il sacrificio originariamente è semplicemente una uccisione collettiva. Sacrificare vuol dire linciare. L'esempio di sacrificio che Smith ci riporta fuga ogni dubbio. Il sacrificio è da intendersi come distruzione di un'essere umano o un animale. Tutte le religioni conoscono il sacrificio, in tutte le religioni il sacrificio è cruento. Con una grandissima probabilità, i primi sacrifici furono umani, per poi trasformarsi in sacrifici animali e poi prodotti della terra etc. Il pasto sacrificale è una usanza di uccidere un animale, solitamente proibito, tutti assieme, mangiarlo tutti assieme. L'animale considerato intoccabile viene ritualmente ucciso e mangiato. Chi partecipa al rito, spiegano che un modo per stringere rapporti con le altre persone. <b>Kinship</b> è quel legame sociale con quello persone cui mangi. Il pasto "totemico" è un pasto. La proibizione di mangiare un'animale ma l'obbligo di mangiarlo in certi momenti, rappresenta un'ambiivalenza. In modo chiarissimo, l'ambivalenza nei confronti del totem da origine a reali fatti cruenti. In molte feste documentate presso popoli primitivi, la festa che seguiva il pasto totemico, era caratterizata dall'abrogazione dell'incesto. Freud non accetta il soddisfacimento delle pulsioni come fatto immaginario. Il mito di Edipo non è una storia inventata, ma dobbiamo supporre che le prime manifestazioni della vita sociale degli uomini siano stati cruenti. Secondo Freud, quando parliamo di miti, probabilmente, siamo difronte a fatti reali. Con questo discoso, Freud mette sulla carreggiata del ragionevole tutta la scienza dei miti.</p>
<p>I più antichi modi di omicidio sono collettivi e deresponsabilizzati:</p>
<ul>
<li>Spingere una vittima verso un precipizio
<li>Lapidazione
<li>Plotone di esecuzione
</ul>
<p>Qui abbiamo la prova che le religioni sono una prassi sociale. Poichè la religione ha bisogno di adepti, non può dare vantaggi solo a un piccolo gruppo di persone. Le religioni sono un fenomeno collettivo perchè rispondono a un'esigenza umana, cioè sentire la propria forza moltiplicata grazie alla presenza degli altri. La religione non è un'inganno di qualche astuto individuo, ma è il prodotto di un'immaginazione collettiva. La religione non può esistere senza una chiesa. Un'ossessione si distingue da una religione per il carattere pubblico che la seconda ha.</p>
<p>Freud è ateo e il suo rapporto con l'ebraismo è molto complesso. Non respinge la sua cultura ebraica.  Freud cercherà di mostrare che l'ebraismo non è così originale quanto sembra.</p>
<p>I fratelli scacciati dai clan, si riunirono, abbatterono il padre e lo divorarono.  Uniti, i fratelli osarono compiere ciò che risultava impossibile. Uccidedo e mangiando il padre, ogniuno si identificò in modo più forte nel padre. L'uccisione del cammello è la commemorazione di quell'antico pasto che vide i fratelli mangiare il padre. Ogni festa, in origine, è la commemorazione dell'uccisione del padre. Freud poi interpreta altre forme di comunione da quella derivanti dal padricidio. Se avessero ucciso uno straniero, essi sarebbero stati meno contenti, perchè il padre è la persona è meno odiata, però ci sarebbe anche meno <i>senso di colpa</i>. Mentre festeggiavano, già si sentivano tristi. Iniziano tacitamente ad obbedirgli post-mortem. Avevano cioè introiettato la figura opprimente esterna. Così si crearono le due regole totemiche. I due tabù fondamentali i fratelli se li sono dati, ma essi hanno diverso valore. Il divieto di uccidere il padre si basa sul senso di colpa dei figli, e il divieto dell'incesto è l'obbedienza retrospettiva. C'è anche un secondo motivo: il bisogno sessuale li divide, non li unisce. In questo modo loro salvarono l'organizzazione che li ha fatti forti. Non è da escludersi che la lega costituita che, come ogni unione sociale, doveva esserci una forma libidica. Non è da escludersi che la "società dei fratelli" si basasse anche su elementi omosessuali sviluppati nel momento di distanza dalle donne.</p>
<p>La religione totemica nasce dal senso di colpa dei figli. Come tentativo di riconciliarsi col padre è usata l'obbedienza retrospettiva. Ogni uomo (maschio) ripercorre questo procedimento nella sua infanzia.</p>
<p>In una società che è costituita sui due imperativi totemici ha bisogno di risaldare il legame tra fratelli? Ripetendo l'azioneche l'ha creata. Un'uccisione che ricorda quella lontata uccisione. È un momento di identità comunitaria. Freud guarda come alcune religioni (in  particolare quella cristiana) si siano articolate su questo. Nelle religioni, Dio è il padre e la religione è un modo per recuperare alcuni aspetti del rapporto col padre. Tuttavia il surrogato del padre (animale totemico) può essere la madre.</p>

<?php t("9", "03/03/2011"); ?>
<?php t2("9.1", "Totem e Tabù"); ?>
<?php t3("9.1.1", "Il ritorno del totemismo nei bambini"); ?>
<p>Quest'opera pone dei tentativi di soluzione straordinarie, ma non è completa come opera. Le intuizioni che ha, sono molto brillanti e alcune questioni sono ancora aperte.</p>
<p>Freud pensa che alla <b>fondazione della società ci sia un parricidio</b>. Da questo, si può far derivare tutte le formazioni culturali. Il sacrificio, la più importante istituzione religiosa. Da un lato il sacrificio è una ripetizione dell'uccisione del padre, ma dal momento che il sacrificio è offerto alal divinità, il padre apapre come vittima dei fratelli e anche colui che, amato, si rivolge un'atto di sottomissione. Le istituzioni sociali nascono tutte da quel sentimento tra i fratelli. La fratellazna non è soltanto razionale, ma è anche fondata su un comune senso di colpa. Una società non si può solo basare su una convenienza. Secondo Freud, una società richiede anche un vincolo affettivo. Al di sotto di un vincolo sociale, ci deve essere una sublimazione della libido.</p>
<p>La <b>società</b>, con tutti i suoi <b>divieti</b>, si impone in modo contrastante con i desideri primari umani. Si può quindi capire, che questo non può essere creato da un mero calcolo, ma solo può essere causato dalla presenza della paura di ritornare al punto iniziale.</p>
<p>Il Re è un personaggio molto particolare, perché si rendevano conto dell'esistenza del reggicidio. C'era troppa affinità tra il Re e la vittima sacrificale. La più importante analisi sulla questione è quella di Frazer nel <b>Ramo d'oro</b>. Frazer riporta un'antica usanza romana.</p>
<p>Presso gli antichi romani c'era un'istituzione che, anche se non centrale, è durata tantissimo (per quasi tutto  l'impero). Per descriverla usiamo le parole di Frazer: <i>"In questo bosco sacro cresceva un'albero, intorno a cui in ogni momento del giorno si aggirava una truce figura. Quest'uomo era un Re, e un omicida. [...] Un'aspirante sacerdote poteva diventare sacerdote solo uccedendo il precedente."</i>. Quest'usanza mette assieme tre figure:</p>
<ul>
<li>Assassino/Vittima
<li>Sacerdote
<li>Re
</ul>
<p>Frazer formula più di una spiegazione per quest'usanza. Freud pensa che quest'usanza si può capire grazie alla teoria del sacrificio. Cosa simboleggia colui che viene ucciso? Il padre. Allo stesso tempo il padre è il dio a nome del quale il sacrificio viene compiuto. Possiamo supporre che tra l'assassino del sacerdote e il sacerdote stesso, non sia altroche una limpida espressione del fatto che il Dio è prima qualcuno contro il quale si opera in modo violento. Si può diventare Dio solo se prima si viene ucciso.</p>
<p>frazer elabora una teoria: Il re nasce dalla figura del prigioniero di guerra che deve essere sarificato. I primi Re erano prigionieri che godevano di largo prestigio perchè su di loro potevano essere rovesciati tutti i problemi della comunità stessa. Il Re è "tu sei un escremento, tu sei la nostra salvezza, tu sei venuto per ucciderci, tu sei il nostro salvatore". Il Re viene usato come Caprio Espriatorio della società e che poi viene ritualmente messo a morte. Il Re è tale soltanto nella misura in cui si sa che verrà ucciso sistematicamente.  Al Re che regna si distacca un Governatore che governa.  In questa seconda figura noi abbiamo l'antenato dei Re moderni. Anche essi mantengono dei tratti del primo Re.</p>
<p>L'esaltazione del Re e contemporaneamente l'ucciderlo, sono esattamente le due azioni che portano l'omicio che poi creererà la comunità dei figli.</p>
<p>Freud non sa affermare quando le <b>divinità femminili</b> si sono create.. Però afferma che le divinità femminili sono spesso accompagnate da animali che sono i loro protettori/vendicatori. Secondo Freud questo da una possibile chiave di lettura del problema. La divinità femminile finisce per fondare la sua temibilità su figure maschili. L'omicidio, cioè l'atto religioso per eccellenza, viene sempre compiuto dagli animali (quindi maschi).</p>
<p>Le <b>religioni del figlio</b> sono più di una: quella Cristiana, quella di Mitra. La sua analisi di Cristo è: se Cristo libera gli uomini dal peso del Peccato Originale, è evidente che il Peccato Originale fosse stata un'uccisione, per la legge del taglione. La salvezza che porta la riconciliazione con il padre, si parla dell'uccisione del padre. Come nelle costruzioni nevrotiche, il Peccato Originale, nella Bibbia è trasposto, ma questa trasposizione da luogo a delle incoerenze che sono la manifestazione che il contenuto di questi miti è stato sottoposto a un lavoro simil-onirico. La riconciliazione con il padre (la morte in croce) è ancora più forte perchè Gesù rifiuta completamente alla donna. Cristo per il senso di colpa accetta una morte ignominosa per espiare il delitto, ma ha anche il sentimento di fierezza per aver ucciso il padre. Questo comporta che il figlio si affianca al padre o, addirittura, lo sostituisce. La comunione Cristiana è un pasto Totemico 'aggiornato' rappresenta un'eliminazione del padre, ma dove il padre è - in realtà - Gesù. Il fatto che i comandamenti di fratellanza, ci fa capire che il cristianesimo sono accentuati i temi della solidarietà tra fratelli, fondata sulla complicità in un omicidio.</p>
<p>La <b>tragedia</b> è una tendenziosa ripetizione dell'evento primordiale. Quello che è successo la prima volta è riportato in modo infedele. Lo svisamento è che il coro (la banda dei fratelli) fa soffrire l'eroe, ma lo consiglia etc. Un'orda di persone che circonda una persona sola che deve soffrire, siamo in uan situazione di linciaggio. La raffinata ipocrisia consiste nel togliere al coro la sua violenza, facendone un'adunata di persone che commentano con simpatia. A questo punto non si capisce perchè l'eroe soffre. Allora la tragedia giustifica questo creando un passato di errori all'eroe spesso involontari. Esattamente come la vittima sacrificale, gli si addossa tutte le colpe, e dopo averlo ucciso lo si ringrazia.</p>
<?php t3("9.1.2", "Note Finali"); ?>
<p>Perchè io dovrei nascere con un senso di colpa così vecchio? Come si spiega il suo passaggio di generazione in generazione? La risposta di Freud è che in realtà non esiste un inconscio collettivo o ereditario, ma "nessuna generazione è in grado di nascondere alla successiva piuttosto importanti". Secondo Freud questi contenuti pscichici vengono trasmessi da un uomo all'altro in modo inconscio.</p>
<p>Se una religione sparisce, spariscono anche tutte le parti? No perchè alcune parti rimangono tramite trasmissione inconsapevole di detrrminate disposizioni psichiche. Il problema della continuità della cultura è uno dei problemi più difficili da spiegare.</p>
<p>Esiste anche un divenire storico che Freud non nega. La varietà delle vicende umane è un fatto inspiegabile, come per Darwin le variazioni all'interno degli esseri viventi sono inspiegabili. Freud legge la storia in termini evoluzionistici.</p>
<p>In un dato momento, in vari posti della Terra, ci sono vari 'tentativi', che alcuni sopravviveranno, mentre altre spariranno. Quelle varietà che erano contrarie alle esigenze del gruppo sono sparite. Quello che chiamiamo <b>Progresso Storico</b> è da spiegare non come una tendenza verso qualcosa, ma come una sopravvivenza di quelle variazioni positive.</p>
<p>Qualcuno potrebbe chiedersi: "Se effettivamente nella vita psichica non contano gli eventi realmente avvenuti, ma gli impulsi, perchè Freud afferma che all'origine di tutto c'è una <u>reale</u> uccisione del padre?" Freud afferma che è vero che nel caso del nevrotico la fantasia conta quanto la realtà, mentre nel bambino non è esattamente così. Il bambino cerca di mettere in atto le sue fantasie, con i suoi mezzi. Se il paragone tra bambini e selvaggi è vera, l'inibizione all'azione (la debolezza del bambino) non sarebbe stata presente per i selvaggi. Il nevrotico è l'unico che rimane inibito all'azione. È nel nevrotico che c'è una prevalenza del pensiero sull'azione. I bambini e i primitivi non soffrono perchè hanno un primato dell'azione. Nella passività del nevrotico, risiede la sua sofferenza.</p>
<p>Nell'adulto non nevrotico, le pulsioni originarie vengono spostati verso oggetti compatibili con il principio di realtà, mentre per il nevrotico non fa conciliare le sue pulsioni con il principio di realtà. Nel nevrotico non c'è la modificazione della pulsione ma ha semplicemente inibito le pulsioni. E questo fa soffrire la persona.</p>
<p>Freud è fortemente determinismo nel senso che in certe circostanze l'io non può che evolgersi in un dato modo. Freud nega la libertà del volere, perchè se esistesse il libero arbitrio, non si potrbbe fare scienza, ma soltanto quelle cose mosse da meccanismi si può capire e studiare.</p>
<p>In un certo senso, i padri possono essere di varia natura, perchè si parla di una forma di sviluppo costante?In realtà Freud pensa che dietro un'educazione più liberale, le vecchie forme di controllo dell'adulto sul bambino abbiano cambiato aspetto ma non sostanza. C'è qualcosa nella struttura padre-figlio che è costante, che assume varie forme nelle varie società ma non cambiano a livello profondissimo.</p>
<?php t2("9.2", "Al di là del Principio di Piacere"); ?>
<?php t3("9.2.1", "Introduzione"); ?>
<p>L'argomento è più semplice di Totem e tabù. L'opera  del '20 e prova a rispondere a un'unica domanda. Tra il '13 e il '20 c'è la prima guerra mondiale, e il pessimismo di Freud in questo llibro è anche causato dalla guerra. In questo libro nomina anche i "traumi di guerra". Questi sono uno dei punti importanti del discorso, perchè questo sembra dimostrare che negli uomini che sono stati sottoposti a uno shock, sono costretti a rivivere molte volte quel momento drammatico.</p>
<p>Va sfatato il mito che vuole che questo libro viene scritto sull'onda emotiva della morte della figlia preferita, poichè la teoria del libro è stata scritta prima dell'improvvisa morte della figlia. Nonostante questo, la figlia appare nel libro.</p>
<p>La domanda che si pone è: "È proprio certo che la vita psichica umana sia tutta rivolta a conseguire il massimo del piacere possibile? Oppure nella psiche umana esistono anche delle forze che tendono alla morte?". Il titolo dell'opera fa chiaramente capire che si sta provando ad affacciarsi sulle forze che tendono alla morte. C'è da presupporre una forza masochista o si può ricondurre a una diversa modulazione del principio del piacere?Fino a prima, anche la sofferenza del malato psichico, veniva visto come 'male minore'. Al di la del principio del piacere arriva ad affermare che esistono le pulsioni di morte.</p>

<?php t("10", "07/03/2011"); ?>
<?php t2("10.1", "Al di là del Principio di Piacere"); ?>
<?php t3("10.1.1", "Introduzione"); ?>
<p>Empetocle suggeriva che odio e amore sono due forze che si contrappongono. Freud fino al '20 postula che tutti i processi psichici sono governati dal principio del piacere. Questa è una teoria meta-psicologica, cioè una spiegazione in termini scientifici dell'intero comportamento umano. Freud vuole tenersi in ambito scientifico, e prova sempre a dar spiegazione ai concetti stessi con cui si da spiegazione. L'opera non diventa mai una cosmologia, ma rimane nelle mere interpretazioni che lo pcisoanalista può fare nel suo lavoro. La psicanalisi è un paradigma, ma ci sono degli aspetti che sembrano costituire dei problemi di contraddizioni con il paradigma stesso. La spiegazione unitaria (principio del piacere) sembra avere dei problemi. Bisogna analizzarle una alla volta per vedere se l'attuale paradigma sia corretto o meno. Nella seconda parte della produzione di Freud, viene ammesso il principio di morte. Poichè la prima teoria si basava su forti basi, moltissimo lavoro viene reciclato.</p>
<p>Quali sono le anomalie che portano Freud a questo libro? In molti sogni il soggetto sperimenta situazioni dolorissime che lo fanno soffrire in modo difficile da spiegare se si considera solo il principio del piacere. Inoltre ci sono anche le nevrosi di guerra.</p>
<p>Altre se ne aggiungono poi. Ad esempio: durante la cura psicanalitica, quando il paziente trova gli aspetti che lo hanno traumatizzato, al posto che ricordarli in maniera distaccata, rivive l'esperienza stando peggio. Questo tipo di ricordi traumatici costituiscono spesso uno dei motivi per cui il paziente abbandona la cura. In questo momento, ci si può chiedere se una parte della psiche stia lavorando contrariamente. (Trauma da transfert).</p>
<p>Alcuni giochi infantili tendono ad essere ripetizioni di una situazione di sofferenza.</p>
<p>Coazione a ripetere. Costrizione a ritornare sulla situazione dolore che sembra essere una stupida ostinazione a rivivere costantemente l'evento doloroso. Prima Freud prova a correggere la teoria.</p>
<p>Nel primo capitolo ci spiega che si può supporre che il dolore provato serva a garantire più piacere nel futuro. Per far questo bisogna spiegare cos'è il piacere e il dispiacere.</p>
<p>Il <b>dispiacere</b> deve essere consderato come un'allontanamento dallo stato di stabilità emotiva. Proviamo dispiacere quando in noi appare una pulsione molto forte che crea uno squilibrio nell'organismo. Una spinta verso una situazione diversa, una forza che preme per essere soddisfatta.</p>
<p>Il <b>piacere</b> è il risultato dell'operazione con la quale l'organismo annulla l'eccitazione prodotta da una pulsione (stato di eccitazione). Il piacere è un tentativo di rimanere nello stesso stato (principio di staticità).</p>
<p>Se spieghiamo il principio di piacere come principio di costanza, possiamo spiegarci facilmente come alcune azioni non piacevoli lo possano diventare. Esistono forze libere che spingono direttamente verso il proprio piacere e forze legate. L'organismo umano ha la possibilità di differire il soddisfacimento immadeiato di alcune pulsioni a fronte di garantirne un migliore soddisfacimento in seguito. Es: Se ho fame e mangio la prima cosa che capita in mano. Questo peggiora la situazione perchè potri cercare di mangiare qualcosa di non commestibile se non di tossico. Il principio di realtà ci insegna a legare certe pulsioni (cioè il loro soddisfacimento deve essere differito). Il 'sacrificio' legato al principio di realtà è doloroso, ma questo non è in contrasto con il principio del piacere. Anzichè il piacere immediato, si cerca un piacre più duraturo. Il principio di realtà è al servizio del principio del piacere.</p>
<p>Ci sono delle pulsioni che tornano in superficie e provocano doloro. Dopo aver rimosso un desiderio (es desiderio sessuale verso la madre), quando ci si sente rinascere il desiderio si soffre. Freud afferma che il desiderio provoca dolore a una parte dell'apparato psichico (solo l'io cosciente), ma tutto il resto del cervelllo ne deriva un piacere da questo desiderio. Il dolore può soddisfare un'altra parte dell'aparato psichico (incoscio). Questo non è sufficiente a dire che uqlacosa al di sopra del principio del piacere domina la nostra vita. Freud ragiona per iscritto, è un opera in divenire.</p>
<p>Le nevrosi traumatiche possono essere apparentemente spiegate secondo il principio del piacere. Freud le divide in: paura, spavento, angoscia. La paura ha sempre un oggetto ben definito, lo spavento è una situazione di sorpresa di fronte a un pericolo a cui non eravamo preparati, l'angoscia è l'attesa di un pericolo. Se supponiamo che il trauma sia il risultato di un pericolo a cui non eravamo preparati. Come possiamo interpretare l'angoscia dei sogni? Provare nel sogno l'evento traumatico ha la funzione di poter agire retrospettvivamente per potersi aspettare quello che è successo. Una abreazione: un reagire restrospettivamente a un truma. Freud riconosce che ci fa stare molto peggio che non fare sogni normali, quindi questo soogno non rimette in equilibrio l'eccitazione.</p>
<p>Il caso sul quale Freud insiste di più è quello del gioco dei bambini. Freud osserva che suo nipote, non precoce da un punto di vista itellettuale, e tutti lodavano il suo buon carattere (accettava il distacco dai genitori notturno, e anche quando la madre si doveva allontanare, il bambino non andava in escandescenza). Aveva una fastidiosa abitudine di scagliare piccoli oggetti negli angoli. Facendo questo diceva 'o-o-o'. La parola che sembra che il bambino volesse dire è <i>fort</i> (cioè via, lontano, in tedesco). Questo fa immaginare che il bambino volesse far sparire quegli oggetti. Questa interpretazione viene confermata da un'altra osservazione. Il bambino ha in mano un rocchetto con attaccato lo spago. Lanciava il rocchetto tenendo lo spago e diceva 'o-o-o' e poi lo riprendeva dicendo <i>da</i> (eccolo). L'intero gioco era 'faccio sparire' e 'faccio tornare'.  Secondo Freud questo era legato all'alto grado culturale raggiunto dal bambino. Il bambino stava imparando a fare i conti (o differire) le proprie pulsioni. Il gioco era una ripetizione della scomparsa della madre e del suo ritorno. La vita glli aveva imposto che la madre se ne andasse e di aspettare il suo ritorno, nel gioco, il bambino, anzichè subire l'abbandono, si rendeva l'attore. Si trasformava il suo gioco, anzichè essere una dolorosa imposizione dall'esterno, ma una sua scelta, cioè ab-reagendo. Questa ab-reazione è per Freud, sin dagli studi sull'isteria. Quando subiamo un trauma possiamo reagire in modi diversi: si può reagire, tenerselo dentro, etc. Le reazioni differite (quando l'individuo tiene dentro) sono quelle che rischiano di far nascere l'isteria. Perchè soffriamo quando qualcuo ci tratta male o se ne va? Quando qualcuno fa così, siamo presi da una frenesia di far qualcosa. Se questo non succede, di solito, sono le persone che soffrono più a lungo. È come se gli atti motori servissero a far qualcosa. Soffriamo perchè siamo passivi, siamo ridotti al rango di cosa. È la passività che ci fa soffrire. È come se ci offendessimo perchè la nostra energia psichica viene 'gelata. Chi si vendica sta provando a tornare attivo. Se l'organismo non riesce a tornare ad essere attivo, il trauma non si cicatrizza e può produrre l'isteria. Già Aristotele si era reso conto che era la passività a far star malle l'insultato. Aristotele affermava che colui che sta fermo viene poi visto come bersaglio fermo per qualsiasi cosa. L'ab-reazione catartica è un modo per purificare (espiare, espellere) da se cio che è negativo, agendo retrospettivamente.</p>
<p>Il piccolo Erst (nipote di Freud) successsivamente (dopo che suo padre è andato al fronte), nei momenti di rabbia prendeva i giocattoli e gli diceva 'vai al fronte'. Il bambino, ancora, si metteva in situazione di azione e non su subire l'azione.</p>
<p>Cosa fa il bambino quando deve fare una visita 'traumatica'? Rivive in senso attivo l'evento (magari sul fratellino) facendo finta di fargli una puntura etc.</p>
<p>L'infelicità deriva solo da una causa: il fatto che il bambino prova dei desideri sessuali che non possono essere appagati in quel momento. Per natura proviamo desideri che per natura o per l'organizzazione della società non possono essere appagati. Questo è il punto di origine di tutte le nevrosi. Il bambino, nel cercare appagamenti sostitutivi, sposta la sua libido su altri oggetti. È costretto a trovare forme simboliche di appagamento. Il bambino inizia a padroneggiare la realtà per cercare un piacere alternativo. Freud vede questo come inizio della cultura.</p>
<p>Il gioco del rocchetto è, nella sua dolorosità, la nascita di una capacità simbolica, la nascita dell'umano nel senso ordinario del termine. Il bambino cercando un'oggetto sostitutivo e diventando artefice della situazione stessa, il bambino inventa il simbolo, la sua razionalità. Diventa quell'essere simbolico che prima non è. Questo è il primo momento in cui il rocchetto non è più il rocchetto, ma è la madre. Se siamo capaci di intendere quello che gli altri vogliono dire è perchè noi ci abituiamo a sostiuire una cosa con un'altra. Il bambino fa provare al rocchetto dolore, proietta sul rocchetto una persona e di conseguenza l'anima. Questo è l'inizio della religione.</p>
<p>Il bambino non farebbe il gioco del rocchetto, se non avesse un'ambivalenza emotiva verso la madre.</p>
<p>Freud ci insegna a ricondurre le nostre sensazioni da adulti alle sensazioni del bambino. Freud lo fa notare in una nota tristissima: "A 5 anni e 9 mesi il bambino perse la madre. Questa volta che la madre era davvero andata via, il piccolo non mostrò il minimo senso di dolore". Il bambino aveva sviluppato la capacità culturale di padroneggiare il senso dell'abbandono. Il bambino cominciò a diventare geloso del fratellino nato da poco. Lui trasferisce la sua sofferenza verso il fratello sotto forma di gelosia. L'energia che riusciamo a togliere da una cosa (morte della madre) la riversiamo da qualche altra parte. Le energie tolte alle soffereze, si tende a riversarle in modo negativo su altri. Le forze che agiscono nella psiche hanno un + e un - (economico, quantitvio). Le forze prodotte da un'abbandono sono un capitale di negatività e si tende a scaricarle in modo attivo (come soggetto di un'azione). Cultura è spostamento della libido da un'oggetto all'altro. Questo spostamento può diventare sadico, geloso, o sublimato. Come nel bilancio di un'azienda, i calcoli devono tornare (tanto - => tanto +). La vendetta è un esempio perfetto di un'ab-reazione catartica.</p>
<p>L'azione dell'offesa è diversa dalla natura del complimento/amore nel fatto che nel primo caso la persona che viene offessa si trova ad essere cosa-izzata (resa un oggetto) si sente il bisogno di far vedere che si esiste.</p>
<p>La direzione che sembra prendere il discorso è che il bambino nel ripetere il gioco prova piacere perchè gestisce. Freud dice che il gioco del bambino contiene un'elemento di coazione a ripere. Anche se ha uno sbocco positivo per rendersi cosciente dell'azione. Il bambino è come se fosse nevroticamente fissato a ripetere la parte negativa del gioco (il <i>fort</i> è più frequente del <i>da</i>). Perchè la parte violetnta del gioco/spettacolo (horror, tragedie..) è ricercata più che il piacere? Allora la coazione a ripetere deve essere qualcosa di originale.</p>

<?php t("11", "08/03/2011"); ?>
<?php t2("11.1", "Al di la del Principio di Piacere"); ?>
<p>Freud è attentissimo a proclamare la sua prudenza nell'esporre le sue idee in questo libro. Se leggiamo "L'Io e L'es" la toria delle pulsioni di morte, è una teoria che accoglie nel suo pensiero. Weis (psicanalista Italiano) inventa la parola <i>destrudon</i> che è l'opposto di <i>libido</i>. Il concetto di pulsioni di morte è quello più criticato dagli stessi seguaci di Freud. Questa teoria, infatti è meta-psicologica.</p>
<p>Dove trova Freud una prova dell'esistenza delle pulsioni di morte? Tutti gli esempi finora portati, sono spiegabili anche con il principio del piacere. Non c'è un'evidenza psicanalitica dell'esistenza del principio di morte, ma Freud spiega che essa non è mai presente da sola, quindi è inutile cercarla. Il fenomeno che spiega di più questo è la <i>nevrosi da transfert</i>. Durante la terapia, il paziente finisce per far emergere alcuni contenuti rimossi e anzichè essere ricordata (vissuta come qualcosa che apppartiene al passato) viene rivissuta (vissutta come qualcosa che appartiene al presente). È come se l'analista fosse il sostituto del padre/madre (soggetto del dolore). L'energia psichica che emerge da quei contenuti non è razionalizzata, ma è libera e tende all'spressione diretta. Il paziente li rivive con lo stesso grado di dolore e sofferenza con cui lo aveva vissuto quando era bambino. Freud afferma che la coazione a ripetere certamente non è completamente contro il principio del piacere, perchè quello che è spiacevole per il conscio, non lo è per il subconscio. Freud ritiene questa spiegazione molto debole. Questo perchè molti casi riportano situazioni che erano negative già in primo luogo. In questo caso, non può essere positivo per nessuna parte del cervello.</p>
<p><i>(p36/37)</i>. Si crea una ferita indelebile nell'autostima che si crea quando la . Se riemerge nella coscienza durante l'analisi, non può certo fornire piacere, come non l'ha mai creato. Siamo di fronte a qualcosa di <i>demoniaco</i>. Si rifà al motto "errare è umano, perserverare è diabolico". Questo è un perseverare in qualcosa che ci ha già deluso. La persona che ripete è come se fosse posseduta da uno spirito che la porta a rifare sempre gli stessi errori.</p>
<p>Da qui, ne deriva le <b>sindromi da destino</b>. Alcuni individui sembrano perseguitate da qualche destino, ma la psicoanalisi dice che è la persona stessa che se lo crea. (p39). Es: tutte le volte che scelgono una donna, ne scelgono una che non gli darà la felicità, e tutte le donne sono 'simili'. Secondo Freud questo non è un fallimento del principio del piacere, ma è la coazione a ripetere. L'obbiettivo è tramite la comprensione del meccanismo, di riuscire ad uscirne.</p>
<p>Al di sotto della maaggior parte delle persone che sembrano 'colpite' dal destino, c'è una ricerca del destino stesso.</p>
<p>La scelta è legata ad una connessione tra il piacere e un certo tipo di relazione psichica che si è creato da bambini. Il desiderio sessuale, quindi, viene collegato a quel comportamento e, in assenza del comportamento, non si presenta il desiderio sessuale.</p>
<p>La coazione a ripetere sembra più originario del principio del piacere. Bisogna sempre ricordare che queste pulsioni non si trovano mai da sole, ma sempre assieme. La vita sembra essere contemporaneamente:</p>
<ul>
<li>continuare a vivere
<li>avvicinamento alla morte
</ul>
<p>Nel momento stesso in cui una persona continua a vivere, si avvicina alla morte. In ogni azione della nostra vita, possiamo vedere all'opera un'allungamento di una nostra vita e un'accorciamento di quello che ci resta. C'è un equilibrio tra queste due forze. Nessuna delle due si presenta mai in modo puro.</p>
<p>La coazione a ripetere non potrebbee essere letto come un desiderio di riscatto? Coloro che hanno criticato Freud ritengono che questo sia giusto, mentre Freud non pensa che questo sia vero. Freud pensa che il nostro conscio si 'prende in giro da solo', mentre l'inconscio non si prende in giro ma che può essere votato all'auto-distruzione.</p>
<p>La produzione dell'insconscio (sogno) può rivelare una chiarezza che nella vita vigile non riusciamo ad avere. Tutto quello che l'illudersi, il consolarsi etc appartiene ad una sfera moltoo superficiale dell'Io. Freud dimostra questo mostrando che il sogno riveli delle cose che poi, durante la veglia, ci neghiamo. Le nevrosi da destino sembrano proprio provare l'esistenza della coazione a ripetere.</p>
<p>I capitoli 4 e 5 (complicati, e andremo veloci perchè poco utili) sono sulle conoscenze neurologiche (oggi superate). La cosa interessante è che le sue conclusioni sono ancora sostenibili. Freud, nel capitolo 4, cerca di spiegare cosa succede quando un sistema psichico viene investito da una podero sascarica (luce fortissima, rumore fortissimo, ...). Alcuni meccanismi evolutivi hanno portato la corteccia celebrare a sviluppare dei sistemi di protezione. Si rivela un'assimmetria. Noi abbiamo sviluppato con i 5 sensi, la capacità di regolare gli impulsi esterni (chiusura degli occhi). La corteccia celebrale è in grado di proteggersi da stimoli sensoriali troppo forti, ma non ha un'adeguata protezione verso gli stimoli endo-psichici. Noi siamo meglio protetti dai fenomeni eso-psichici che non dagli endo-psichici. Questo comporta una situazione di malessere (o disagio) che l'individuotende a proiettarne la causa all'esterno. (p49) Le energie psichiche vengono spostate da una porta della percezione verso quella in cui ci sono stati dolori. Freud parla spesso di energia psichica come se fossero soldi (la si sposta, man on si crea e non si distrugge). L'attività primaria dell'organismo sembra che sia padroneggiare, ossia legare, le eccitazioni non tenendo conto del principio del piacere. Le energie slegate (che tendono ad essere soddisfatte subito) devono essere legate per non creare scompensi nell'organismo.</p>
<p>Ci sono delle pulsioni che non possono (e non devono) essere costretti, come ad esempio il bisogno di respirare. Ma sono pochissime le pulsioni così. Anche le pulsioni fisiologiche di base (mangiare, bere, ...) vengono legate. Esiste l'attività di padroneggiare le eccitazioni. Come possiamo chiamare questa funzione psichica che precede il principio del piacere? È come se dentro di noi esistessero delle pulsioni che tengono ad inibire qualsiasi forma di eccitazione. È come se dentro di noi, più originarie delle pulsioni a raggiungere il piacere, ci fossero delle pulsioni a legare/limitare/smussare il piacere. Di fronte alle esperienze a provare piacere, c'è una tendenza più antica a non provare nulla, o permanere nello stesso stato. Essendo noi sempre spinti dalle pulsioni, questa è una forza che ci riporti alla situazione iniziale. Freud ritiene che è intrinseco nella vita (cellulare) l'essere inerte (cioè tendere a stare nello stato in cui si trova). Più che desiderare il soddisfacimento di un piacere, la vita sembra interessata a mantenere il suo stato precedente (<i>status quo</i>). Ma cosa é ogni parte dellaa materia prima di essere vita? Prima di tutto è materia organica, allora se ogni essere prima di essere vivo è inorganico, allora la tendenza fondamentale a ogni essere, è quella di regredire allo stadio di non-vita (cioè la morte). "La meta di ogni essere vivente è lla morte". Nella costituzione tipica dell'uomo vi sia un'inconscia aspirazione a tornare all'immobilità dell'inorgarnico.</p>
<p>Freud afferma che non possiamo che tutte le pulsioni abbiano come scopo l'inerzia del vivente. Prima Freud postulava solo il principio di vita, ora solo di morte. Adesso afferma che dobbiamo vedere tutte le pulsioni assieme. Ci sono pulsioni aggreganti (erotiche) e desgreganti. Un gruppo di  pulsioni cerca di raggiungere il più velocemente la morte, mentre l'altro gruppo cerca di raggiungerlo più lentamente. Se prima Freud aveva postulato che esistono delle pulsioni sessuali che si oppongono a quelle dell'io. Ora le pulsioni sessuali vengono modificate e si contrappongono non al principio di realtà, ma al princcipio della dissoluzione.  Adesso abbiamo pulsioni di vita contrapposte a pulsioni di morte.</p>

<?php t("12", "14/03/2011"); ?>
<?php t2("12.1", "Introduzione generica"); ?>
<p>Quando Freud parla di pulsioni parla di pulsioni 'naturali' che avrebbe anche un bambino cresciuto in isolamento in una foresta. Allora da dove arrivano? Dal corpo: sono quello che la psiche procude in conseguenza dei cambiamenti di stato dei tessuti corpori. L'origine è, quindi, somatica. Gli uomini hanno simili pulsioni perchè hanno simili corpi. In Freud l'individuo resta l'ultimo stato del discorso. Al di sotto dell'individuo non si possono trovare forze più semplici. Freud non mette in crisi la nozione di individuo. Freud sente il bisogno di escludere che Ernst abbia inventato quel gioco per imitazione di qualche azione. Questo gioco è nato all'interno del bambino, indipendentemente dall'ambiente. Abbiamo una delineazione di una natura/essenza umana che entra in contatto con l'esterno, pur mantenendo una sua definizione.</p>
<p>Chi si è occupato di masse prima di Freud, avevano insistito sul fatto che gli uomini, nella massa, si suggestionano gli uni con gli altri. Sembra essere uno spunto molto promettente. Freud respinge questo nettamente perchè per lui, le nostre azioni scaturiscono innanzi tutto dall'interno dell'individuo stesso. Freud deve respingere, perchè se no lo psichico non può più nascere dal somatico. Secondo Freud, si copia il comportamento perchè c'è una tendenza interna a qualcosa, come l'ammissione sociale. In ultima istanza, è sempre la mia individuità che decide cosa fare. Spinoza pensa che il bambino non abbia nessuna esperienza di quello che è il mondo e quindi può essere plasmato in ogni modo. Per Spinoza quello che chiamiamo individuo si configura sulla base dei primi scontri. Un individuo è un equilibrio di forze.</p>
<p>Freud ha una forte ragione di tenere la sua idea perchè considera che il corpo influenza le azioni. Perchè non hanno sviluppato una terapia su base corporea? Da dopo Freud moltissimi ci hanno provato, ma Freud vedeva un'ostacolo insuperabile, perchè il posto tra corpo e mente è irraggiungibile, se non quello simbolico linguistico.</p>
<p>Freud si era reso conto che la suggestione era una forza estremamente grande al momento, ma la suggestione è di breve durata perchè non scende nel profondo. Tutto quello che apprendiamo da un'altro e imitiamo (suggestione) non scende nel profondo dell'essere. Freud tende sempre a tornare a una visione deterministica. La concezione relazionale porta a pensare che se io sono quel che sono in base ai miei incontri, allora qualuncuo sia l'latro essere umano, non è particolarmente importnate. Se i primi individui non fossero genitori, ma altri che si prendono cura di lui è uguale. Freud, in realtà, egli sembra affermare che dall'interno esista una tendenza ad amare i propri genitori biologici.</p>
<p>Freud pensa che anche nel caso dell'omosessualità, questa è originale e non derivata dalle frustrazionei di relazioni mal andate.</p>
<p>La psicanalisi Freudiana è stata fortemente contaminata da elementi sociologici.</p>
<p>L'anima della massa, per Freud, non è accettabile, perchè l'individuo rimane l'atomo di cui si compone anche una massa o una docietà.</p>
<p>La componente platonica del discorso Freudiano va verso una similitudine degli esseri, ma rimane il fatto che ogni ingolo individuo è già completo e che questa individualità non nasce col tempo.</p>
<p>Freud nel '15 afferma che noi uomini che apparteniamo alle società ricche, abbiamo messo su una maschera e la guerra ha strappato la maschera. La guerra ha mostrato che al di sotto delle buone maniere e delle leggi sempre più civili, le pulsioni sono sempre le stesse. La civiltà è uno stato di vernice sottilissimo che si toglie al bisogno.</p>
<?php t2("12.2", "La teoria delle pulsioni di Freud"); ?>
<p>Nel capitolo 6 afferma che le pulsioni di vita e di morte erano già state presupposte da Schopenhour. La teoria delle ppulsioni di vita contrapposte a quelle di morte è una teoria dualistica che prevede uno sfondo coomune: anche le pulsioni di vita che premono per il proseguimento, fanno il gioco delle pulsioni di morte perchè accellerano verso la morte. Le pulsioni di vita sono al servizio alle pulsioni di morte. Una cosa viva necessita continuamente di cose per continuare a vivere. La pulsione di vita è al servizio delle pulsioni di morte perchè fa di tutto per evitare un pericolo, per cercare di morire soltanto per cause 'naturali' (o interne). Il dualismo </p>
<ul>
<li>Tutte le pulsioni hanno carattere regressivo
<p>Il piacere per essere soddisfatto, il modo per soddisfarla è tornare allo stato precedente, al momento in cui la pulsione non c'era.</p>
<li>La coazione a ripete si configura come la vera natura intrinseca di ogni pulsione
<li>Il principio del piacere si conferma come principale, ma deve essere inteso come principio del Nirvana.
<p>La tendenza della vita tende a sopprimere gli stimoli. Vivere in un modo senza stimoli.</p>
</ul>
<p>Se è così, la vita è il male e il bene è non provare stimoli. Questo diventa la prova decisiva per l'esistenza delle pulsioni di morte. Le pulsioni di morte ci vanno direttamente, mentre le pulsioni di vita in modo indiretto. Le pulsioni di vita tendono ad aggregare, quelle di morte a disgregare.</p>
<p>La paura di morire, secondo Freud, non è mai disgiunta da un desiderio di morire e i comportamenti avventati/eroici sono proprio prove di questa ambivalenza. In questa prospettiva la paura di morire deve essere pensata come paura di morire per circostanze esterne. Cioè la paura di essere subita da noi al posto che subita. C'è una tendenza a dominare la propria morte. È la paura di non poter determinare come e quando morire. Anche in un organismo complesso come quello umano ci sarebbe la tendenza di andare verso la morte inscitta all'interno dell'individuo. La morte in quanto tale si configurebbere come una fase accettabile purchè  questo non venga accellerato da circostanze esterne.</p>
<p>In <i>Al di là del Principio del Piacere</i> arriva ad accettare un possibile masochhismo primario, cosa che rifiutò precedentemente. La pulsione distruttiva (sadismo) può rivolgersi anche verso se stessi (masochhismo).</p>
<p>Le pulsioni di vita e di morte sembrano essere la sorgente di amore e odio, ma non è così chiaro questo rapporto. La prima manifestazione dell'odio è il sadismo sessuale ed è qualcosa in contrasto con il soddasficemnto di Eros. Il sadismo non è una forma di sessualità, ma una perversione di essa. Tutta la teoria della sessualità deve essere rivista dopo il fatto che tutto quello che è distruttivo nel bambino non può arrivare da Eros, ma deve arrivare da un'altro principio.</p>
<p>Prima di <i>Al di là del Principio del Piacere</i> c'erano due pulsioni, una che voleva conseguire il piacere subito e l'altra che voleva differirlo. Ora, le pulsioni sessuali e quelle di conservazioni dell'Io sono la stessa cosa. Le prime energia slegata, le seconde imbrigliate, ma sono entrambe fatte per andare avanti.</p>
<p>Le pulsioni di morte finiscono con avere come unico esemplare il sadismo (e il masochismo, sull'oggetto stesso). Costruzione e distruzione hanno la stessa meta finale. La distruzione prova ad arrivare più velocemente alla morte rispetto a quello che farebbero i processi interni, rispettati invece da quello di costruzone.</p>
<p>Le pulsioni di vita fanno un sacco di frastuono, mentre quelle di morte agiscono silenziosamente. La tendenza alla distruzione si presenta più come un tarlo. Si presentano a noi nei fini ultimi e nei sogni. Le pulsioni di morte reggono i fili delle marionette. Tutti i doveri sociali che noi accettiamo è il frutto delle nostre pulsioni di morte. Freud identifica i nostri doveri sociiali come un effetto delle pulsioni di morte. La società è un'istanza che chiede a noi di rinunciare le pulsioni di vita e che ci spinge verso la morte. Tutto quello che è imposto dalla società non avrebbe nessun effetto su di noi se non potesse giocare sulle nostre pulsioni interne di morte.</p>

<?php t("13", "15/03/2011"); ?>
<?php t2("13.1", "Programma"); ?>
<ul>
<li>Totem e Tabu (1913)
<li>Al di là del Principio del Piacere (1920)
<li>3 opere brevi
<li>Il Disagio della Società (1928)
<li>Psicologia delle Masse
<li>L'avvenire della disillusione
<li>
<li>L'uomo Mosè
</ul>
<?php t2("13.2", "1908 - "); ?>
<p>Freud tiene assieme il movimento psicanalitico ponendosi nella parte più estremistica del movimento, e non in quella conciliante.</p>
<p>Nervosismo nel senso di frequenza di nevrosi. Freud ne parla come se l'avanzare della civiltà fa aumentare la frequenza delle nevrosi.</p>
<p>La morale dice che l'unica sessualità accettabile è quella matrimoniale. Ma le scappatelle dell'uomo sono ok, quelle della donna meno. La consolidità della società è intrinsicamente minata da questa doppia moralità. Se la nostra società è più ricca di nervosismo delle società del passato, la colpa non è del fatto che le regole non sono più rispettate, ma del fatto che le regole sono fin troppo rispettate e che la morale sessuale è troppo repressiva e non compatibile con le pulsioni dell'individuo. Inoltre Freud afferma che non è vero che l'epoca moderna sia caratterizzata da decadenza e non pensa che le nevrosi siano aumentate, semplicemente ora si conoscono.</p>
<p>Qual'è leffetto che hanno le regole sociali sulla psiche dell'individuo? In fondo la teoria definitiva di Freud dice che quello che la civiltà chiede all'uomo è una rinuncia delle pulsioni di vita, cioè far trionfare le forze di morte. In questo momento Freud considera che ci siano pulsioni sessuali e pulsioni di conservazione. (p16)</p>
<p>Le rinuncie che la società ci chiede servono per poter vivere insicurezza (idea Hobbsiana). Inoltre le rinuncie sono annche fatte per una corrente pulsionale che ci spinge a proteggere verso qualcuno con cui proviamo affetto e la rinuncia all'odio verso di loro. I nostri sentimenti aggressivi e erotici vengono rimossi in famiglia. La famiglia è la palestra della società.</p>
<p>La rinuncia è stata graduale e ogni passo è stato 'assicurato' dalla religione. Chi non rispetta le regole viene espulso (manicomio, prigione,...).</p>
<p>Freud: Cosa succede alle pulsioni represse? Dipende. La cosa migliore sarebbe la sublimazione: scambiare la meta di una pulsione con un'altra meta più accettabile a livello sociale, come far carriere, opere d'arte, etc. Nei casi meno buoni, anzichè essere sublimata, la pulsione viene siffissa.</p>
<p>Freud riconosce agli omosessuali il fatto che è (o è anche) si tratta di una via laterale, perchè è stata impedita la <i>via maestra</i>.</p>
<p>Posto che solo in una piccola parte dei casi le pulsioni sessuali si manifestano in sublimazione e in tutti gli altri casi creano nevrosi, il vantaggio per la società è maggiore degli svantaggi? Quello che la società ottiene reprimendo gli individui è decisamente inferiore al costo pagato. Per pochi individui che hanno sublimato, la quasi totalità del genere umano è andato incontro ad una fine brutta. Un matrimonio 'come società vuole' è la garanzia certa del fallimento del loro matrimonio o il naufragare nella mancanza di felicità. La nevrosi è la via più certa attraverso la quale la donna rimane una donna per bene. L'astinenza sessuale, secondo Freud, forma molto frequentemente dei <i>codardi per bene</i>. L'esigenza di mantenere le donne 'per bene' è ottenuta con una disinformazione. Mentre per gli uomini viene repressa ma in realtà accettata. Sulla cosa delle donne Freud afferma che questo è la causa dell'indubbia minorità intellettuale femminile (p27). Come le religioni chiedono il divieto di pensare. Se per l'uomo le conoscenze 'porta a porta' sessuali sono accompagnate da un po' di orgoglio, nel caso della donna sono accompagnate da un senso di peccato.</p>
<p>Finchè consideremo la felicità individuale come metro del <i>bene</i>, la morale sessuale sarà il male.</p>
<?php t2("13.3", "1914 - Considerazioni attuali sulla guerra e sulla morte"); ?>
<p>Quest'opera arriva dopo ~6 mesi dallo scoppio della guerra. Sono considerazioni, non c'è una tesi unica. La parola chiave è <b>delusione</b>. Freud cerca di rivestire questa parola di un significato positivo. "La guerra ci ha deluso". Non ha mantenuto alle aspettive che avevamo, ma ogni delusione è la fine di un'illusione. La fine di un'illusione è sempre il ritorno a una concezione più fredda, più spassionata delle cose. Si può ringraziare la guerra di averci fatto vedere con chiarezza quello che prima non volevamo vedere. Pensavamo che si fosse creata una cerchia di scienziati cosmopolita. Pensavamo che gli umani avessero perso le zanne. La guerra ci ha mostrato alcune verità. Ad esempio: il diritto all'interno degli stati aveva portato gli uomini a bandire la violenza. Con la guerra viene fuori che lo stato chiede questo solo perchè lo stato vuole essere l'unico ad avere diritto di commettere violenza. Vuole quindi monopolizzare l'ingiustizia, non reprimerla. Lo sstato infrange i patti internazionali perchè 'l'altro potrebbe farlo'. Però lo stato non ammette che i cittadini usino la stessa motivazione.</p>
<p>C'eravamo illusi che noi stessi non fossimo più in grado di commettere certe forme di violenza (addomesticatti). Invece questa metamorfosi è facilissima. Le pulsioni aggressive mirano al soddasficemnto di alcuni bisogni originali. Le forze pulsionali cambiano pochissimo al cambiamento di usi e costumi. Cosa ha fatto la pace? Ha semplicemente trasformato queste pulsioni (teoria della sublimazione). Nell'uomo la trasformazione tra l'immoralità del bambino (non conosce il differimento del piacere) (p43). Non esiste una pulsione alla morale, alla pace o al bene comune, ma sono derivative da istanze esterne interiorizzate. Il bambino le interiorizza perchè ci identifichiamo con (amiamo) la persona che ce le impone.</p>
<p>Le pulsioni sessuali si tramutano in sociali. Una pulsione originariamente egoistica che rivolta sull'altro si trasforma in pulsione sociale. Cosa spiega il repentino cambiamento? Il fatto che basta che la sua società diventi l'esercito, che egli venga istruito patriotticamente perchè egli ri-trasformi le sue pulsioni in quello che erano originariamente. "Può darsi che un certo grado di incivilmento ipocrita sia indispensabile per la conservazione della società". Può essere che l'ipocrisia sia il minore dei mali.</p>
<?php file::footer(); ?>