<?php
require "../class/include.php";

file::head("Storia della Filosofia Morale - Totem e tabù");

toc::show_toc("Storia_della_Filosofia_Morale/Totem_e_tabu.php");
?>

<?php t("0", "Introduzione"); ?>
<p>L'opera <i>Totem e tabù</i> è divisa in quattro saggi.</p>
<p>Le parole "Totem" e "Tabù" derivano entrambe dal gergo dell'antropologia.</p>
<p><b>Totem:</b> progenitore naturale (animale, pianta, elemento naturale) di un clan (stirpe). Concetto tipico di società arcaiche, infatti non presente nella cultura occidentale.</p>
<p><b>Tabù</b>: divieto assoluto. È l'<i>imperativo morale</i> (o delle proibizioni assolute), e rappresenta il concetto negativo del sacro (innominabile).</p>
<p>Il sottotitolo dell'opera è <b>"Alcune concordanze tra la vita dei selvaggi e dei nevrotici"</b>. Freud sostiene che la nascita di questi due concetti possa essere spiegata usando l'analisi della vita dei nevrotici. Freud, infatti, ritiene che la nevrosi, nonostante oggi ci appaia come malattia, sia un residuo degli antichi totem e tabù. Il nevrotico soffre di regressione allo stato infantile, che è lo stesso stato in cui si sono fermati i popoli selvaggi. Tutti siamo nevrotici, chi più chi meno.</p>
<p>Freud più volte usa le espressioni <i>"popoli selvaggi"</i> e <i>"popoli semi-selvaggi"</i> per indicare alcuni popoli con una civiltà inferiore a quella occidentale, ma bisogna considerare che in quel periodo questo era normale, infatti - nello stesso periodo - assistiamo al colonialismo. Freud arriverà a superare, almeno teoricamente, questo preconcetto. Inoltre, le sue conclusioni per la vita dei selvaggi, valgono anche per i popoli europei, quindi - ovviamente - bisogna considerare i selvaggi alla stregua degli europei. Non si può, infatti, tracciare una linea evolutiva per dimostrare che noi siamo più evoluti di loro.</p>
<p>Freud venne molto criticato sia per il gusto della dissacrazione che spesso mostrava, sia perché accusato di aver mostrato gli umani come esseri mossi soltanto dalle pulsioni di piacere.</p>

<?php t("1", "L'orrore dell'incesto"); ?>
<p>Sin dalla fine dell'1800 ci si era posto il problema dell'obbligo dell'esogamia. L'esogamia è, infatti, la mescolanza dei geni con geni esterni. Il suo opposto è l'endogamia, spessa riferitasi come incesto. La definizione di 'gamia', ovviamente non è unica, ma varia al variare della civiltà considerata. Esistono molteplici situazioni sociali, nelle quali viene prescritta l'endogamia, quali: la Germania Hitleriana (ariani vs others), USA fino al 1967 (neri vs bianchi nel sud), Sud Africa (neri vs bianchi). Nonostante questo si obbligavano delle leggi esogamiche, quando  si parlava a livello familiare.</p>
<p><b>Westermarck</b> propone la teoria <i>Effetto Westermarck</i>, la quale suggerisce che individui che nascono e vivono sotto lo stesso tetto, perdono l'interesse sessuale l'uno per l'altro. Questa teoria deduce un divieto da una situazione di disinteresse psicologico, e  questo non spiega l'esistenza di una legge che lo proibisca.</p>
<p><b>Emil Durkheim</b>, Francese di origine ebraica, contemporaneo di Freud che nel 12-13 scrive un'opera sull'analisi della religione anche lui basandosi sugli Aborigeni Australiani. Secondo lui c'è un orrore per il mescolarsi del sangue che colpisce maggiormente la donna (sangue mestruale). Con una donna con la quale si vive, ci sono situazioni in cui si vede il sangue dell'altra persona, creando una situazione di non accettabilità. Questa teoria ha problemi su tutti i fronti, ma per la prima volta inserisce la religione come causa.</p>
<p><b>Spencer</b> propone una teoria che si fonda su: "in un epoca in cui la virtù cavalleresca è il tratto distintivo di un uomo, la capacità di riuscire a prendere una donna di un'altra tribù, è un motivo di prestigio". Questa teoria di Spencer non riesce a spiegare il motivo per cui si obbligano gli uomini ad acquisire prestigio.</p>
<p><b>Lévi-Strauss</b> vede in modo capovolto il problema. Pensa che la regola struttura il sistema sociale, non i divieti. Secondo Lévi-Strauss una buona regola per una società sia quella di entrare in contatto quanto più pacifico con altri clan/famiglie, anche scambiandosi le figlie. Secondo Lévi-Strauss, quindi, questa diventa una regola di "buon vicinato".</p>
<p><b>René Girard</b> (posteriore rispetto a Freud) rimane in una prospettiva Freudiana, considerando che il divieto preceda l'obbligo. Ma è un divieto (non Freudiano) che non verte sulla sorella in quanto cosanguinea, ma il divieto verte sugli oggetti sessuali che essendo troppo vicini, possono creare una rivalità all'interno della famiglia stessa. L'idea è sostanzialmente Freudiana, ma Freud mantiene il tema della parentela, mentre René Girard vede come tema qualsiasi oggetto troppo vicino.</p>
<p>Tutte le precedenti teorie non risolvevano il problema per sei motivi:</p>
<ol>
<li>Come fa notare Frazer, un uomo non ha motivo di proibire a se stesso qualcosa che non farebbe comunque
<li>Non spiegano il motivo per vietare il soddisfacimento sessuale con l'oggetto più a portata di mano (madre, figlia, sorella), anche considerando che gli animali lo fanno senza scrupoli.
<li>Tutte le teorie precedenti ritengono che la morale che proibisce l'incesto si sia sviluppata nel tempo, pian piano. Eppure se si prende il popolo più arretrato (aborigeni australiani) è vietatissimo l'incesto.
<li>Viaggiando si era capito che gli usi riguardanti l'incesto erano i più vari: aborigeni completamente proibito, in altri obbligatorio. Nella famiglia reale egiziana era obbligatorio sposare la sorella. Alcune hanno una contraddizione interna (vietato, ma obbligatorio in una festa).
<li>Qualcuno sosteneva che l'incesto era vietato per evitare malattie genetiche, ma all'epoca non si conosceva il DNA e le malattie genetiche.
<p>Non è chiaro, addirittura, se per gli Aborigeni Australiani ci sia un collegamento tra il rapporto sessuale e la nascita del figlio. La spiegazione che spesso veniva riportata era che la donna rimanesse in cinta il giorno stesso in cui se ne accorgesse. La donna rimaneva in cinta a causa di quel particolare totem che era particolarmente dominante nel posto in cui la donna si trovasse nel momento in cui se ne accorgesse. Quindi è impossibile che l'incesto fosse vietato per motivi di discendenza.</p>
<li>Le tesi diffusioniste non possono essere usate perché le pulsioni della natura umana sono le stesse dappertutto e quindi è normale aspettarci comportamenti simili.
<p>Il diffusionismo è quell'idea che considera che quando una cultura comincia a fare una cosa, gli altri li copiano.  Gli uomini posso non aver sviluppato molti modi diversi, ma solo le usanze "positive" o "neutre" vengono eliminate. Questo spiega il motivo per cui molte usanze sono molto simili.</p>
</ol>
<p>Freud sviluppa una teoria incentrata sul <i>Complesso di Edipo</i>. Secondo Freud, la prima scelta dell'analisi sessuale del bambino è incestuosa. Freud sostiene che la parte cosciente della psiche prova un orrore per l'incesto, mentre la parte incosciente la desidera, facendo notare che la psiche e la coscienza non sono la stessa cosa (modello dell'iceberg). </p>
<p>Freud analizza il sistema Totemico australiano e scopre che è basato su due principi:</p>
<ul>
<li>Divieto di uccidere l'animale/piante a cui si appartiene
<li>Divieto di avere rapporti sessuali con compagni dell'altro sesso che appartengono allo stesso totem
</ul>
<p>Il Totem si può trasmettere per via di madre (matrilineare) o padre (patrilineare), in base alla tribù. Freud considera il sistema originario matrilineare, ma non porta delle giustificazioni per questa sua affermazione. Nel sistema matrilineare, l'incesto vietato è madre-figlio, mentre nel caso patrilineare è vietato l'incesto padre-figlia. Per vietare anche l'incesto non vietato dal sistema totemico, gli aborigeni, hanno creato una serie di classi matrimoniali, per fare in modo che all'individuo siano vietati i rapporti con il ~75% delle donne vicine a lui.</p>
<p>Freud si avvicina al problema affrontato l'argomento dell'<b>avoidances</b>, quell'insieme di usanze che evitano il contatto tra persone vicine. Secondo Freud sono forme attenuanti del divieto dell'incesto. Dietro il divieto dell'incesto, c'è un divieto di un rapporto affettivo tra le due persone. I fenomeni psichici (antipatie..) non hanno mai una causa sola, ma solitamente ne hanno molte, anche se ogni una sarebbe abbastanza per spiegare il fenomeno.</p>
<p>Secondo Freud i <b>rapporti tra generi e suoceri</b> sono difficili poiché quando l'investimento libidico passa da se stessi verso un oggetto esterno, non lo fa direttamente investendo un oggetto completamente esterno, ma su un oggetto vicino, come può essere la madre. Questo è la base del Complesso di Edipo. La presenza materna (della suocera) risveglia il sentimento di affetto per la propria madre che è stato difficilmente sorpassato. Questo comporta un rischio di regressione e quindi deve essere tenuto a distanza.</p>
<p>Freud è spesso accusato di <b>maschilismo</b>, poiché ricopre solo gli uomini dell'intenzione libidica. Parlando, però, del Freud Antropologo, esso, non è così assurdo.</p>
<p>Secondo Freud, possiamo affermare che l'<b>orrore dell'incesto</b> è un tratto "squisitamente infantile", in cui l'individuo non vuole che gli sia ricordato un elemento della vita infantile e che aveva rimosso in una fase precedente della sua vita psichica. Così questa regola è stata fatta per <b>evitare che l'uomo regredisca all'età infantile</b>. Secondo Freud, quando parliamo della creazione di nuove leggi, gli uomini sono spinti dall'affettività e non dalla razionalità, quindi sotto effetto di paure/angosce. Egli ritiene che gli uomini non calcolano quando creano regole, ma sono mossi - come marionette - dalle loro pulsioni, in questo caso, erotiche.</p>

<?php t("2", "Il tabù e l'ambivalenza dei sentimenti"); ?>
<p><b>Tabù</b> è una parola polinesiana che si può tradurre con l'espressione <i>"orrore sacro"</i>, cioè un sentimento di repulsione assoluta per qualcosa che è motivi che non sappiamo e di cui non riusciamo a trovare una giustificazione concreta. L'effetto del Tabù è reale, perché le persone lo rendono tale. Si può infrangere un Tabù senza saperlo, ma questo non fa cambiare la colpevolezza della persona.</p>
<p>La tematica psicoanalitica che è in gioco è il parallelo che c'è tra il tabù e le nevrosi ossessive. Le nevrosi ossessive sono una classe di nevrosi. I nevrosi ossessivi hanno una ossessività nel (non) compiere determinate azioni.</p>
<p>Freud elenca quattro punti di comunanza tra i nevrotici ossessivi e i Tabù</p>
<ol>
<li>Scarsa motivazione delle prescrizioni
<li>Consolidamento attraverso una necessità interiore
<li>Dislocabilità e contagiosità degli oggetti proibiti
<p>Alcuni oggetti e persone hanno un carattere tabù che passano agli oggetti con cui vengono in <b>contatto</b>. Coloro che seppelliscono il morto, diventano tabù. Il contatto anche per l'ossesso è molto pericoloso, infatti non entra in contatto con ceti oggetti.</p>
<li>Se si entra in contatto con qualcosa che è tabù ci sono delle forme di rituale che devono essere eseguiti
</ol>
<p>I tabù possono essere di varie specie</p>
<ul>
<li><b>Temporanei</b>: persone che entrano a contatto col cadavere)
<li><b>Eterni</b>: cadaveri
<li><b>Geografici</b>
<li><b>Trasgressori</b> del tabù.
</ul>
<p>Il tabù si differenzia dalla ossessione per alcuni aspetti</p>
<ul>
<li><b>Conoscenza della causa</b>
<p>Il <b>nevrotico</b> è a conoscenza della causa del tabù, infatti si proibisce il contatto con un'oggetto che aveva dato un grandissimo piacere nella primissima infanzia, ma a questo piacere si contrappone un divieto esterno a toccare queste cose e trova all'interno della psiche trova un rafforzamento. Secondo Freud le proibizioni vengono interiorizzate se arrivano da una figura temuta/amata/odiata, quindi c'è un'ambivalenza affettiva, come il padre. Così facendo si crea un'istanza interna, il <i>Super-Io</i>, cioè l'interiorizzazione del padre. Il conflitto tra desiderio e divieto può spiegare le dinamiche compulsive del nevrotico ossessivo e i tabù. La libido può essere trasformata o spostata, ma non si crea e non si distrugge. L'azione proibita è un'azione che l'inconscio vuole compiere.</p>
<p>Il <b>selvaggio</b> non sa spiegare il motivo per cui una determinata cosa è tabù.</p>
<li><b>* Fonte</b>: il nevrotico si auto-impone il tabù, mentre al selvaggio viene imposto dall'esterno
</ul>
<p>La <b>dislocabilità</b> del tabù, secondo Freud, è riconducibile alla capacità di associazione della nostra psiche. Il motivo del tabù e della nevrosi, è il concetto di contatto (fisico, o tramite nominazione).</p>
Il nevrotico </p>
<p>Freud analizza tre casi di tabù non totemici dei selvaggi:</p>
<ul>
<li>Tabù del sangue dei nemici
<p>Freud vuole dimostrare che le forme di prescrizione che sono imposte ai guerrieri che hanno ucciso dei nemici, sono il risultato di un'ambivalenza emotiva. Poiché è evidente il motivo per cui si giustifica questa azione, bisogna dimostrare che esista la pulsione che ci imponga di trattare i nemici con rispetto. Freud prova a eliminare l'ipotesi più ovvia e comune, che prevedeva la paura degli spiriti dei nemici. Freud sostiene che c'è un'<i>apparente legge di non uccidere</i>. Secondo Freud c'è un'<b>identificazione nel nemico ucciso</b>. Quindi nel provare quel minimo di rispetto e umanità che si prova nelle cerimonie di purificazione, è come se si provasse umanità verso se stessi, quando si verrà uccisi. Il carattere comune di queste purificazioni era la privazione di piaceri ed entrare in contatto con gli altri. L'idea che c'è ma che Freud non espone, è che colui che ha ucciso, ha provato un piacere che potrebbe averlo inebriato e quindi deve liberarsi da questo stato prima di ritornare nella società. Le osservanze che fanno parte di questo tabù, si possono dividere in:</p>
<ul>
<li>Riconciliazione con il nemico ucciso
<li>Limitazioni
<li>Pratiche espiatorie
<li>Pratiche cerimoniali
</ul>
<p>Il tabù in questione è ambivalente perché da un lato c'è la soddisfazione per averli uccisi, e dall'altro il necessario blocco di questi impulsi per tornare alla vita di tutti i giorni. Freud non lo dice in modo esplicito, ma è necessario che quell'atteggiamento aggressivo non contamini i momenti di vita normale. Per far questo ci vuole un momento di "quarantena". Freud non lo spiega in questi termini, ma spiega l'operazione opposta, cioè la necessità per il guerriero che si appresta ad andare in guerra a lasciar cadere tutti i freni inibitori che solitamente ha; esso deve, quindi, fare dei riti per favorire l'emersione dello spirito aggressivo.</p>
<li>Tabù che riguarda la figura del sovrano
<p>Nel caso dei sovrani, tutto è ambivalente. Un esempio è il contatto volontario (da parte del Re) ha effetti molto positivi (es: guarire dalla scrofola), mentre quello involontario può essere fatale. Il contatto con oggetti del Re, essendo un contatto non intenzionale da parte del Re, è egualmente pericoloso. Freud fa notare che questo rapporto ambivalente è tipico del rapporto padre-figlio, poiché il bambino attribuisce a sua padre l'onnipotenza (sia positiva sia negativa). Questa ambivalenza è facilmente capibile se avvicinata a quella paterna, il quale sembra onnipotente e però sbarra la strada verso uno dei voleri del bambino (incesto). L'attribuire a qualcuno un potere immenso (far guarire, e far ammalare) è la conseguenza di un <b>delirio paranoico</b>. Questo non è altro che <i>la proiezione su un'altra persona di quei poteri terribili che il bambino attribuisce al padre</i>.</p>
<p>Una contraddizione molto forte riguardo i sovrani è quella legata alla loro protezione. Al sovrano viene attribuito un grande potere sulle forze  naturali ma, nonostante questo, ci si  ritiene obbligati a proteggerlo. Spesso questa protezione diventa una forma di <b>apprensione</b> ed è paragonabile al rapporto madre-figlio. Anche questo è un rapporto ambivalente, poiché per <i>"amore"</i> si impone all'oggetto una vita molto limitata.<p>
</p>Frazer scopre che molti re sono uccisi ritualmente. C'è, quindi, una connessione tra il potere del Re e il sacrificio rituale che risulta statisticamente difficile da spiegare. In alcune società, però, il Re non viene sacrificato ma, al suo posto, ci sono dei <i>"doppi del re"</i> (giullari, carnevale, ...) che rappresentano il sacrificio rituale. Come già visto, il re è un sostituto della figura paterna; ci si spiega, quindi, il motivo di questi scoppi d'ira verso di esso. <b>Spesso venerazione e persecuzione sono cose che vanno assieme, quando si parla di umani.</b></p>
<p>Poichè il Re, in queste condizioni, non era in grado di governare, troviamo una divisione tra un re <i>"sacro"</i> e uno che si occupa di affari. Nella forma originale, il Re diventa garante che tutte le cose naturali succedano come devono (<i>regna</i>) mentre l'altro comanda.</p>
<p>Quando le azioni ossessive si trasformano in un complesso rituale, finiscono per costituire dei <b>deliri organizzati</b>. Freud, inizialmente, non pensa che la nostra cultura sia basata su deliri organizzati, perché pensa che un delirio organizzato si scontra prima o poi con la realtà e crolla. Dopo il 1933, analizzando il Nazzismo, Freud comincia a rivalutare la sua posizione, accetando che ci possa essere qualcosa come una paranoia totale.</p>
<p><i>Secondo interpretazioni di Frazer, i primi re erano stranieri che dopo un breve periodo di regno sarebbero stati sacrificati in una cerimonia sacra.</i> Freud sostiene che il Cristianesimo ancora abbia delle rimanenze di questo. Freud potrebbe alludere al fatto che Gesù è stato proclamato Re (INRI) e fornito di corona. Secondo Frazer, invece, questa è una grottesca presa in giro, come quella che avviene nelle Saturnali. Questo potrebbe essere visto come nuovi esempi di re-sacrificale.</p>
<li>Tabù che riguarda i morti
<p>Si può notare che ci sono moltissimi tabù intorno alla morte. Esempi sono: cadaveri, omicida, arma del delitto, coloro che toccano i morti, etc. Si è notato che il tabù dei morti è più forte quando le persone morte sono care (parenti, persone vicine), e meno forte quado i morti sono sconosciuti.</p>
<p> Westermark spiega questo sostenendo che la persona appena muore diventa un demone che vuole vendicarsi. Secondo le popolazioni aborigene, infatti, non esiste morte naturale, e tutte le persone vengono uccise o direttamente, o tramite la magia. La cosa che può colpire è il fatto che più la persona deceduta è vicina, più bisogna temere la sua ira. Inoltre bisogna considerare che i morti hanno un rapporto particolare con la morte, infatti c'è una specie di commistione tra i morti e la morte. Westermark sostiene che i morti diventano buoni solo dopo aver compiuto la loro vendetta. A questo punto diventano i buoni antenati, storicamente sempre onorati.</p>
<p>Freud accetta la spiegazione di Westermark, però non pensa che la spiegazione sia completa. Freud aggiunge alla teoria che quando una persona muore, è naturale che tutti coloro che hanno trattato male il morto si sentono parzialmente reposnsabili. Fermo restando che una persona che muore non ha voluto morire, stiamo male perché ci ha lasciati, e quindi si crea una corrente di ostilità verso il morto. Il sopravvissuto nega questo, in modo incosciente, per evitare una contraddizione emoriva, quindi proietta questo sentimento sul morto. Il demone è semplicemente l'odio che i vivi hanno verso il morto e che riproiettano su esso.</p>
<p>Freud basa la religione, la cultura e la società sulla proiezione. La definizione data da Freud di <b>proiezione</b> suppone che il cervello umano abbia, originariamente, solamente la funzione di percepire i processi esterni (eso-psichici) e percepisce i processi endo-psichici soltanto come forma di piacere o dispiacere. L'individuo non pensa a ciò che pensa, ma percepisce soltanto i sintomi esterni, il piacere e il dolore. I processi endo-psichici più potenti vengono attribuiti a un fenomeno eso-psichico. Il cervello umano trasforma in stimoli esterni gli stimoli interni poichè non è in grado di gestirli come stimoli interni. Proiettare costituisce la risposta più adattiva e, anche se il suo risultato è falso, può essere utile alla sopravvivenza. Gli spiriti, i demoni e le anime che "popolavano" il mondo antico sono da considerarsi come delle proiezioni dei processi endo-psichici. La proiezione è molto utilee per liberare la mente da contraddizioni che potrebbero arrecare danni all'individuo.</p>
<p>Il vedovo o la vedova sono pericolosi anche da un punto di vista sessuale. Inoltre loro, come anche gli altri parenti, possono essere scossi e quindi pericolosi.</p>
</ul>


<p><b>Colui che infrange un tabù, diventa a sua volta oggetto di tabù</b>. Il motivo è che la persona risveglia negli altri la tentazione di fare quel qualcosa. Se la violazione del tabù non ha provveduto a punire la persona stessa, le altre persone lo puniranno, per paura dell'esempio negativo. Non di rado, le persone colgono la situazione per fare la stessa azione ma in modo "giustificato". Questo è uno dei fondamenti del sistema giudiziario moderno.</p>
<p>Freud, inizialmente, cerca di spiegare tutto con le pulsioni per il piacere ma, successivamente, indaga l'esistenza di altre  pulsioni, come le pulsioni distruttive (di morte). Una delle cose che fanno pensare a Freud l'esistenza di tali pulsioni è il fatto che una persona terrorizzata, continua a sognare cose che lo terrorizzano, e questo andrebbe contro le pulsioni di piacere. Freud, all'inizio, sostiene che il mettere le mani addosso a qualcuno, sia una forma di trasformazione delle pulsioni sessuali.</p>
<p>Parallelo tra le azioni degli ossessi e dei tabù. Questo è manifesto nel fatto che entrambi i casi hanno un'ambivalenza conscio/inconscio. Così come il tabù si sposta perché si sposta il desiderio così i rituali dell'ossesso provengono da un'ambivalenza nei confronti di determinate azioni.</p>

<?php t2("2.1", "Fixes to be evaluated"); ?>
<p>Il sogno serve per garantire il prolungamento del sonno. Per questo non possono essere troppo espliciti, però non viene censurato. Le pulsioni assumono una veste presentabile. L'operazione onirica primaria serve per evitare che la persona si svegli a causa di quello che ha sognato. L'operazione onirica secondaria. L'esigenza che il sogno non disturbi il sonno, il sogno necessita una certa logica (anche non completa). </p>
<p>Quando una persona proietta all'esterno propri sentimenti, gli deve fornire una veste di accettabilità. Il delirio paranoico ha la funzione di mettere in un sistema razionale pulsioni primitive che non ha nulla di razionalità. Lo psicotico può essere una persona in cui nulla più di coerente trapela, mentre nel paranoico, tutto è logico. La magia, l'animismo, la proiezione verso l'esterno, i demoni sono tipici dei sistemi paranoici. Per diventare collettive, devono per forza essere fenomeni logici, almeno in apparenza.</p>
<p>Freud pensa che nella civiltà moderna, il tabù della morte ha perso potere, rispetto al passato. La vita emotiva è diventata più tenera e ci sono più collegamenti positivi che negativi all'interno della famiglia. Quindi c'è meno motivo per odiare la persona che è morta, e di conseguenza proiettargli addosso il proprio odio.</p>
<p>Il tabù è anche alla base della nostra morale. Infatti moralità vuol dire la preclusione di compiere atti che seguono un desiderio. L'istanza morale che c'è dentro di me, è una istanza repressiva esterna, interiorizzata. Il tabù, come la morale, è frutto di una cultura che noi facciamo nostra (interiorizziamo) ma che è contro le nostre pulsioni. <i>Più la cultura è moralmente e sessualmente repressiva, più individui nevrotici e quindi infelici saranno presenti.</i> Non è pensabile una società nella quale nessuna morale/tabù è presente. <i>Il soddisfacimento sessuale è innanzi tutto un fatto privato dell'individuo.</i> È impossibile stringere relazioni pubbliche, senza distogliersi dal proprio partner. Le forze sessuali non cimentano le relazioni tra le persone. Il nevrotico grave ha delle pulsioni sessuali molto potenti, e fugge dalla realtà, perché esso è in contrasto con la società.</p>
<p>Nella prima teoria di Freud evidenzia due pulsioni: quelle erotiche e quelle di conservazione. Le prime devono essere tenute a freno per poter avere anche le seconde. Questa non è una teoria bipolare, perché entrambe le pulsioni sono pulsioni di piacere. Le seconde garantiscono nel tempo una maggiore continuità delle prime. Questa è una dottrina ottimistica, perché nel complesso è una struttura pulsionale che è tutta rivolta al piacere.</p>

<?php t("3", "Animismo, magia e onnipotenza dei pensieri"); ?>
<p>Freud riconduce una serie di pratiche, come la credenza nella magia, negli spiriti, etc, alla fase del narcisismo. Freud ritiene che ci sia uno sviluppo ordinato nello sviluppo umano.</p>
<p>Tutti i popoli hanno forme di magia, tranne quelli che ne sono terrorizzati. Il divieto biblico di fare immagini di esseri viventi (e di Dio) non nasce dall'idea che la magia non esiste, ma dal fatto che c'è il timore che un'immagine possa essere usata per scopi magici.</p>
<p>Secondo gli egizi, quando il Dio del sole (<b>Ra</b>) calava (tramonto), Ra combatteva una lotta contro degli spiriti che provavano a prolungare il più possibile la notte. Il compito dei sacerdoti, era quello di creare immagini di questi demoni, e poi la figura veniva 'maltratta' per aiutare Ra a riemergere il mattino dall'orizzonte.</p>
<p>L'<u>azione sugli spiriti</u> si chiama <b>incantesimo</b>. Le pratiche magiche sono antecedenti delle pratiche di incantesimo. Freud sottolinea che <i>la magia è caratterizzata da una sopravvalutazione del pensiero</i>. L'uomo attribuisce alla capacità di collegare due fenomeni psicologici anche a due fenomeni reali. Quando ci si offende, si pensa che questo possa essere una forma di reazione utile. Questa è una forma di sopravvalutazione del pensiero.</p>
<p>I <b>bambini</b> molto piccoli non hanno quasi mai la capacità di agire, e quindi usano moltissimo questa capacità. Il piangere è la scoperta della propria debolezza nei confronti del mondo esterno. Il bambino cerca e trova soddisfazioni illusorie. L'auto-erotismo che il bambino ha, spesso si manifesta come dito in bocca. La <u>prima fase auto-erotica</u> è caratterizzata da attenzioni verso una parte dell'oggetto e non la sua totalità. Nella seconda, invece è caratterizzata da attenzioni verso un'intero oggetto. Un caso del primo momento è la bocca. La <u>seconda fase</u> è caratterizzata dall'investitura di un intero oggetto di una libidine: lui stesso.</p>
<p>Questa è la fase <b>narcisistica</b>, e il bambino si comporta come se fosse innamorata di se stessa. È ancora incapace di investire un'esterno di libidine, ma è già in grado di vedere se stesso completamente come oggetto libidico. <i>Come noi sopravvalutiamo la persona amata, così l'individuo nella fase narcisistica pensa di essere capace di quasi qualunque cosa</i>. Se una persona rimane in questa fase, si diventa megalomani. Il narcisismo intellettuale e l'onnipotenza dei pensieri vanno di pari passo. <u>Nel narcisismo l'individuo non fa i conti con la realtà esterna</u>. Una persona può pensare di essere immortale solamente se è in una fase di esaltazione narcisistica. Il narcisista può raggiungere uno stato di ebrezza senza paragoni, poiché solo lui può vantare l'intera attenzione del suo oggetto di amore. Il narcisismo può acquisire una certa accettabilità se diffuso socialmente. In questi casi il narcisismo deve essere metodizzato e quindi può sopravvivere in modo collettivo senza che questo carattere faccia crollare la società. Il narcisista è onnipotente all'interno del suo recinto (se stesso). L'impatto con la realtà può risvegliarlo da questa fase.</p>
<p><b>La magia è molto reale</b> dal punto di vista psichico, poiché la credenza nella magia produce l'effetto che crede di produrre, in certe situazioni. "Nella vita, si può dire, che conta soltando la <b>moneta nevrotica</b>". Cioè, <u>nella vita non contano le cose per quel che valgono, ma il valore che noi gli diamo</u>. Una persona che sia profondamete inconsapevole delle pulsioni, pensa che la realtà è plasmata da lui. "conoscere che un'idea è adeguata non è sufficiente a scacciare un'idea inadeguata" (Spinoza). La cura non consiste nello spiegare la causa al malato. "Per scacciare una passione, serve unaa passione più potente" (Spinoza).</p>
<p>Freud e <b>Jung</b> hanno una grande differenza di visione poichè, supponendo che qualcosa cancelli per una generazione intera fiabe, miti, leggende, religioni i due studiosi prevedono situazioni diverse. Secondo Jung, la nuova generazione ritroverebbe, ricostruirebbe da dentro di se tutti i miti identici o molto simili a quelli originali,mentre secondo Freud l'uomo che si trovasse in una situazione di azzeramento del patrimonio culturale, lo ricostruirebbe a partire dalla presentazione da quei fenomeni che avevano creato i miti in primo luogo.</p>
<p>Una volta mostrata l'inesistenza concettuale delle magie, e l'utilità per chi ci crede, non si è dissolta la magia. Nei casi di <b>"malattie nervose"</b>, nonostante la gravità dei sintomi e il dolore che il malato prova, la malattia può essere il male minore. Il sintomo, per quanto doloroso, è meglio dell'alternativa. La pulsione si scarica sempre là dove la resistenza è minore. Questi sintomi tendono ad organizzarsi nella forma più coerente possibile.</p>
<p>L'<b>isteria</b> è una caricatura del gesto dell'artista. La mania dell'artista è la musa, mentre all'isterico consiglia cose senza alcuna bellezza. L'<b>ossessione</b> è la caricatura di una religione. I religiosi compiono dei gesti rituali, così fa anche l'ossessivo. La <b>paranoia</b> è la caricatura di un sistema filosofico. Entrambi hanno la ricerca assoluta di una coerenza a partire da presupposti che possono non avere delle evidenze sulla base empirica.</p>
<p>Caso del <b>presidente Schreber</b>: un delirio organizzato che trova un compromesso con la realtà. Parte da alcune premesse e costruisce un sistema di incredibile precisione. I sistemi filosofici riescono a conquistare più seguaci rispetto al sistema del Presidente Schreber. Il Presidente Schreber era un eminente giurista della Sassonia, molto rigido dal punto di vista morale e religioso. Cristiano inmodo "molto convinto", e ad un'età avanzata ha avuto un esaurimento nervoso di circa un'anno. In questo periodo viene curato da Flechsig. Quando la sua carriera sta per fare un salto, ha un altro crollo psicologico. Cade in un delirio paranoico ricchissimo di dettagli. Riusciva a tenere una facciata di normalità, mentre nei momenti dove non era obbligato, delira. Scrive un'opera per ricordare le sue memorie per cercare di dimostrare che i suoi deliri sono reali. Freud si getta su questo caso perché i malati di paranoia non possono andare nel suo studio, perchèerano rinchiusi. La terapia del nevrotico a distanza non ha senso perché ci deve essere interazione tra le due parti. Il paranoico, invece, dice sempre e soltanto quel che gli pare. Quindi l'interazione con il medico non è una variabile. Schreber afferma che il tutto è nato dall'idea che essere donna e sottoporsi alla copula possa essere buona. Freud ritiene che Schreber ha creato un'enorme struttura per rifiutare la cosa. Ilsistema del pensiero si costituisce di due punti. Schreber ritiene di essere destinato al ruolo più importante che l'universo abbia mai avuto. Il suo essere donna è necessario perchè deve creare una nuova specie. Secondo lui gli attuali uomini sono cadaveri o finzioni di uomini, perchè Dio ha sterminato l'umanità. Pensa che Dio sia cattivo e che agisce con dei raggi che escono dal sole che portano malattia. Dio capisce e ama soltanto i morti, e che avendo visto in lui un'individuo in cui i nervi sono più potenti di quelli di Dio. Il dottor Flechsig è il boia di Dio che prova ad assassinare la sua anima. L'ordine delle cose è favorevole a Schreber, Dio (che è cattivo) non può giungere ad assassinare la sua anima perché l'ordine delle cose glielo impedisce. Tutte le cose che non quadrano trova una spiegazione ad-hoc. Arriva a dire che un dottore ha fino a 40 diverse realtà. Le parole che usa in certi momenti (volgari) sono esatte perché espongono lo stato delle cose. Quando viene dichiarato guarito dalla seconda malattia, mantiene quasi tutte le sue idee. Tra cui quella che l'umanità non esista più.</p>
<p>Freud pone il problema sul <b>rapporto col padre</b>. Il sogno di essere donna è il sogno di essere evirato. È un timore che il bambino maschio sperimenta di fronte alla figura paterna. Secondo la spiegazione di Freud, la figura del sole (cattivo), del medico (cattivo), ..., sono proiezioni del padre o di un fratello maggiore. Freud afferma che Schreber è un malato di proiezioni, nel senso che ha proiettato sulle varie figure immagini del padre. Padre che deve eessere stato una vera ira di Dio. Il padre di Schreber è il medico che inculcò il culto per la ginnastica dei bambini nella società. Questa educazione era ferocemente avversa all'auto-erotismo, minacciato in qualsiasi modo. C'erano dei modi al limite del sadismo per imporre la postura. Questa è stata chiamata la "<b>pedagogia nera</b>". Sotto il nazzismo, queste intuizioni, vennero spinte all'estremo. Sottoposto a un padre così, Schreber, cerca di compensare l'umiliazione estrema di queste pratiche educative, inventando per se stesso un ruolo cosmico, e spiegando le sue paure aggiungendogli un fine gratificante. Quando il padre è così amato e così temuto, ha eretto se stesso ad individuo di importanza universale, per fare delle sue paure un motivo di vanto. Una delle cose che Schreber mantenne, uscito dalla casa di cura, è il sostenere di poter guardare il sole senza farsi male agli occhi. L'emblema di famiglia aveva l'aquila, e l'aquila può guardare il sole senza problemi. Al che dimostrava che lui discendeva dal sole, e quindi il Sole cattivo era suo padre.</p>

<?php t("4", "Il ritorno del totemismo nei bambini"); ?>
<p>La <b>religione totemica</b> nasce dal <b>senso di colpa</b> dei figli. Come tentativo di riconciliarsi col padre è usata l'obbedienza retrospettiva. Ogni uomo (maschio) ripercorre questo procedimento nella sua infanzia.</p>
<p>In che modo una società che è costituita sui due imperativi totemici ha bisogno di risaldare il legame tra fratelli? Ripetendo l'azione che l'ha creata. È quindi necessaria un'uccisione che ricorda il parricidio iniziale. Freud nota come alcune religioni (in particolare quella cristiana) si siano articolate su questo. Nelle religioni, Dio è il padre e la religione è un modo per recuperare alcuni aspetti del rapporto col padre. Tuttavia la madre può diventare surrogato del padre (animale totemico) in certe situazioni.</p>
<p>Freud pensa che alla <b>fondazione della società</b> ci sia un <b>parricidio</b>. Da questo, si può far derivare tutte le formazioni culturali. Le istituzioni sociali nascono tutte da quel sentimento tra i fratelli. La fratellazna non è soltanto razionale, ma è anche fondata su un comune senso di colpa. Una società non si può solo basare su una convenienza. Secondo Freud, una società richiede anche un vincolo affettivo. Al di sotto di un vincolo sociale, ci deve essere una sublimazione della libido sessuale.</p>
<p>Il <b>sacrificio</b> è, indubbiamente, la più importante istituzione religiosa. Da un lato il sacrificio è una <u>ripetizione dell'uccisione del padre</u>, ma dal momento che il sacrificio è offerto alal divinità, il padre appare sia come vittima dei fratelli sia come colui al quale si rivolge l'atto di sottomissione.</p>
<p>La <b>società</b>, con tutti i suoi <b>divieti</b>, si impone in modo contrastante con i desideri primari umani. Si può quindi capire che questo non può essere creato da un mero calcolo, ma solo può essere stato causato dalla presenza della paura di ritornare alla situazione iniziale.</p>
<p>Frazer ritiene che il Re sia un personaggio molto particolare, poiché si rendeva conto di un'incidenza di reggicidi superiore rispetto al sacrificio di ogni altro membro della comunità. La più importante analisi sulla questione è quella che Frazer esegue nell'opera <i>Il <b>Ramo d'oro</b></i> nella quale Frazer riporta un'antica usanza romana. Presso gli antichi romani c'era un'istituzione che, anche se non centrale, è durata tantissimo per quasi tutta la durata dell'impero. Per descriverla usiamo le parole di Frazer: <i>"In questo bosco sacro cresceva un'albero, intorno a cui in ogni momento del giorno si aggirava una truce figura. Quest'uomo era un Re, e un omicida. [...] Un'aspirante sacerdote poteva diventare sacerdote solo uccedendo il predecessore."</i>. Quest'usanza mette assieme tre figure:</p>
<ul>
<li>Assassino/Vittima
<li>Sacerdote
<li>Re
</ul>
<p>Frazer formula più di una spiegazione per quest'usanza (p183). Freud pensa che quest'usanza si può capire grazie alla teoria del sacrificio. "Cosa simboleggia colui che viene ucciso?" Il padre. Allo stesso tempo il padre è il Dio a nome del quale il sacrificio viene compiuto. Possiamo supporre che tra l'assassino del sacerdote e il sacerdote stesso, non sia altro che una limpida espressione del fatto che il Dio è prima qualcuno contro il quale si opera in modo violento. Si può diventare Dio solo se prima si viene ucciso.</p>
<p>Frazer elabora una teoria per la quale il re nasce dalla figura del prigioniero di guerra che deve essere sarificato. I primi Re erano prigionieri che godevano di largo prestigio perché su di loro potevano essere rovesciati tutti i problemi della comunità stessa. In una popolazione africana troviamo le seguenti righe riferite ai re:</p>
<cite>tu sei un escremento,<br />
tu sei la nostra salvezza,<br />
tu sei venuto per ucciderci,<br />
tu sei il nostro salvatore</cite>
<p>Il Re viene usato come Caprio Espriatorio della società e, ritualmente, viene messo a morte. Il Re è tale soltanto nella misura in cui si sa che verrà ucciso sistematicamente. Al Re che regna si distacca un Governatore che governa. In questa seconda figura noi abbiamo l'antenato dei Re moderni. Anche essi mantengono dei tratti del primo Re, ma questi tratti sono molto limitati e limitano la sua possibilità di governare.</p>
<p>L'esaltazione del Re e contemporaneamente l'ucciderlo, sono esattamente le due azioni che troviamo nel primo omicidio (il parricidio che porterà alla costituzione della comunità dei figli.</p>
<p>Freud non sa affermare quando le <b>divinità femminili</b> si sono create con precisione. Freud nota che le divinità femminili sono spesso accompagnate da animali che sono i loro protettori/vendicatori. Freud pensa che la divinità femminile finisce per fondare la sua temibilità su figure maschili (gli animali). L'omicidio, cioè l'atto religioso per eccellenza, viene sempre compiuto dagli animali (quindi maschi).</p>
<p>Le <b>religioni del figlio</b> sono più di una: esempi ne sono quella Cristiana e quella di Mitra. La sua analisi di Cristo è: se Cristo libera gli uomini dal peso del Peccato Originale sacrificando la sua vita, è evidente che il Peccato Originale fosse stata un'uccisione, per la legge del taglione. Come nelle costruzioni nevrotiche, il Peccato Originale, nella Bibbia è trasposto, ma questa trasposizione da luogo a delle incoerenze che sono la manifestazione che il contenuto di questi miti è stato sottoposto a un lavoro simil-onirico. La riconciliazione con il padre (la morte in croce) è ancora più forte perché Gesù rifiuta completamente la donna. Cristo per il senso di colpa accetta una morte ignominosa per espiare il delitto, ma ha anche il sentimento di fierezza per aver ucciso il padre. Questo comporta che il figlio si affianca al padre o, addirittura, lo sostituisce. La comunione Cristiana è un pasto Totemico 'aggiornato' poiché vede una sostituzione del Padre con Gesù. Gazie ai comandamenti di fratellanza, capiamo che il cristianesimo accentua i temi della solidarietà tra fratelli, fondata sulla complicità in un omicidio.</p>
<p>La <b>tragedia</b> (p187) è una tendenziosa ripetizione dell'evento primordiale. Quello che è successo la prima volta è riportato in modo infedele. Il coro rappresenta la banda dei fratelli. Un'orda di persone che circonda una persona sola che deve soffrire, ci rappresenta una situazione di linciaggio. La raffinata ipocrisia consiste nel togliere al coro la sua violenza, facendone un'adunata di persone che commentano con simpatia. A questo punto non si capisce perchè l'eroe soffre. Allora la tragedia giustifica questo creando degli errori che in passato l'eroe ha commesso, spesso in modo inconsapevole. Esattamente come la vittima sacrificale, gli si addossa tutte le colpe, e dopo averlo ucciso lo si ringrazia.</p>

<p>In questo capitolo, Freud ci parla dell'<b>origine delle religioni</b>. Freud pone l'origine delle religioni nell'infanzia dei bambini. Nell'inconscio di ogni adulto ci sono segni delle manifestazioni di fenomeni avvenuti quando lui era piccolo. Il bambino, di fronte ad un affetto potente, è privo (o meno dotato) di deviare l'affetto verso altre cose. Gli adulti hanno a disposizione tanti oggetti sostitutivi per la loro vita psichica. Per i bambini, invece, ci sono quasi solo le figure parentali. Il bambino non è in grado di distrarsi in altro modo, perchè non si è ancora aperto a quella varietà di esperienze. Il bambin può superare il trauma, ma questo andrà a toccare tutta la sua vita psicologica. Se i genitori gli provocano qualcosa, esso non imparerà a rivolgere altrove la sua attenzione. Freud insiste tato sulla costituzione psichica del bambino perchè la religione ha una potente forza affettiva, essa non può essersi imposta nella fase adulta. La religione non può essere nella psiche umana nell'età adulta. Le paure, i terrori etc colpiscono molto meno gli adulti che i bambini. Come il nevrotico è essenzialmente legato ad una condizione infantile che non riesce a superare, così l'uomo religioso è caratterizzato da una condizione infantile. La religione è da legarsi con un particolare trauma che ha colpito l'umanità in un'epoca lontanissima. Secondo Freud le religioni non sono causate da un'accumulo di eventi, ma da un evento unico che è punto di origine delle religioni. A partire da quel momento, le religioni hanno dominato l'umanità. L'uomo religioso, soffre per la reminescenza di quel trauma.</p>
<p>I traumi di guerra non lasciano gli stessi effetti nell'uomo adulto se non vengono collegati ad un trauma infantile. Quando si parla di trauma, dobbiaamo ricordare che per Freud il nervrotico non conta tanto che il trauma sia riconducibile ad un fatto reale. Freud, all'inizio, si rende conto di quanto frequentemente il ripo di ricordo che veniva rimosso e che provocava malattia da adulto è caratterizzato da un trauma sessuale oviolenta da bambino, nella maggior parte da parte del padre. Si rende conto che il trauma può non essere avvenuto realmente, ma basta che il bambino abbia freinteso l'azione del padre. Da un punto di vista legale, le due cose sono molto diverse, ma da un punto di vista psicanalitico è quasi identico. Alcuni ricordi sono falsi, anche se sono molto realistici. Secondo Freud ci sono dei rapporti platoici che sono costitutive per l'essere umano, e se vengono intaccate i danni sono enormi.</p>
<p>Il punto di contatto del rapporto totemismo-bambini è: come il totem una religione che afferma che gli individui di un clan sono discenenti dal totem stesso, così l'animale è nella vita psichica del bambino, sta a sostituireil padre. Questo è quello che si evince anche solo ascoltando gli aborigeni. Il bambino attraversa una fase totemica, in cui la figura paterna viene esteriorizzata su un animale. La fobia da animale costituisce la fase totemica del bambino.</p>
<p>Il totemismo è l'oggetto del discorso Freudiano perhè sembra essere la forma religiosa più antiche. Cogliendo la vera natura del totemismo, si possono cogliere tutte le nature di tutte le religioni. Essere totemici significa:</p>
<ul>
<li>considerare che un animale l'antenato della tribù
<lI>il totem si eredita per linea materna
<li>non si può uccidere ne mangiare il totem
<li>non si  possono avere rapporti sessuali con un'altro appartenente allo stesso totem
</ul>
<p>Questo è il codice della più vecchia religione al mondo. Freud cerca di dare una spiegazione cominciando con l'analisi delle dottrine presentate dai suoi contemporanei.</p>
<p>Un'insiseme di teorie chiamate <b>nominalistiche</b>. Il totem è stato attribuito a un certo clan perchè originariamente qualche individuo fu individuato un tratto comune con un animale. Successivamente c'è stata una confusione tra il nome vero e il nome totemico. L'idea che un nome attribuito da altri, fosse rimasto appiccicato a un clan era molto improbabile. Queste teorie sono statedemolite</p>
<p>Spiegazione <b>sociologica</b>. (Durkain) pensa che il totemismo nasca da una forma di aggregazione sociale molto particolare: es: coloro che avevano a disposizione un gran numero di animali di un certo tipo, hanno cominciato a vendere la pelle/carne dell'animale. Una specie di cooperativa di consumo. Secondo lui nel totemismo uello che conta è semplicemente la società stessa. Quello che ogni clan venera come totem, in realtà, è il clan stesso. L'unica cosa che trascende il singolo uomo è la società stessa. Il 'Dio' dell'individuo è la società stessa. L'unica cosa che merita il titolo di divinità è l'unioe di tutti gli individui. L'intuizione è che Dio è la folla, la massa. Dio nasce quando in una società c'è un'insieme di individui che agiscono collettivamente. Quando gli individui hanno 'provato' la massa, pensavano di aver davanti  un evento sovra-umano. Il totem è il vessillo agitata quando la società agisce tutta assieme. Quello che conta del Totem sono proprio i colori. Tutti i fenomeni collettivi sono un'esperienza religiosa originaria. L'elemento decisivo della religione è stare tutti assieme a fare la stessa cosa. Non sono importanti i contenuti, ma gli aspetti sociali. La religione è cagulazione. Tutto quello che è rito, serve a tenere assieme. Solo lo stare tutti assieme a fare la stessa cosa può dare all'uomo quel brivido di un qualcosa di superiore. Chi compie un gesto all'interno di una comunità coesa prova un sentimento che lui chiama <i>effervescenza</i>. Le nostre sensazioni vengono potenziate. Quando una massa agisce tutta assieme, si ha un'effetto paragonabile a quello degli allucinogeni. Il sacro è quel brivido che passa all'interno di una persona che sta agendo all'interno di una massa. Non esiste una religione privata ne morale. Freud liquida questa teoria in modo troppo veloce. Freud non l'accetta perchè non spiega il divieto dell'incesto da un punto di vista sociologico.</p>
<p>Ne Freud ne Durkain uniscono il narcisismo ad una forza di massa è uno dei temi del libro sulle masse.</p>
<p>Altri parlano di una natura psicologica del totemisco, i quali pensano che il totemimo nasca dalla considerazione che il totem è la forza che produce la gravidanza della donna. Il totem sarebbe la forza che feconda le donne. Frazer afferma che il totemismo è il risultato delle donne in cinta.</p>
<p>Freud propone di immaginare come sono vissuti gli essere umani nei tempi più remoti. La risposta nasce da un'osservazione fatta da Darwinin <i>l'origine dell'uomo"</i> sulla gelosia e sull'improbabilità della promisquita dei sessi. Possiamo supporre che l'uomo premitivo come tanti animali che conosciamo vivesse in origine in piccole comunità con un uomo e tante donne quante lui possa mantenere e ottenere. In ogni "orda" si ha soltanto un maschio adulto. Il giovane maschio quando diventa sessualmente attivo, il più forte - dopo aver ucciso o cacciato l'altro - si impone come capo della comunità. Allora, come osservò Hatchinson, se il maschio che nasceva all'interno di un certo gruppo, queste orde erano già esogamiche. Nei bambini abbiamo una singolare predisposizione di cadere in una nevrosi fobica nei confronti degli animali. Questo perchè l'animale viene visto come eviratore. Arrivando ad identificarsi nell'animale temuto. La duplice carica affettiva verso l'animale è paragonata da Freud al rapporto col padre. Quindi l'animale totemico è il padre (A=B, B=C => A=C). Il padre geloso dell'orda primitiva, abbiamo motivo di supporre sia il totem. La figura del totem con tutti i divieti che impone sia il padre. Se il totem è il padre, ci spieghiamo il divieto dell'incesto.</p>
<p>Se lanimale totemico è il padre, i due comandamenti fondamentali del totemismo, coincidono quanto a contenuto con i due delitti di Edipo e con i due desisderi primordiali del bambino.</p>
<p>Dopo Freud, non solo la visione dell'infanza viene modificata dalla visione dei popoli primiitivi e viceversa, quest'opera collega elementi che nessuno avrebbe mai pensato di collegare. La tragedia e il mito non sono opere, ma sono rappresentazioni di pulsioni che abbiamo. Anzichè tirar fuori la Grecità, come se fosse un'essenza, Freud afferma che queste pulsioni foondamentali trovano la loro espressione nella tragedia e anche in altre forme di arte.</p>
<p>Freud si occupa del sacrificio. Non tutte le religioni sono totemiche, anche se si pensa che sia alla base di tutte le culture. Il sacrificio, però, è presente in tutte le culture e se la si riesce a provare che c'è una connessione con il rapporto padre-figlio. Come dice Freud, la parola sacrifico (come rinuncia) è un'accezzione sicuramente posteriore. All'inizio non era così. Un altro concetto sbagliato, è uello del sacrificio come offerta alla divinità. Il sacrificio originariamente è semplicemente una uccisione collettiva. Sacrificare vuol dire linciare. L'esempio di sacrificio che Smith ci riporta fuga ogni dubbio. Il sacrificio è da intendersi come distruzione di un'essere umano o un animale. Tutte le religioni conoscono il sacrificio, in tutte le religioni il sacrificio è cruento. Con una grandissima probabilità, i primi sacrifici furono umani, per poi trasformarsi in sacrifici animali e poi prodotti della terra etc. Il pasto sacrificale è una usanza di uccidere un animale, solitamente proibito, tutti assieme, mangiarlo tutti assieme. L'animale considerato intoccabile viene ritualmente ucciso e mangiato. Chi partecipa al rito, spiegano che un modo per stringere rapporti con le altre persone. <b>Kinship</b> è quel legame sociale con quello persone cui mangi. Il pasto "totemico" è un pasto. La proibizione di mangiare un'animale ma l'obbligo di mangiarlo in certi momenti, rappresenta un'ambiivalenza. In modo chiarissimo, l'ambivalenza nei confronti del totem da origine a reali fatti cruenti. In molte feste documentate presso popoli primitivi, la festa che seguiva il pasto totemico, era caratterizata dall'abrogazione dell'incesto. Freud non accetta il soddisfacimento delle pulsioni come fatto immaginario. Il mito di Edipo non è una storia inventata, ma dobbiamo supporre che le prime manifestazioni della vita sociale degli uomini siano stati cruenti. Secondo Freud, quando parliamo di miti, probabilmente, siamo difronte a fatti reali. Con questo discoso, Freud mette sulla carreggiata del ragionevole tutta la scienza dei miti.</p>
<p>I più antichi modi di omicidio sono collettivi e deresponsabilizzati:</p>
<ul>
<li>Spingere una vittima verso un precipizio
<li>Lapidazione
<li>Plotone di esecuzione
</ul>
<p>Qui abbiamo la prova che le religioni sono una prassi sociale. Poichè la religione ha bisogno di adepti, non può dare vantaggi solo a un piccolo gruppo di persone. Le religioni sono un fenomeno collettivo perchè rispondono a un'esigenza umana, cioè sentire la propria forza moltiplicata grazie alla presenza degli altri. La religione non è un'inganno di qualche astuto individuo, ma è il prodotto di un'immaginazione collettiva. La religione non può esistere senza una chiesa. Un'ossessione si distingue da una religione per il carattere pubblico che la seconda ha.</p>
<p>Freud è ateo e il suo rapporto con l'ebraismo è molto complesso. Non respinge la sua cultura ebraica.  Freud cercherà di mostrare che l'ebraismo non è così originale quanto sembra.</p>
<p>I fratelli scacciati dai clan, si riunirono, abbatterono il padre e lo divorarono.  Uniti, i fratelli osarono compiere ciò che risultava impossibile. Uccidedo e mangiando il padre, ogniuno si identificò in modo più forte nel padre. L'uccisione del cammello è la commemorazione di quell'antico pasto che vide i fratelli mangiare il padre. Ogni festa, in origine, è la commemorazione dell'uccisione del padre. Freud poi interpreta altre forme di comunione da quella derivanti dal padricidio. Se avessero ucciso uno straniero, essi sarebbero stati meno contenti, perchè il padre è la persona è meno odiata, però ci sarebbe anche meno <i>senso di colpa</i>. Mentre festeggiavano, già si sentivano tristi. Iniziano tacitamente ad obbedirgli post-mortem. Avevano cioè introiettato la figura opprimente esterna. Così si crearono le due regole totemiche. I due tabù fondamentali i fratelli se li sono dati, ma essi hanno diverso valore. Il divieto di uccidere il padre si basa sul senso di colpa dei figli, e il divieto dell'incesto è l'obbedienza retrospettiva. C'è anche un secondo motivo: il bisogno sessuale li divide, non li unisce. In questo modo loro salvarono l'organizzazione che li ha fatti forti. Non è da escludersi che la lega costituita che, come ogni unione sociale, doveva esserci una forma libidica. Non è da escludersi che la "società dei fratelli" si basasse anche su elementi omosessuali sviluppati nel momento di distanza dalle donne.</p>
<?php t3("9.1.2", "Note Finali"); ?>
<p>Quest'opera pone dei tentativi di soluzione straordinarie, ma non è completa come opera. Le intuizioni che ha, sono molto brillanti e alcune questioni sono ancora aperte.</p>

<p>Perchè io dovrei nascere con un senso di colpa così vecchio? Come si spiega il suo passaggio di generazione in generazione? La risposta di Freud è che in realtà non esiste un inconscio collettivo o ereditario, ma "nessuna generazione è in grado di nascondere alla successiva piuttosto importanti". Secondo Freud questi contenuti pscichici vengono trasmessi da un uomo all'altro in modo inconscio.</p>
<p>Se una religione sparisce, spariscono anche tutte le parti? No perchè alcune parti rimangono tramite trasmissione inconsapevole di detrrminate disposizioni psichiche. Il problema della continuità della cultura è uno dei problemi più difficili da spiegare.</p>
<p>Esiste anche un divenire storico che Freud non nega. La varietà delle vicende umane è un fatto inspiegabile, come per Darwin le variazioni all'interno degli esseri viventi sono inspiegabili. Freud legge la storia in termini evoluzionistici.</p>
<p>In un dato momento, in vari posti della Terra, ci sono vari 'tentativi', che alcuni sopravviveranno, mentre altre spariranno. Quelle varietà che erano contrarie alle esigenze del gruppo sono sparite. Quello che chiamiamo <b>Progresso Storico</b> è da spiegare non come una tendenza verso qualcosa, ma come una sopravvivenza di quelle variazioni positive.</p>
<p>Qualcuno potrebbe chiedersi: "Se effettivamente nella vita psichica non contano gli eventi realmente avvenuti, ma gli impulsi, perchè Freud afferma che all'origine di tutto c'è una <u>reale</u> uccisione del padre?" Freud afferma che è vero che nel caso del nevrotico la fantasia conta quanto la realtà, mentre nel bambino non è esattamente così. Il bambino cerca di mettere in atto le sue fantasie, con i suoi mezzi. Se il paragone tra bambini e selvaggi è vera, l'inibizione all'azione (la debolezza del bambino) non sarebbe stata presente per i selvaggi. Il nevrotico è l'unico che rimane inibito all'azione. È nel nevrotico che c'è una prevalenza del pensiero sull'azione. I bambini e i primitivi non soffrono perchè hanno un primato dell'azione. Nella passività del nevrotico, risiede la sua sofferenza.</p>
<p>Nell'adulto non nevrotico, le pulsioni originarie vengono spostati verso oggetti compatibili con il principio di realtà, mentre per il nevrotico non fa conciliare le sue pulsioni con il principio di realtà. Nel nevrotico non c'è la modificazione della pulsione ma ha semplicemente inibito le pulsioni. E questo fa soffrire la persona.</p>
<p>Freud è fortemente determinismo nel senso che in certe circostanze l'io non può che evolgersi in un dato modo. Freud nega la libertà del volere, perchè se esistesse il libero arbitrio, non si potrbbe fare scienza, ma soltanto quelle cose mosse da meccanismi si può capire e studiare.</p>
<p>In un certo senso, i padri possono essere di varia natura, perchè si parla di una forma di sviluppo costante?In realtà Freud pensa che dietro un'educazione più liberale, le vecchie forme di controllo dell'adulto sul bambino abbiano cambiato aspetto ma non sostanza. C'è qualcosa nella struttura padre-figlio che è costante, che assume varie forme nelle varie società ma non cambiano a livello profondissimo.</p>
<?php file::footer(); ?>
