<?php
require "../class/include.php";

file::head("Storia della Filosofia Morale - Totem e tabù");

toc::show_toc("Storia_della_Filosofia_Morale/Totem_e_tabu.php");
?>

<?php t("0", "Introduzione"); ?>
<p>L'opera <i>Totem e tabù</i> è divisa in quattro saggi.</p>
<p>Le parole "Totem" e "Tabù" derivano entrambe dal gergo dell'antropologia.</p>
<p><b>Totem:</b> progenitore naturale (animale, pianta, elemento naturale) di un clan (stirpe). Concetto tipico di società arcaiche, infatti non presente nella cultura occidentale.</p>
<p><b>Tabù</b>: divieto assoluto. È l'<i>imperativo morale</i> (o delle proibizioni assolute), e rappresenta il concetto negativo del sacro (innominabile).</p>
<p>Il sottotitolo dell'opera è <b>"Alcune concordanze tra la vita dei selvaggi e dei nevrotici"</b>. Freud sostiene che la nascita di questi due concetti possa essere spiegata usando l'analisi della vita dei nevrotici. Freud, infatti, ritiene che la nevrosi, nonostante oggi ci appaia come malattia, sia un residuo degli antichi totem e tabù. Il nevrotico soffre di regressione allo stato infantile, che è lo stesso stato in cui si sono fermati i popoli selvaggi. Tutti siamo nevrotici, chi più chi meno.</p>
<p>Freud più volte usa le espressioni <i>"popoli selvaggi"</i> e <i>"popoli semi-selvaggi"</i> per indicare alcuni popoli con una civiltà inferiore a quella occidentale, ma bisogna considerare che in quel periodo questo era normale, infatti - nello stesso periodo - assistiamo al colonialismo. Freud arriverà a superare, almeno teoricamente, questo preconcetto. Inoltre, le sue conclusioni per la vita dei selvaggi, valgono anche per i popoli europei, quindi - ovviamente - bisogna considerare i selvaggi alla stregua degli europei. Non si può, infatti, tracciare una linea evolutiva per dimostrare che noi siamo più evoluti di loro.</p>
<p>Freud venne molto criticato sia per il gusto della dissacrazione che spesso mostrava, sia perché accusato di aver mostrato gli umani come esseri mossi soltanto dalle pulsioni di piacere.</p>

<?php t("1", "L'orrore dell'incesto"); ?>
<p>Sin dalla fine dell'1800 ci si era posto il problema dell'obbligo dell'esogamia. L'esogamia è, infatti, la mescolanza dei geni con geni esterni. Il suo opposto è l'endogamia, spessa riferitasi come incesto. La definizione di 'gamia', ovviamente non è unica, ma varia al variare della civiltà considerata. Esistono molteplici situazioni sociali, nelle quali viene prescritta l'endogamia, quali: la Germania Hitleriana (ariani vs others), USA fino al 1967 (neri vs bianchi nel sud), Sud Africa (neri vs bianchi). Nonostante questo si obbligavano delle leggi esogamiche, quando  si parlava a livello familiare.</p>
<p><b>Westermarck</b> propone la teoria <i>Effetto Westermarck</i>, la quale suggerisce che individui che nascono e vivono sotto lo stesso tetto, perdono l'interesse sessuale l'uno per l'altro. Questa teoria deduce un divieto da una situazione di disinteresse psicologico, e  questo non spiega l'esistenza di una legge che lo proibisca.</p>
<p><b>Emil Durkheim</b>, Francese di origine ebraica, contemporaneo di Freud che nel 12-13 scrive un'opera sull'analisi della religione anche lui basandosi sugli Aborigeni Australiani. Secondo lui c'è un orrore per il mescolarsi del sangue che colpisce maggiormente la donna (sangue mestruale). Con una donna con la quale si vive, ci sono situazioni in cui si vede il sangue dell'altra persona, creando una situazione di non accettabilità. Questa teoria ha problemi su tutti i fronti, ma per la prima volta inserisce la religione come causa.</p>
<p><b>Spencer</b> propone una teoria che si fonda su: "in un epoca in cui la virtù cavalleresca è il tratto distintivo di un uomo, la capacità di riuscire a prendere una donna di un'altra tribù, è un motivo di prestigio". Questa teoria di Spencer non riesce a spiegare il motivo per cui si obbligano gli uomini ad acquisire prestigio.</p>
<p><b>Lévi-Strauss</b> vede in modo capovolto il problema. Pensa che la regola struttura il sistema sociale, non i divieti. Secondo Lévi-Strauss una buona regola per una società sia quella di entrare in contatto quanto più pacifico con altri clan/famiglie, anche scambiandosi le figlie. Secondo Lévi-Strauss, quindi, questa diventa una regola di "buon vicinato".</p>
<p><b>René Girard</b> (posteriore rispetto a Freud) rimane in una prospettiva Freudiana, considerando che il divieto preceda l'obbligo. Ma è un divieto (non Freudiano) che non verte sulla sorella in quanto cosanguinea, ma il divieto verte sugli oggetti sessuali che essendo troppo vicini, possono creare una rivalità all'interno della famiglia stessa. L'idea è sostanzialmente Freudiana, ma Freud mantiene il tema della parentela, mentre René Girard vede come tema qualsiasi oggetto troppo vicino.</p>
<p>Tutte le precedenti teorie non risolvevano il problema per sei motivi:</p>
<ol>
<li>Come fa notare Frazer, un uomo non ha motivo di proibire a se stesso qualcosa che non farebbe comunque
<li>Non spiegano il motivo per vietare il soddisfacimento sessuale con l'oggetto più a portata di mano (madre, figlia, sorella), anche considerando che gli animali lo fanno senza scrupoli.
<li>Tutte le teorie precedenti ritengono che la morale che proibisce l'incesto si sia sviluppata nel tempo, pian piano. Eppure se si prende il popolo più arretrato (aborigeni australiani) è vietatissimo l'incesto.
<li>Viaggiando si era capito che gli usi riguardanti l'incesto erano i più vari: aborigeni completamente proibito, in altri obbligatorio. Nella famiglia reale egiziana era obbligatorio sposare la sorella. Alcune hanno una contraddizione interna (vietato, ma obbligatorio in una festa).
<li>Qualcuno sosteneva che l'incesto era vietato per evitare malattie genetiche, ma all'epoca non si conosceva il DNA e le malattie genetiche.
<p>Non è chiaro, addirittura, se per gli Aborigeni Australiani ci sia un collegamento tra il rapporto sessuale e la nascita del figlio. La spiegazione che spesso veniva riportata era che la donna rimanesse in cinta il giorno stesso in cui se ne accorgesse. La donna rimaneva in cinta a causa di quel particolare totem che era particolarmente dominante nel posto in cui la donna si trovasse nel momento in cui se ne accorgesse. Quindi è impossibile che l'incesto fosse vietato per motivi di discendenza.</p>
<li>Le tesi diffusioniste non possono essere usate perché le pulsioni della natura umana sono le stesse dappertutto e quindi è normale aspettarci comportamenti simili.
<p>Il diffusionismo è quell'idea che considera che quando una cultura comincia a fare una cosa, gli altri li copiano.  Gli uomini posso non aver sviluppato molti modi diversi, ma solo le usanze "positive" o "neutre" vengono eliminate. Questo spiega il motivo per cui molte usanze sono molto simili.</p>
</ol>
<p>Freud sviluppa una teoria incentrata sul <i>Complesso di Edipo</i>. Secondo Freud, la prima scelta dell'analisi sessuale del bambino è incestuosa. Freud sostiene che la parte cosciente della psiche prova un orrore per l'incesto, mentre la parte incosciente la desidera, facendo notare che la psiche e la coscienza non sono la stessa cosa (modello dell'iceberg). </p>
<p>Freud analizza il sistema Totemico australiano e scopre che è basato su due principi:</p>
<ul>
<li>Divieto di uccidere l'animale/piante a cui si appartiene
<li>Divieto di avere rapporti sessuali con compagni dell'altro sesso che appartengono allo stesso totem
</ul>
<p>Il Totem si può trasmettere per via di madre (matrilineare) o padre (patrilineare), in base alla tribù. Freud considera il sistema originario matrilineare, ma non porta delle giustificazioni per questa sua affermazione. Nel sistema matrilineare, l'incesto vietato è madre-figlio, mentre nel caso patrilineare è vietato l'incesto padre-figlia. Per vietare anche l'incesto non vietato dal sistema totemico, gli aborigeni, hanno creato una serie di classi matrimoniali, per fare in modo che all'individuo siano vietati i rapporti con il ~75% delle donne vicine a lui.</p>
<p>Freud si avvicina al problema affrontato l'argomento dell'<b>avoidances</b>, quell'insieme di usanze che evitano il contatto tra persone vicine. Secondo Freud sono forme attenuanti del divieto dell'incesto. Dietro il divieto dell'incesto, c'è un divieto di un rapporto affettivo tra le due persone. I fenomeni psichici (antipatie..) non hanno mai una causa sola, ma solitamente ne hanno molte, anche se ogni una sarebbe abbastanza per spiegare il fenomeno.</p>
<p>Secondo Freud i <b>rapporti tra generi e suoceri</b> sono difficili poiché quando l'investimento libidico passa da se stessi verso un oggetto esterno, non lo fa direttamente investendo un oggetto completamente esterno, ma su un oggetto vicino, come può essere la madre. Questo è la base del Complesso di Edipo. La presenza materna (della suocera) risveglia il sentimento di affetto per la propria madre che è stato difficilmente sorpassato. Questo comporta un rischio di regressione e quindi deve essere tenuto a distanza.</p>
<p>Freud è spesso accusato di <b>maschilismo</b>, poiché ricopre solo gli uomini dell'intenzione libidica. Parlando, però, del Freud Antropologo, esso, non è così assurdo.</p>
<p>Secondo Freud, possiamo affermare che l'<b>orrore dell'incesto</b> è un tratto "squisitamente infantile", in cui l'individuo non vuole che gli sia ricordato un elemento della vita infantile e che aveva rimosso in una fase precedente della sua vita psichica. Così questa regola è stata fatta per <b>evitare che l'uomo regredisca all'età infantile</b>. Secondo Freud, quando parliamo della creazione di nuove leggi, gli uomini sono spinti dall'affettività e non dalla razionalità, quindi sotto effetto di paure/angosce. Egli ritiene che gli uomini non calcolano quando creano regole, ma sono mossi - come marionette - dalle loro pulsioni, in questo caso, erotiche.</p>

<?php t("2", "Il tabù e l'ambivalenza dei sentimenti"); ?>
<p><b>Tabù</b> è una parola polinesiana che si può tradurre con l'espressione <i>"orrore sacro"</i>, cioè un sentimento di repulsione assoluta per qualcosa che è motivi che non sappiamo e di cui non riusciamo a trovare una giustificazione concreta. L'effetto del Tabù è reale, perché le persone lo rendono tale. Si può infrangere un Tabù senza saperlo, ma questo non fa cambiare la colpevolezza della persona.</p>
<p>La tematica psicoanalitica che è in gioco è il parallelo che c'è tra il tabù e le nevrosi ossessive. Le nevrosi ossessive sono una classe di nevrosi. I nevrosi ossessivi hanno una ossessività nel (non) compiere determinate azioni.</p>
<p>Freud elenca quattro punti di comunanza tra i nevrotici ossessivi e i Tabù</p>
<ol>
<li>Scarsa motivazione delle prescrizioni
<li>Consolidamento attraverso una necessità interiore
<li>Dislocabilità e contagiosità degli oggetti proibiti
<p>Alcuni oggetti e persone hanno un carattere tabù che passano agli oggetti con cui vengono in <b>contatto</b>. Coloro che seppelliscono il morto, diventano tabù. Il contatto anche per l'ossesso è molto pericoloso, infatti non entra in contatto con ceti oggetti.</p>
<li>Se si entra in contatto con qualcosa che è tabù ci sono delle forme di rituale che devono essere eseguiti
</ol>
<p>I tabù possono essere di varie specie</p>
<ul>
<li><b>Temporanei</b>: persone che entrano a contatto col cadavere)
<li><b>Eterni</b>: cadaveri
<li><b>Geografici</b>
<li><b>Trasgressori</b> del tabù.
</ul>
<p>Il tabù si differenzia dalla ossessione per alcuni aspetti</p>
<ul>
<li><b>Conoscenza della causa</b>
<p>Il <b>nevrotico</b> è a conoscenza della causa del tabù, infatti si proibisce il contatto con un'oggetto che aveva dato un grandissimo piacere nella primissima infanzia, ma a questo piacere si contrappone un divieto esterno a toccare queste cose e trova all'interno della psiche trova un rafforzamento. Secondo Freud le proibizioni vengono interiorizzate se arrivano da una figura temuta/amata/odiata, quindi c'è un'ambivalenza affettiva, come il padre. Così facendo si crea un'istanza interna, il <i>Super-Io</i>, cioè l'interiorizzazione del padre. Il conflitto tra desiderio e divieto può spiegare le dinamiche compulsive del nevrotico ossessivo e i tabù. La libido può essere trasformata o spostata, ma non si crea e non si distrugge. L'azione proibita è un'azione che l'inconscio vuole compiere.</p>
<p>Il <b>selvaggio</b> non sa spiegare il motivo per cui una determinata cosa è tabù.</p>
<li><b>* Fonte</b>: il nevrotico si auto-impone il tabù, mentre al selvaggio viene imposto dall'esterno
</ul>
<p>La <b>dislocabilità</b> del tabù, secondo Freud, è riconducibile alla capacità di associazione della nostra psiche. Il motivo del tabù e della nevrosi, è il concetto di contatto (fisico, o tramite nominazione).</p>
Il nevrotico </p>
<p>Freud analizza tre casi di tabù non totemici dei selvaggi:</p>
<ul>
<li>Tabù del sangue dei nemici
<p>Freud vuole dimostrare che le forme di prescrizione che sono imposte ai guerrieri che hanno ucciso dei nemici, sono il risultato di un'ambivalenza emotiva. Poiché è evidente il motivo per cui si giustifica questa azione, bisogna dimostrare che esista la pulsione che ci imponga di trattare i nemici con rispetto. Freud prova a eliminare l'ipotesi più ovvia e comune, che prevedeva la paura degli spiriti dei nemici. Freud sostiene che c'è un'<i>apparente legge di non uccidere</i>. Secondo Freud c'è un'<b>identificazione nel nemico ucciso</b>. Quindi nel provare quel minimo di rispetto e umanità che si prova nelle cerimonie di purificazione, è come se si provasse umanità verso se stessi, quando si verrà uccisi. Il carattere comune di queste purificazioni era la privazione di piaceri ed entrare in contatto con gli altri. L'idea che c'è ma che Freud non espone, è che colui che ha ucciso, ha provato un piacere che potrebbe averlo inebriato e quindi deve liberarsi da questo stato prima di ritornare nella società. Le osservanze che fanno parte di questo tabù, si possono dividere in:</p>
<ul>
<li>Riconciliazione con il nemico ucciso
<li>Limitazioni
<li>Pratiche espiatorie
<li>Pratiche cerimoniali
</ul>
<p>Il tabù in questione è ambivalente perché da un lato c'è la soddisfazione per averli uccisi, e dall'altro il necessario blocco di questi impulsi per tornare alla vita di tutti i giorni. Freud non lo dice in modo esplicito, ma è necessario che quell'atteggiamento aggressivo non contamini i momenti di vita normale. Per far questo ci vuole un momento di "quarantena". Freud non lo spiega in questi termini, ma spiega l'operazione opposta, cioè la necessità per il guerriero che si appresta ad andare in guerra a lasciar cadere tutti i freni inibitori che solitamente ha; esso deve, quindi, fare dei riti per favorire l'emersione dello spirito aggressivo.</p>
<li>Tabù che riguarda la figura del sovrano
<p>Nel caso dei sovrani, tutto è ambivalente. Un esempio è il contatto volontario (da parte del Re) ha effetti molto positivi (es: guarire dalla scrofola), mentre quello involontario può essere fatale. Il contatto con oggetti del Re, essendo un contatto non intenzionale da parte del Re, è egualmente pericoloso. Freud fa notare che questo rapporto ambivalente è tipico del rapporto padre-figlio, poiché il bambino attribuisce a sua padre l'onnipotenza (sia positiva sia negativa). Questa ambivalenza è facilmente capibile se avvicinata a quella paterna, il quale sembra onnipotente e però sbarra la strada verso uno dei voleri del bambino (incesto). L'attribuire a qualcuno un potere immenso (far guarire, e far ammalare) è la conseguenza di un <b>delirio paranoico</b>. Questo non è altro che <i>la proiezione su un'altra persona di quei poteri terribili che il bambino attribuisce al padre</i>.</p>
<p>Una contraddizione molto forte riguardo i sovrani è quella legata alla loro protezione. Al sovrano viene attribuito un grande potere sulle forze  naturali ma, nonostante questo, ci si  ritiene obbligati a proteggerlo. Spesso questa protezione diventa una forma di <b>apprensione</b> ed è paragonabile al rapporto madre-figlio. Anche questo è un rapporto ambivalente, poiché per <i>"amore"</i> si impone all'oggetto una vita molto limitata.<p>
</p>Frazer scopre che molti re sono uccisi ritualmente. C'è, quindi, una connessione tra il potere del Re e il sacrificio rituale che risulta statisticamente difficile da spiegare. In alcune società, però, il Re non viene sacrificato ma, al suo posto, ci sono dei <i>"doppi del re"</i> (giullari, carnevale, ...) che rappresentano il sacrificio rituale. Come già visto, il re è un sostituto della figura paterna; ci si spiega, quindi, il motivo di questi scoppi d'ira verso di esso. <b>Spesso venerazione e persecuzione sono cose che vanno assieme, quando si parla di umani.</b></p>
<p>Poichè il Re, in queste condizioni, non era in grado di governare, troviamo una divisione tra un re <i>"sacro"</i> e uno che si occupa di affari. Nella forma originale, il Re diventa garante che tutte le cose naturali succedano come devono (<i>regna</i>) mentre l'altro comanda.</p>
<p>Quando le azioni ossessive si trasformano in un complesso rituale, finiscono per costituire dei <b>deliri organizzati</b>. Freud, inizialmente, non pensa che la nostra cultura sia basata su deliri organizzati, perché pensa che un delirio organizzato si scontra prima o poi con la realtà e crolla. Dopo il 1933, analizzando il Nazzismo, Freud comincia a rivalutare la sua posizione, accetando che ci possa essere qualcosa come una paranoia totale.</p>
<p><i>Secondo interpretazioni di Frazer, i primi re erano stranieri che dopo un breve periodo di regno sarebbero stati sacrificati in una cerimonia sacra.</i> Freud sostiene che il Cristianesimo ancora abbia delle rimanenze di questo. Freud potrebbe alludere al fatto che Gesù è stato proclamato Re (INRI) e fornito di corona. Secondo Frazer, invece, questa è una grottesca presa in giro, come quella che avviene nelle Saturnali. Questo potrebbe essere visto come nuovi esempi di re-sacrificale.</p>
<li>Tabù che riguarda i morti
<p>Si può notare che ci sono moltissimi tabù intorno alla morte. Esempi sono: cadaveri, omicida, arma del delitto, coloro che toccano i morti, etc. Si è notato che il tabù dei morti è più forte quando le persone morte sono care (parenti, persone vicine), e meno forte quado i morti sono sconosciuti.</p>
<p> Westermark spiega questo sostenendo che la persona appena muore diventa un demone che vuole vendicarsi. Secondo le popolazioni aborigene, infatti, non esiste morte naturale, e tutte le persone vengono uccise o direttamente, o tramite la magia. La cosa che può colpire è il fatto che più la persona deceduta è vicina, più bisogna temere la sua ira. Inoltre bisogna considerare che i morti hanno un rapporto particolare con la morte, infatti c'è una specie di commistione tra i morti e la morte. Westermark sostiene che i morti diventano buoni solo dopo aver compiuto la loro vendetta. A questo punto diventano i buoni antenati, storicamente sempre onorati.</p>
<p>Freud accetta la spiegazione di Westermark, però non pensa che la spiegazione sia completa. Freud aggiunge alla teoria che quando una persona muore, è naturale che tutti coloro che hanno trattato male il morto si sentono parzialmente reposnsabili. Fermo restando che una persona che muore non ha voluto morire, stiamo male perché ci ha lasciati, e quindi si crea una corrente di ostilità verso il morto. Il sopravvissuto nega questo, in modo incosciente, per evitare una contraddizione emoriva, quindi proietta questo sentimento sul morto. Il demone è semplicemente l'odio che i vivi hanno verso il morto e che riproiettano su esso.</p>
<p>Freud basa la religione, la cultura e la società sulla proiezione. La definizione data da Freud di <b>proiezione</b> suppone che il cervello umano abbia, originariamente, solamente la funzione di percepire i processi esterni (eso-psichici) e percepisce i processi endo-psichici soltanto come forma di piacere o dispiacere. L'individuo non pensa a ciò che pensa, ma percepisce soltanto i sintomi esterni, il piacere e il dolore. I processi endo-psichici più potenti vengono attribuiti a un fenomeno eso-psichico. Il cervello umano trasforma in stimoli esterni gli stimoli interni poichè non è in grado di gestirli come stimoli interni. Proiettare costituisce la risposta più adattiva e, anche se il suo risultato è falso, può essere utile alla sopravvivenza. Gli spiriti, i demoni e le anime che "popolavano" il mondo antico sono da considerarsi come delle proiezioni dei processi endo-psichici. La proiezione è molto utilee per liberare la mente da contraddizioni che potrebbero arrecare danni all'individuo.</p>
<p>Il vedovo o la vedova sono pericolosi anche da un punto di vista sessuale. Inoltre loro, come anche gli altri parenti, possono essere scossi e quindi pericolosi.</p>
</ul>


<p><b>Colui che infrange un tabù, diventa a sua volta oggetto di tabù</b>. Freud cerca sempre risposte più ampie. Si chiede, perciò, perché ci sia un collegamento tra il tabù e chi lo trasgredisce. La risposta è che la persona risveglia negli altri la tentazione di fare quel qualcosa. Se la violazione del tabù non ha provveduto a punire la persona stessa, le altre persone lo puniranno, per paura dell'esempio negativo. Non di rado, le persone colgono la situazione per fare la stessa azione ma in modo "giustificato". Questo è uno dei fondamenti del sistema giudiziario moderno.</p>
<p>Il contatto da un punto di vista sociale è anche un contatto aggressivo. Freud, successivamente, si chiede se ci sono solo pulsioni per il piacere (sessuali) o altre pulsioni, come le pulsioni distruttive (di morte). Una persona terrorizzata, continua a sognare cose che lo terrorizzano, ma questo è contro la classe di pulsioni per il piacere, quindi - probabilmente - c'è un'altra classe di pulsioni. Questo, però, Freud lo pensa solo successivamente. Freud al momento sostiene che il mettere le mani addosso a qualcuno, sia una forma di trasformazione delle pulsioni sessuali.</p>

<p>Parallelo tra le azioni degli ossessi e dei tabù. Questo è manifesto nel fatto che entrambi i casi hanno un'ambivalenza conscio/inconscio. Così come il tabù si sposta perché si sposta il desiderio così i rituali dell'ossesso provengono da un'ambivalenza nei confronti di determinate azioni.</p>

<p>Se l'attenzione del cervello umano è essenzialmente rivolta verso l'esterno è prevedibile che i fenomeni interni alla psiche vengono vissuti come se fossero esterni. Quando un uomo si trova in condizioni estreme, l'attenzione per la vita interiore si affievolisce, e si acutizza l'attenzione per la vita esteriore. La proiezione sgombera la mente da contraddizioni affettive, proiettando all'esterno una delle due parti della contraddizione. Proiettando qualcosa al di fuori, si sgrava la mente, e credo di poter padroneggiare quella cosa.</p>
<p>Il sogno serve per garantire il prolungamento del sonno. Per questo non possono essere troppo espliciti, però non vengono censurate. Le pulsioni assumono una veste presentabile. L'operazione onirica primaria serve per evitare che la persona si svegli a causa di quello che ha sognato. L'operazione onirica secondaria. L'esigenza che il sogno non disturbi il sonno, il sogno necessita una certa logica (anche non completa). </p>
<p>Quando una persona proietta all'esterno propri sentimenti, gli deve fornire una veste di accettabilità. Il delirio paranoico ha la funzione di mettere in un sistema razionale pulsioni primitive che non ha nulla di razionalità. Lo psicotico può essere una persona in cui nulla più di coerente trapela, mentre nel paranoico, tutto è logico. La magia, l'animismo, la proiezione verso l'esterno, i demoni sono tipici dei sistemi paranoici. Per diventare collettive, devono per forza essere fenomeni logici, almeno in apparenza.</p>
<p>Freud pensa che nella civiltà moderna, il tabù della morte ha perso potere, rispetto al passato. La vita emotiva è diventata più tenera e ci sono più collegamenti positivi che negativi all'interno della famiglia. Quindi c'è meno motivo per odiare la persona che è morta, e di conseguenza proiettargli addosso il proprio odio.</p>
<p>Il tabù è anche alla base della nostra morale. Infatti moralità vuol dire la preclusione di compiere atti che seguono un desiderio. L'istanza morale che c'è dentro di me, è una istanza repressiva esterna, interiorizzata. Il tabù, come la morale, è frutto di una cultura che noi facciamo nostra (interiorizziamo) ma che è contro le nostre pulsioni. <i>Più la cultura è moralmente e sessualmente repressiva, più individui nevrotici e quindi infelici saranno presenti.</i> Non è pensabile una società nella quale nessuna morale/tabù è presente. <i>Il soddisfacimento sessuale è innanzi tutto un fatto privato dell'individuo.</i> È impossibile stringere relazioni pubbliche, senza distogliersi dal proprio partner. Le forze sessuali non cimentano le relazioni tra le persone. Il nevrotico grave ha delle pulsioni sessuali molto potenti, e fugge dalla realtà, perché esso è in contrasto con la società.</p>
<p>Nella prima teoria di Freud evidenzia due pulsioni: quelle erotiche e quelle di conservazione. Le prime devono essere tenute a freno per poter avere anche le seconde. Questa non è una teoria bipolare, perché entrambe le pulsioni sono pulsioni di piacere. Le seconde garantiscono nel tempo una maggiore continuità delle prime. Questa è una dottrina ottimistica, perché nel complesso è una struttura pulsionale che è tutta rivolta al piacere.</p>

<?php t("3", "Animismo, magia e onnipotenza dei pensieri"); ?>
<p>Freud riconduce una serie di pratiche, come la credenza nella magia, negli spiriti, etc, alla fase del narcisismo.</p>
<p>Freud pensa che ci sia uno sviluppo ordinato nello sviluppo umano.</p>
<p>Tutti i popoli hanno forme di magia, tranne quelli che ne sono terrorizzati. Il divieto biblico di fare immagini di esseri viventi (e di Dio) non nasce dall'idea che la magia non esiste, ma dal fatto che c'è il timore che un'immagine possa essere usata per scopi magici. Secondo gli egizi, quando il Dio del sole (Ra) calava (tramonto), esso stesse combattendo una lotta contro degli spiriti che provavano a prolungare il più possibile la notte. Il compito dei sacerdoti, era quello di creare immagini di questi demoni, e poi la figura veniva 'maltratta' per aiutare Ra a riemergere il mattino dall'orizzonte. L'azione sugli spiriti si chiama incantesimo. Le pratiche magiche sono antecedenti delle pratiche di incantesimo. Freud sottolinea che la magia è caratterizzata da una sopravvalutazione del pensiero. L'uomo attribuisce alla capacità di collegare due fenomeni psicologici anche a due fenomeni reali. Quando ci si offende, si pensa che questo possa essere una forma di reazione utile. Questa è una forma di sopravvalutazione del pensiero. I bambini molto piccoli non hanno quasi mai la capacità di agire, e quindi usano moltissimo questa capacità. Il piangere è la scoperta della propria debolezza nei confronti del mondo esterno. Il bambino cerca e trova soddisfazioni illusorie.</p>
<p>L'auto-erotismo che il bambino ha, spesso si manifesta come dito in bocca. La prima fase auto-erotica è caratterizzata da attenzioni verso una parte dell'oggetto e non la sua totalità. Nella seconda, invece è caratterizzata da attenzioni verso un'intero oggetto. Un caso del primo momento è la bocca. Il primo oggetto intero investito di una libidine è lui stesso. Questa è la fase narcisistica, e il bambino si comporta come se fosse innamorata di se stessa. È ancora incapace di investire un'esterno di libidine, ma è già in grado di vedere se stesso completamente come oggetto libidico. Come noi sopravvalutiamo la persona amata, così l'individuo nella fase narcisistica pensa di essere capace di quasi qualunque cosa. Se una persona rimane in questa fase, si diventa megalomani. Il narcisismo intellettuale e l'onnipotenza dei pensieri vanno di pari passo. Nel narcisismo l'individuo non fa i conti con la realtà esterna. Una persona può pensare di essere immortale solamente se è in una fase di esaltazione narcisistica. Il narcisista può raggiungere uno stato di ebrezza senza paragoni, poiché solo lui può vantare l'intera attenzione del suo oggetto di amore. Il narcisismo può acquisire una certa accettabilità se diffuso socialmente. In questi casi il narcisismo deve essere metodizzato e quindi può sopravvivere in modo collettivo senza che questo carattere faccia crollare la società.</p>
<?php file::footer(); ?>
